COMMANDS = [
("ls", "Files", "list directory contents", "ls [options] [path]",
 ["-l long format (permissions, owner, size, date)", "-a include hidden entries", "-h human-readable sizes", "-t sort by modification time", "-R recurse into subdirectories", "-i show inode numbers"],
 ["ls -lah /var/log", "ls -lt ~/Downloads | head -20", "ls -R src | less"],
 "the most-used command on any Linux system"),
("cd", "Files", "change the current working directory", "cd [path]",
 ["cd - go back to the previous directory", "cd ~ go home", "cd .. go up one level"],
 ["cd /var/log", "cd ~/projects/universe-ai", "cd -"],
 "in scripts, prefer absolute paths so the working directory cannot surprise you"),
("pwd", "Files", "print the absolute path of the current directory", "pwd",
 ["-P resolve symlinks to the physical path"],
 ["pwd", "cd /tmp && pwd -P"],
 "handy when a relative path misbehaves"),
("cp", "Files", "copy files and directories", "cp [options] source... destination",
 ["-r recursive (needed for directories)", "-a archive mode: -r plus preserve permissions, times, links", "-i ask before overwriting", "-u copy only when source is newer", "-v verbose"],
 ["cp -a project/ project-backup/", "cp -u *.conf /etc/app/ 2>/dev/null", "cp file.txt /tmp/"],
 "to copy across machines use rsync or scp instead"),
("mv", "Files", "move or rename files and directories", "mv [options] source... destination",
 ["-i ask before overwriting", "-n never overwrite", "-v verbose", "-u move only when source is newer"],
 ["mv report.pdf ~/Documents/", "mv old-name.txt new-name.txt", "mv -i *.log /var/tmp/"],
 "same filesystem = instant rename; different filesystem = copy + delete"),
("rm", "Files", "remove files and directories", "rm [options] target...",
 ["-r recursive (directories)", "-f force: no prompt, ignore missing", "-i interactive: ask for each file", "-I ask once before deleting many files", "-v verbose"],
 ["rm -i oldfile.txt", "rm -r build-cache/", "rm -f /tmp/*.tmp"],
 "there is no undo; double-check the path, and never run rm -rf with a variable that can be empty"),
("mkdir", "Files", "create directories", "mkdir [options] path...",
 ["-p create parents as needed, no error if it exists", "-m set permissions at creation", "-v verbose"],
 ["mkdir -p ~/projects/new-app/src", "mkdir -m 700 ~/private"],
 "mkdir -p is the safe default in scripts"),
("rmdir", "Files", "remove empty directories", "rmdir path...",
 ["-p remove the directory and its now-empty parents"],
 ["rmdir olddir/", "rmdir -p a/b/c"],
 "fails on non-empty directories by design; use rm -r for those"),
("touch", "Files", "create empty files or update timestamps", "touch [options] file...",
 ["-a change only access time", "-m change only modification time", "-t set a specific timestamp", "-c do not create the file"],
 ["touch notes.md", "touch -t 202601010000 project.stamp"],
 "also used to make a file look newer so make/rsync pick it up"),
("ln", "Files", "create hard or symbolic links", "ln [options] target linkname",
 ["-s symbolic (symlink) instead of hard link", "-f replace an existing link", "-n treat destination symlink as a file", "-v verbose"],
 ["ln -s /opt/app/current/config.yml ./config.yml", "ln -sf /usr/local/bin/python3.12 /usr/local/bin/python"],
 "prefer symlinks; hard links cannot cross filesystems or point to directories"),
("stat", "Files", "show detailed file or filesystem status", "stat [options] target",
 ["-c custom format", "-f filesystem info instead of file info", "-L follow symlinks"],
 ["stat /etc/hosts", "stat -c '%s %n' *.log", "stat -f /home"],
 "the go-to tool when you need exact sizes, inodes, or timestamps"),
("file", "Files", "identify a file's type from its contents", "file [options] target...",
 ["-i show MIME type", "-b brief: no filename prefix", "-L follow symlinks"],
 ["file mystery.bin", "file -i *.png"],
 "much smarter than guessing from the extension"),
("find", "Files", "search for files and directories by name, size, time and more", "find [path...] [expression]",
 ["-name pattern (case-sensitive glob)", "-iname case-insensitive name", "-type f|d|l only files/dirs/links", "-size +100M by size", "-mtime -7 modified in the last 7 days", "-exec command {} \\; run a command per hit", "-delete delete matches (dangerous)"],
 ["find ~/Downloads -type f -size +500M", "find /var/log -name '*.log' -mtime -1", "find . -type f -name '*.tmp' -delete"],
 "combine tests freely; -exec rm is a loaded gun - run without -exec first and look at the list"),
("locate", "Files", "find files by name using a prebuilt index", "locate [options] pattern",
 ["-i case-insensitive", "-b match only the basename", "-c count matches", "-e only existing files"],
 ["locate -i qwen3", "sudo updatedb && locate project.conf"],
 "instant, but only as fresh as the last updatedb run"),
("tree", "Files", "display a directory tree", "tree [options] [path]",
 ["-L N limit depth", "-a include hidden files", "-h human sizes", "-I pattern exclude matches", "--du show directory sizes"],
 ["tree -L 2 src/", "tree -I 'node_modules|__pycache__' -a"],
 "great for getting your bearings in an unfamiliar project"),
("basename", "Files", "strip the directory part of a path", "basename path [suffix]",
 ["-a treat every argument as a path", "-s strip a trailing suffix", "-z NUL-separated output"],
 ["basename /usr/share/doc/readme.gz .gz", "for f in *.log; do echo $(basename \"$f\" .log); done"],
 "the counterpart of dirname; both are script staples"),
("dirname", "Files", "strip the last component of a path", "dirname path...",
 ["-z NUL-separated output"],
 ["dirname /etc/nginx/nginx.conf", "cd \"$(dirname \"$0\")\""],
 "commonly used to resolve a script's own directory"),
("realpath", "Files", "resolve a path to its absolute, symlink-free form", "realpath [options] path",
 ["-e require all components to exist", "-m allow missing components", "--relative-to print relative to a base"],
 ["realpath ./config.yml", "realpath -m /opt/app/../app/bin"],
 "the reliable way to compare two paths that may contain symlinks"),
("readlink", "Files", "print the target of a symbolic link", "readlink [options] link",
 ["-f canonicalize by following every link", "-e require the target to exist", "-n no trailing newline"],
 ["readlink -f /usr/bin/python3", "readlink /etc/alternatives/editor"],
 "readlink -f is the classic one-liner for canonical paths"),
("shred", "Files", "overwrite a file to make recovery harder", "shred [options] file...",
 ["-n N number of overwrite passes", "-z add a final zero pass", "-u truncate and remove after overwriting", "-f force permissions change"],
 ["shred -uz secret.txt", "shred -n 3 -z disk.img"],
 "on SSDs, wear levelling means overwriting is not a guarantee - full-disk encryption is"),
("truncate", "Files", "shrink or extend a file to a given size", "truncate [options] file",
 ["-s SIZE set the size (K, M, G suffixes)", "-c do not create the file", "-o use an offset"],
 ["truncate -s 0 app.log", "truncate -s +1M data.bin"],
 "truncate -s 0 is the fast way to empty a live log file without breaking writers"),
("dd", "Files", "copy raw data block by block", "dd if=source of=target [bs=N] [count=N] [status=progress]",
 ["bs=N block size", "count=N number of blocks", "status=progress show progress", "conv=fsync flush at the end"],
 ["dd if=image.iso of=/dev/sdX bs=4M status=progress conv=fsync", "dd if=/dev/zero of=swapfile bs=1M count=4096"],
 "triple-check if= and of= before pressing Enter - writing the wrong device destroys data"),
("du", "Files", "estimate disk usage of files and directories", "du [options] [path]",
 ["-s summary per argument", "-h human-readable", "-a include files, not only directories", "--max-depth=N depth limit", "--exclude=pattern"],
 ["du -sh */ | sort -h", "du -ah /var | sort -rh | head -20"],
 "the standard first step of any disk-full investigation"),
("df", "Files", "report filesystem space usage", "df [options] [path]",
 ["-h human-readable", "-T show filesystem type", "-i inode usage instead of blocks", "-x exclude a filesystem type"],
 ["df -hT", "df -i /", "df -h /home /var /tmp"],
 "df full but du small usually means deleted files still held open (check lsof)"),
("mount", "Files", "attach a filesystem or device to the directory tree", "mount [options] device dir",
 ["-t fstype filesystem type", "-o options like ro, noexec, remount", "-a mount everything in fstab", "-l show labels"],
 ["mount /dev/sdb1 /mnt/usb", "mount -o remount,rw /", "mount -t iso9660 -o loop image.iso /mnt/iso"],
 "on modern systems use findmnt to inspect what is mounted where"),
("umount", "Files", "detach a mounted filesystem", "umount [options] target",
 ["-l lazy unmount: detach now, clean up when free", "-f force (use with care)", "-R unmount a subtree"],
 ["umount /mnt/usb", "umount -l /mnt/old"],
 "device busy means something still has a file open there - check with lsof or fuser"),
("lsblk", "Files", "list block devices as a tree", "lsblk [options]",
 ["-f show filesystem type, label, UUID", "-a include empty devices", "-o COLUMNS custom columns", "-p full device paths"],
 ["lsblk -f", "lsblk -o NAME,SIZE,TYPE,MOUNTPOINT"],
 "the safest way to see disks before touching them"),
("blkid", "Files", "print block device attributes (UUID, label, type)", "blkid [device]",
 ["-s tag show a specific tag", "-o value output the value only"],
 ["blkid", "blkid -s UUID -o value /dev/sda2"],
 "the output feeds /etc/fstab entries"),
("fdisk", "Files", "edit disk partition tables (MBR and GPT)", "fdisk [options] device",
 ["-l list partitions without editing", "-p print the table (interactive)", "-d delete a partition (interactive)", "-n new partition (interactive)"],
 ["fdisk -l", "fdisk /dev/sdb"],
 "changes are not written until you type w; q quits without saving"),
("parted", "Files", "create, resize and inspect partitions (scriptable)", "parted [options] device command",
 ["-s script mode: no prompts", "unit B print exact byte offsets", "resizepart N END resize partition N", "print show the table"],
 ["parted -s /dev/sdb mklabel gpt", "parted -s /dev/sdb mkpart primary ext4 1MiB 100%", "parted unit B print /dev/sda"],
 "resizepart takes an absolute END position, not a size - the classic foot-gun"),
("mkfs", "Files", "create a filesystem on a device or file", "mkfs -t fstype device",
 ["-t ext4|xfs|btrfs|vfat|exfat choose the type", "-L label set a filesystem label", "-F force on a non-empty target"],
 ["mkfs -t ext4 -L data /dev/sdb1", "mkfs -t vfat -F 32 /dev/sdc1"],
 "destroys everything already on the device; verify the device name twice"),
("fsck", "Files", "check and repair a filesystem", "fsck [options] device",
 ["-y assume yes to all questions", "-n answer no to everything (read-only check)", "-f force check even if clean", "-C progress bar"],
 ["sudo fsck -f /dev/sdb1", "fsck -n /dev/sda2"],
 "never run fsck on a mounted read-write filesystem - unmount first"),
("swapon", "Files", "enable swap devices and files", "swapon [options] target",
 ["-a enable everything in fstab", "-s show current swap", "--show summary"],
 ["sudo swapon /swapfile", "swapon --show", "free -h"],
 "swapon --show is the quickest swap check"),
("mkswap", "Files", "set up a swap area", "mkswap [options] device",
 ["-L label set a label", "-U UUID set a UUID"],
 ["mkswap /dev/sdb2", "sudo mkswap -L swap /swapfile && sudo swapon /swapfile"],
 "run mkswap before the first swapon on any new swap target"),
("cat", "Text", "print file contents to standard output", "cat [options] file...",
 ["-n number all lines", "-b number non-empty lines", "-A show invisible characters", "-s squeeze repeated blank lines"],
 ["cat /etc/hostname", "cat -n script.sh | head", "cat file1 file2 > merged.txt"],
 "for large files prefer less; cat is for small files and pipelines"),
("tac", "Text", "print files in reverse line order", "tac [options] file...",
 ["-s separator use a custom separator"],
 ["tac /var/log/app.log | head -50", "tac access.log | awk 'NR<=10'"],
 "the fastest way to read a log newest-first without tail maths"),
("less", "Text", "view file contents page by page", "less [options] file",
 ["/pattern search forward", "n / N next / previous match", "G end of file, g start", "F follow mode like tail -f"],
 ["less /var/log/syslog", "journalctl -b | less"],
 "better than more: scrolls both ways and searches"),
("head", "Text", "show the first lines of a file", "head [options] file...",
 ["-n N first N lines", "-c N first N bytes", "-q never print file headers"],
 ["head -n 20 access.log", "head -c 512 disk.img | xxd | head"],
 "the counterpart of tail; -n 1 is common in scripts"),
("tail", "Text", "show the last lines of a file", "tail [options] file...",
 ["-n N last N lines", "-f follow the file as it grows", "-F like -f but reopen if the file is rotated", "--pid=PID stop following when process exits"],
 ["tail -n 100 app.log", "tail -F /var/log/nginx/error.log", "tail -f app.log --pid=1234"],
 "tail -F is the standard live-log viewer"),
("nl", "Text", "number the lines of a file", "nl [options] file",
 ["-b a number all lines", "-s STRING custom separator", "-w N number width"],
 ["nl -ba script.sh | less", "grep -n error app.log"],
 "grep -n covers most numbering needs, but nl gives clean control"),
("wc", "Text", "count lines, words and bytes", "wc [options] file...",
 ["-l lines", "-w words", "-c bytes", "-m characters"],
 ["wc -l access.log", "grep -c ERROR app.log", "find . -name '*.py' | xargs wc -l | tail -1"],
 "wc -l on a log is the classic 'how many errors' one-liner with grep"),
("sort", "Text", "sort lines of text", "sort [options] file...",
 ["-n numeric sort", "-h human-readable numbers (2K, 1M)", "-r reverse", "-k N field to sort on", "-t C field separator", "-u unique output", "-V version sort"],
 ["sort -h sizes.txt | tail", "du -sh */ | sort -rh | head", "sort -t: -k3 -n /etc/passwd"],
 "pairs perfectly with uniq and du/df output"),
("uniq", "Text", "filter or count adjacent duplicate lines", "uniq [options] [input [output]]",
 ["-c prefix lines with a count", "-d only duplicated lines", "-u only unique lines", "-i ignore case"],
 ["sort access.log | uniq -c | sort -rn | head", "sort ips.txt | uniq -c"],
 "input must be sorted first - uniq only compares neighbours"),
("cut", "Text", "extract columns from each line", "cut [options] [file]",
 ["-d C delimiter (default TAB)", "-f N field(s) to print", "-c N character positions", "--complement invert the selection"],
 ["cut -d: -f1 /etc/passwd", "cut -c1-8 file.txt", "df -h | cut -d' ' -f1"],
 "for anything more complex than columns, awk is the right tool"),
("tr", "Text", "translate or delete characters", "tr [options] SET1 [SET2]",
 ["-d delete characters in SET1", "-s squeeze repeats", "-c complement SET1", "a-z A-Z ranges"],
 ["echo hello | tr a-z A-Z", "cat file | tr -d '\\r' > clean", "tr -s ' ' < messy.txt"],
 "works on characters, not words; sed handles strings"),
("sed", "Text", "stream editor for filtering and transforming text", "sed [options] 'script' [file]",
 ["-i edit files in place", "-n suppress automatic printing (use with p)", "-e multiple scripts", "s/a/b/g substitute globally", "d delete lines, p print lines"],
 ["sed -n '10,20p' file.txt", "sed -i 's/old/new/g' config.ini", "sed '/^#/d' config.ini"],
 "sed -i rewrites the file - test the script without -i first"),
("awk", "Text", "pattern scanning and field processing language", "awk 'pattern { action }' [file]",
 ["-F C field separator", "NR line number, NF number of fields", "$1..$N fields", "-v var=value pass a variable in"],
 ["awk -F: '{print $1}' /etc/passwd", "awk '$9 == 404 {print $7}' access.log | sort | uniq -c", "awk 'NR>1 {sum+=$2} END {print sum}' data.txt"],
 "the swiss-army knife of log and column processing"),
("grep", "Text", "search text for lines matching a pattern", "grep [options] pattern [file...]",
 ["-r recursive", "-i ignore case", "-n show line numbers", "-v invert match", "-E extended regex (egrep)", "-F fixed strings (fgrep)", "-c count matching lines", "-l only filenames", "-A/-B/-C N context lines"],
 ["grep -rn TODO src/", "journalctl -u nginx | grep -i error", "grep -A3 -B1 'panic' kernel.log"],
 "the single most useful text tool; combine with -r for code trees"),
("rg", "Text", "fast recursive search (ripgrep)", "rg [options] pattern [path]",
 ["-i case-insensitive", "-n line numbers", "-l filenames only", "-t TYPE restrict to file type", "-uu include hidden and ignored files"],
 ["rg -n 'def main' -t py", "rg -i error --glob '*.log'", "rg -uu 'api_key'"],
 "respects .gitignore by default, which is usually what you want"),
("tee", "Text", "write input to a file and to standard output", "command | tee [options] file...",
 ["-a append instead of overwrite", "-i ignore interrupt signals"],
 ["make 2>&1 | tee build.log", "echo value | sudo tee /etc/sysctl.d/99-x.conf"],
 "the standard trick for writing to root-owned files without a shell redirect"),
("xargs", "Text", "build and run command lines from standard input", "xargs [options] [command]",
 ["-n N max arguments per command", "-0 NUL-separated input (for filenames with spaces)", "-I {} replace {} with each item", "-P N run N processes in parallel", "-r do nothing on empty input"],
 ["find . -name '*.tmp' -print0 | xargs -0 rm -f", "cat urls.txt | xargs -n1 -P4 curl -sO", "find . -name '*.png' | xargs -I{} cp {} /backup/"],
 "always pair with find -print0 / xargs -0 when filenames may contain spaces"),
("split", "Text", "split a file into pieces", "split [options] [file [prefix]]",
 ["-l N N lines per piece", "-b SIZE bytes per piece", "-d numeric suffixes", "-a N suffix length"],
 ["split -l 10000 big.csv part-", "split -b 1900M archive.tar part-"],
 "the classic way to make upload-sized chunks"),
("paste", "Text", "merge lines of files side by side", "paste [options] file...",
 ["-d C delimiter between columns", "-s serial: one file per line"],
 ["paste names.txt phones.txt", "paste -sd, values.txt"],
 "the horizontal counterpart of cat"),
("join", "Text", "join lines of two files on a common field", "join [options] file1 file2",
 ["-1 N field in file1", "-2 N field in file2", "-t C field separator", "-a N also print unpairable lines"],
 ["join -t, users.csv orders.csv", "sort a.txt > a.s; sort b.txt > b.s; join a.s b.s"],
 "both inputs must be sorted on the join field"),
("comm", "Text", "compare two sorted files line by line", "comm [options] file1 file2",
 ["-1 suppress column 1 (only in file1)", "-2 suppress column 2", "-3 suppress column 3 (common lines)"],
 ["comm -23 list-new list-old", "comm -12 a.txt b.txt"],
 "the three-column output is exactly what diff-oriented scripts need"),
("diff", "Text", "compare files line by line", "diff [options] file1 file2",
 ["-u unified format (like git diff)", "-r recursive directory compare", "-q only say whether files differ", "-i ignore case", "-w ignore whitespace"],
 ["diff -u old.conf new.conf", "diff -rq dir1 dir2", "git diff --stat"],
 "read unified diffs as: - old lines, + new lines, @@ hunk headers"),
("patch", "Text", "apply a diff to files", "patch [options] [file [patchfile]]",
 ["-p N strip N leading path components", "-R reverse an applied patch", "--dry-run test without changing anything"],
 ["patch -p1 < fix.patch", "patch --dry-run -p0 < change.diff"],
 "always --dry-run first when the tree may have drifted"),
("column", "Text", "format text into aligned columns", "column [options] [file]",
 ["-t table mode", "-s C input delimiter", "-N names header names", "-J JSON output"],
 ["mount | column -t", "cat data.csv | column -t -s,"],
 "turns ragged command output into something readable"),
("strings", "Text", "print printable strings from binary files", "strings [options] file",
 ["-n N minimum length", "-t x offset format", "-a scan the whole file"],
 ["strings /usr/bin/ls | grep -i version", "strings -n 8 firmware.bin | head -50"],
 "first stop when a binary contains an unknown message"),
("tar", "Archives", "create and extract archive files", "tar [options] [archive] [files...]",
 ["-c create", "-x extract", "-t list", "-f archive filename", "-v verbose", "-z gzip", "-J xz", "--zstd zstd", "-C DIR change directory first"],
 ["tar -czf backup.tar.gz ~/project", "tar -xzf backup.tar.gz -C /tmp/restore", "tar --zstd -xf model.tar.zst"],
 "remember the -f always comes right before the archive name"),
("gzip", "Archives", "compress files with gzip", "gzip [options] [file...]",
 ["-d decompress", "-k keep the original file", "-9 best compression", "-1 fastest", "-l list compressed info"],
 ["gzip -9 big.log", "gzip -dk archive.gz", "zgrep -i error app.log.gz"],
 "replaces the file with file.gz unless -k is given"),
("bzip2", "Archives", "compress files with bzip2 (better ratio, slower)", "bzip2 [options] [file...]",
 ["-d decompress", "-k keep original", "-9 best compression"],
 ["bzip2 -9 data.tar", "bunzip2 data.tar.bz2"],
 "mostly superseded by xz/zstd today"),
("xz", "Archives", "compress files with xz (very high ratio)", "xz [options] [file...]",
 ["-d decompress", "-k keep original", "-9 extreme compression", "-T0 multithreaded"],
 ["xz -9 -T0 bigfile.tar", "xz -dk file.xz"],
 "slowest of the common compressors; best for long-term archives"),
("zstd", "Archives", "fast compression with a great ratio", "zstd [options] [file...]",
 ["-d decompress", "-19 high compression", "-T0 all cores", "-o output file", "--long long-distance matching"],
 ["zstd -19 -T0 model.gguf -o model.gguf.zst", "zstd -d model.gguf.zst"],
 "the modern default for large files"),
("zip", "Archives", "create zip archives (cross-platform)", "zip [options] archive.zip files...",
 ["-r recurse into directories", "-9 best compression", "-e encrypt with a password", "-x exclude pattern"],
 ["zip -r site.zip public/", "zip -9 -r src.zip src -x '*.git*'"],
 "the format to use when Windows users will open the file"),
("unzip", "Archives", "extract zip archives", "unzip [options] archive.zip",
 ["-l list contents without extracting", "-d DIR extract into DIR", "-o overwrite without asking", "-P pass extract with password"],
 ["unzip -l bundle.zip", "unzip -d /tmp/out bundle.zip"],
 "list first when you do not know what is inside"),
("chmod", "Permissions", "change file mode bits (permissions)", "chmod [options] mode file...",
 ["u/g/o/a user/group/other/all", "+/-/= add/remove/set", "r/w/x read/write/execute", "numeric: 4=r 2=w 1=x, e.g. 644, 755, 600", "-R recursive"],
 ["chmod 600 ~/.ssh/config", "chmod +x script.sh", "chmod -R u=rwX,g=rX,o= project/"],
 "the capital X in -R mode sets execute only on directories"),
("chown", "Permissions", "change file owner and group", "chown [options] owner[:group] file...",
 ["-R recursive", "--reference=file copy ownership from another file", "-h affect symlinks themselves"],
 ["sudo chown -R user:user ~/project", "chown --reference=ref.txt new.txt"],
 "forgetting -R on a copied tree is the classic docker/mount permission bug"),
("chgrp", "Permissions", "change the group of files", "chgrp [options] group file...",
 ["-R recursive", "--reference=file copy the group from a file"],
 ["sudo chgrp -R developers /srv/app"],
 "same semantics as chown but only touches the group"),
("umask", "Permissions", "show or set the default permission mask", "umask [-S] [mask]",
 ["-S symbolic output", "mask 022 gives 755 dirs / 644 files"],
 ["umask", "umask 077"],
 "077 makes new files private by default - a good habit on shared machines"),
("sudo", "Permissions", "run a command with elevated privileges", "sudo [options] command",
 ["-i login shell as root", "-u USER run as another user", "-l list allowed commands", "-k invalidate the cached credential"],
 ["sudo apt update", "sudo -u postgres psql", "sudo -l"],
 "on Universe OS, sudo is a graphical consent gate - the dialog IS the password prompt"),
("su", "Permissions", "switch user or start a shell as another user", "su [options] [user]",
 ["- login shell (full environment)", "-c command run a single command", "-s shell choose a shell"],
 ["su - deploy -c 'whoami'", "sudo su -"],
 "prefer sudo -u for single commands; su changes the whole session"),
("passwd", "Permissions", "change a user's password", "passwd [options] [user]",
 ["-l lock an account", "-u unlock", "-e force expiry at next login", "-S status"],
 ["passwd", "sudo passwd alice", "sudo passwd -S bob"],
 "regular users can only change their own password"),
("useradd", "Permissions", "create a user account", "useradd [options] username",
 ["-m create the home directory", "-s shell login shell", "-G groups supplementary groups", "-c comment", "-d home path"],
 ["sudo useradd -m -s /bin/bash alice", "sudo useradd -m -G sudo,docker bob"],
 "pair with passwd to set the password afterwards"),
("usermod", "Permissions", "modify an existing user account", "usermod [options] username",
 ["-aG groups append to supplementary groups (keep -a!)", "-s shell change shell", "-L lock, -U unlock", "-d/-m move home"],
 ["sudo usermod -aG docker alice", "sudo usermod -s /bin/zsh bob"],
 "omitting -a with -G replaces the user's whole group list - a classic mistake"),
("userdel", "Permissions", "delete a user account", "userdel [options] username",
 ["-r also remove the home directory and mail spool", "-f force even if logged in"],
 ["sudo userdel -r olduser"],
 "decide first whether the home directory data must be kept"),
("groupadd", "Permissions", "create a group", "groupadd [options] group",
 ["-g GID specific group id", "-r system group"],
 ["sudo groupadd developers", "sudo groupadd -g 1500 project"],
 "add users with usermod -aG afterwards"),
("groups", "Permissions", "show group memberships", "groups [user]",
 ["no options to remember - just the user name"],
 ["groups", "groups alice"],
 "after usermod -aG, the user must log out and back in to see the new group"),
("id", "Permissions", "show user and group identity", "id [options] [user]",
 ["-u user id only", "-g primary group id", "-G all group ids", "-n names instead of numbers"],
 ["id", "id alice", "id -nG"],
 "the first command to run when permissions behave strangely"),
("getfacl", "Permissions", "show access control lists", "getfacl [options] file...",
 ["-R recursive", "-p absolute paths", "-c omit comment header"],
 ["getfacl /srv/shared", "getfacl -R project/ | head -40"],
 "ACLs give per-user permissions beyond owner/group/other"),
("setfacl", "Permissions", "set access control lists", "setfacl [options] file...",
 ["-m modify entries (u:alice:rwx)", "-x remove entries", "-b remove all ACLs", "-R recursive", "-d default ACLs for new files"],
 ["setfacl -m u:alice:rwx /srv/shared", "setfacl -R -m g:devs:rwX project/"],
 "ls -l shows a + next to the mode when an ACL is present"),
("chattr", "Permissions", "change ext4 file attributes", "chattr [options] [+/-=attributes] file...",
 ["+i immutable: cannot be changed even by root until removed", "+a append-only", "+e extent format (default)"],
 ["sudo chattr +i /etc/resolv.conf", "sudo chattr -i /etc/resolv.conf"],
 "immutable is a strong anti-tamper trick; remember how to remove it"),
("lsattr", "Permissions", "list ext4 file attributes", "lsattr [options] [files...]",
 ["-R recursive", "-a include hidden files", "-d directories themselves"],
 ["lsattr /etc/resolv.conf", "lsattr -R /etc | grep -i '^....i'"],
 "use it to find files that resist deletion"),
("ps", "Processes", "report a snapshot of running processes", "ps [options]",
 ["aux every process with user-oriented detail", "-ef full listing", "--sort=-%cpu sort by cpu", "--sort=-%mem sort by memory", "-p PID specific process"],
 ["ps aux | grep nginx", "ps aux --sort=-%mem | head", "ps -ef --forest | less"],
 "ps is a snapshot; use top/htop for live monitoring"),
("top", "Processes", "live view of processes and system load", "top [options]",
 ["-b batch mode for scripts", "-n N refresh N times then exit", "-o %MEM sort field", "-p PID only specific processes"],
 ["top -b -n1 | head -20", "top -o %MEM"],
 "press M inside top to sort by memory, P for CPU, q to quit"),
("htop", "Processes", "interactive process viewer (friendlier top)", "htop [options]",
 ["F3 search, F4 filter", "F5 tree view", "F6 sort column", "F9 kill"],
 ["htop", "htop -u alice"],
 "not installed everywhere; top is always available"),
("kill", "Processes", "send a signal to a process", "kill [-SIGNAL] PID...",
 ["-15 TERM polite termination (default)", "-9 KILL force, cannot be caught", "-1 HUP reload", "-l list signals"],
 ["kill 1234", "kill -9 1234", "kill -HUP $(cat /run/nginx.pid)"],
 "try TERM before KILL: -9 can leave locks and temp files behind"),
("pkill", "Processes", "kill processes by name or other attributes", "pkill [options] pattern",
 ["-f match the full command line", "-u USER only that user's processes", "-9 force", "-x exact name match"],
 ["pkill -f 'python3 app.py'", "pkill -u alice -x firefox"],
 "pkill -f is powerful and dangerous: it can match your own shell command"),
("killall", "Processes", "kill processes by exact name", "killall [options] name",
 ["-9 force", "-i interactive confirmation", "-u USER user's processes", "-w wait for exit"],
 ["killall firefox", "killall -9 crashyapp"],
 "exact-name matching, unlike pkill's pattern matching"),
("pgrep", "Processes", "find process IDs by name", "pgrep [options] pattern",
 ["-f full command line", "-a print the full command", "-u USER filter by user", "-c count only"],
 ["pgrep -a nginx", "pgrep -u alice -f python"],
 "the safe half of pkill: look first, then decide"),
("nice", "Processes", "start a process with a chosen scheduling priority", "nice [options] command",
 ["-n N niceness from -20 (highest) to 19 (lowest)"],
 ["nice -n 19 rsync -a bigdir/ /backup/", "nice -n -5 game"],
 "positive niceness = lower priority = friendlier to the desktop"),
("renice", "Processes", "change the priority of a running process", "renice -n N -p PID",
 ["-p PID target process", "-u USER all of a user's processes"],
 ["sudo renice -n 10 -p 1234", "renice -n 5 -u alice"],
 "only root can raise priority (negative niceness)"),
("jobs", "Processes", "list background jobs of the current shell", "jobs [options]",
 ["-l include PIDs", "-r running only", "-s stopped only"],
 ["jobs -l", "kill %1"],
 "each shell session has its own job table"),
("fg", "Processes", "bring a background job to the foreground", "fg [%job]",
 ["%N job number from jobs"],
 ["fg", "fg %2"],
 "Ctrl+Z stops a job, bg sends it to the background, fg brings it back"),
("bg", "Processes", "resume a stopped job in the background", "bg [%job]",
 ["%N job number from jobs"],
 ["bg %1", "jobs"],
 "useful after Ctrl+Z when a long build should keep running"),
("nohup", "Processes", "run a command immune to hangup signals", "nohup command [args] &",
 ["output goes to nohup.out by default", "pair with & and redirects for a real detach"],
 ["nohup ./server.sh > server.log 2>&1 &", "nohup rsync -a src/ dest/ > rsync.log 2>&1 &"],
 "for full detachment on modern systems use setsid + redirects"),
("disown", "Processes", "remove jobs from the shell's job table", "disown [options] [%job]",
 ["-h keep the job but ignore SIGHUP", "-a all jobs", "-r running only"],
 ["disown -h %1", "sleep 100 & disown"],
 "after disown the job survives the shell exiting"),
("time", "Processes", "measure how long a command takes", "time command",
 ["reports real, user and sys time", "the bash builtin differs from /usr/bin/time -v"],
 ["time make -j8", "/usr/bin/time -v ./benchmark"],
 "real is wall clock; user+sys is actual CPU time"),
("timeout", "Processes", "run a command with a time limit", "timeout [options] DURATION command",
 ["s/K/M suffixes: 30s, 5m", "-k extra kill-after time", "--preserve-status keep the command's exit code", "-s SIGNAL choose the signal"],
 ["timeout 30s ping -c 100 example.com", "timeout -k 5s 2m ./long-task.sh"],
 "the standard way to keep scripts from hanging forever"),
("watch", "Processes", "run a command repeatedly and show the output", "watch [options] command",
 ["-n N interval seconds", "-d highlight differences", "-t no header", "-c show colors"],
 ["watch -n2 'df -h /'", "watch -d -n1 sensors"],
 "perfect for disk, memory or temperature that you want to eyeball"),
("strace", "Processes", "trace system calls and signals of a process", "strace [options] command",
 ["-f follow child processes", "-p PID attach to a running process", "-e trace=openat,read filter calls", "-c summary of time per call", "-o file write to a file"],
 ["strace -f -e trace=openat ./app 2>&1 | grep ENOENT", "strace -c ls", "strace -p 1234"],
 "the definitive tool for 'why does this program fail' when logs say nothing"),
("ltrace", "Processes", "trace library calls of a process", "ltrace [options] command",
 ["-p PID attach", "-e filter specific functions", "-c summary"],
 ["ltrace ./binary", "ltrace -e malloc+free ./app"],
 "useful when the bug is in library usage rather than syscalls"),
("lsof", "Processes", "list open files and the processes using them", "lsof [options]",
 ["-i network sockets", "-i :PORT who uses a port", "-p PID files of a process", "-u USER user's files", "+D DIR files under a directory", "-nP numeric ports, no DNS"],
 ["lsof -i :8080", "lsof +D /mnt/usb", "lsof | grep deleted"],
 "'device busy' or 'deleted file still filling the disk' - lsof answers both"),
("fuser", "Processes", "identify processes using files or sockets", "fuser [options] target...",
 ["-m mounted filesystem users", "-n tcp -k PORT kill users of a port", "-v verbose listing"],
 ["fuser -v /mnt/usb", "fuser -k -n tcp 3000"],
 "the fastest 'what is holding this mount' answer"),
("tmux", "Processes", "terminal multiplexer: persistent sessions and split panes", "tmux [options]",
 ["new -s name create a session", "attach -t name reattach", "detach (prefix d) leave it running", "split panes: prefix % or \"", "ls list sessions"],
 ["tmux new -s work", "tmux attach -t work", "tmux ls"],
 "a long build survives your ssh dropping - that is the point"),
("screen", "Processes", "older terminal multiplexer with the same idea", "screen [options]",
 ["-S name create a named session", "-r reattach", "-ls list sessions", "-d detach elsewhere"],
 ["screen -S build", "screen -ls", "screen -r build"],
 "tmux is usually the better choice today"),
("systemctl", "Systemd", "control systemd units and services", "systemctl [options] command [unit]",
 ["status UNIT detailed state + recent logs", "start / stop / restart UNIT", "enable / disable UNIT at boot", "is-active / is-enabled quick checks", "list-units --failed broken units", "daemon-reload after unit file changes"],
 ["systemctl status nginx", "sudo systemctl restart ssh", "systemctl --failed", "systemctl enable --now docker"],
 "after editing a unit file, daemon-reload is mandatory"),
("journalctl", "Systemd", "query the systemd journal (logs)", "journalctl [options]",
 ["-u UNIT logs for a unit", "-b current boot (-b -1 previous)", "-f follow live", "-p err priority filter", "--since / --until time range", "-n N last N lines", "--disk-usage, --vacuum-size cleanup", "-xe most recent errors"],
 ["journalctl -u nginx -n 50", "journalctl -b -p err", "journalctl -f -u docker", "journalctl --since '1 hour ago'"],
 "the first stop for any modern service problem"),
("systemd-analyze", "Systemd", "analyze boot performance and unit sanity", "systemd-analyze [command]",
 ["blame slowest units", "critical-chain boot dependency chain", "verify unit files", "plot SVG timeline"],
 ["systemd-analyze blame | head -20", "systemd-analyze critical-chain", "systemd-analyze verify /etc/systemd/system/foo.service"],
 "'boot is slow' is answered by blame and critical-chain"),
("coredumpctl", "Systemd", "inspect and manage core dumps", "coredumpctl [command]",
 ["list dumps", "info PID details of one dump", "debug PID open it in gdb", "dump PID save the core file"],
 ["coredumpctl list", "coredumpctl info 12345", "coredumpctl debug ./crashyapp"],
 "the modern replacement for hunting core files by hand"),
("loginctl", "Systemd", "control login sessions and users", "loginctl [command]",
 ["list-sessions", "list-users", "terminate-session N", "show-session N details"],
 ["loginctl list-sessions", "loginctl terminate-user alice"],
 "useful on multi-session and remote machines"),
("hostnamectl", "Systemd", "view or set the hostname and machine info", "hostnamectl [command]",
 ["status show hostname, OS, kernel, virtualization", "set-hostname NAME change it", "set-chassis desktop|laptop|vm"],
 ["hostnamectl", "sudo hostnamectl set-hostname devbox"],
 "one command for the classic three-file hostname dance"),
("timedatectl", "Systemd", "view or set system time, date and timezone", "timedatectl [command]",
 ["status overview", "set-timezone REGION/CITY", "set-ntp true|false toggle NTP", "list-timezones"],
 ["timedatectl", "sudo timedatectl set-timezone Asia/Tehran", "sudo timedatectl set-ntp true"],
 "check set-ntp first when the clock drifts"),
("localectl", "Systemd", "view or set locale and keyboard layout", "localectl [command]",
 ["status current settings", "set-locale LANG=...", "set-keymap us|de|...", "list-keymaps"],
 ["localectl status", "sudo localectl set-keymap de"],
 "the supported way to change console and X11 keyboard defaults"),
("resolvectl", "Systemd", "inspect and control DNS resolution", "resolvectl [command]",
 ["status per-link DNS state", "query NAME resolve like dig", "flush-caches clear the cache", "statistics cache hits"],
 ["resolvectl status", "resolvectl query example.com", "sudo resolvectl flush-caches"],
 "systemd-resolved's own front-end; use it before editing resolv.conf"),
("uname", "System", "print kernel and system information", "uname [options]",
 ["-a everything", "-r kernel release", "-m machine architecture", "-o operating system"],
 ["uname -a", "uname -r"],
 "uname -r is the kernel version you compare against driver requirements"),
("hostname", "System", "show or set the system hostname", "hostname [options] [name]",
 ["-I all IP addresses", "-f fully qualified name", "-s short name"],
 ["hostname", "hostname -I", "sudo hostname newname"],
 "hostnamectl is the modern way to set it permanently"),
("uptime", "System", "show how long the system has been running and load averages", "uptime [options]",
 ["-p pretty format", "-s since when"],
 ["uptime", "uptime -p"],
 "load average above the CPU core count means oversubscription"),
("free", "System", "show memory and swap usage", "free [options]",
 ["-h human-readable", "-m/-g megabytes/gigabytes", "-s N repeat every N seconds", "-t totals"],
 ["free -h", "free -m -s 5"],
 "look at 'available', not 'free': Linux uses spare RAM as cache on purpose"),
("vmstat", "System", "report virtual memory, CPU and IO statistics", "vmstat [interval] [count]",
 ["-s summary table", "-d disk stats", "-w wide output"],
 ["vmstat 1 10", "vmstat -s | head"],
 "the si/so columns reveal actual swapping; watch them under load"),
("iostat", "System", "report CPU and disk IO statistics", "iostat [options] [interval] [count]",
 ["-x extended disk stats", "-m megabytes", "-z skip idle devices"],
 ["iostat -xz 1 5", "iostat -m"],
 "await and %util tell you when a disk is the bottleneck"),
("mpstat", "System", "per-CPU statistics", "mpstat [options] [interval] [count]",
 ["-P ALL every core", "-u CPU utilization (default)", "-I interrupts"],
 ["mpstat -P ALL 1 3"],
 "one hot core while others idle usually means a single-thread bottleneck"),
("sar", "System", "historical system activity reports", "sar [options] [interval] [count]",
 ["-u CPU history", "-r memory history", "-d disk history", "-n DEV network"],
 ["sar -u 1 5", "sar -r -f /var/log/sysstat/sa15"],
 "the only tool that answers 'what was the load like yesterday at 3pm'"),
("dmesg", "System", "print kernel ring buffer messages", "dmesg [options]",
 ["-T human timestamps", "-w follow live", "-l err,warn filter levels", "-H pager with colors"],
 ["dmesg -T | tail -50", "sudo dmesg -T -l err,warn", "dmesg -w"],
 "hardware errors, USB events and OOM kills all land here first"),
("lsmod", "System", "list loaded kernel modules", "lsmod",
 ["the output columns are: name, size, used-by count"],
 ["lsmod | head", "lsmod | grep nvidia"],
 "when a driver 'does nothing', check whether its module is even loaded"),
("modprobe", "System", "load or unload kernel modules (with dependencies)", "modprobe [options] module [param=value]",
 ["-r remove a module", "-n dry run", "module blacklist lives in /etc/modprobe.d/"],
 ["sudo modprobe nvidia", "sudo modprobe -r usb_storage", "modprobe -n -v brd"],
 "prefer modprobe over insmod: it resolves dependencies and options"),
("lspci", "System", "list PCI devices", "lspci [options]",
 ["-k kernel driver in use", "-nn numeric and names", "-v verbose"],
 ["lspci -k | grep -A3 -i vga", "lspci -nn"],
 "GPU and network controller identification starts here"),
("lsusb", "System", "list USB devices", "lsusb [options]",
 ["-t tree view", "-v verbose descriptors", "-d vendor:product filter"],
 ["lsusb", "lsusb -t"],
 "dmesg + lsusb together explain most USB mysteries"),
("lscpu", "System", "show CPU architecture information", "lscpu [options]",
 ["-e extended per-core table", "-p parseable output", "-C cache details"],
 ["lscpu", "lscpu | grep -E 'Model name|Socket|Core|Thread'"],
 "tells you cores vs threads before you tune make -j"),
("lsmem", "System", "show memory ranges and their online state", "lsmem [options]",
 ["--summary overview only"],
 ["lsmem --summary"],
 "useful on machines with memory hotplug"),
("sensors", "System", "show temperatures, voltages and fan speeds", "sensors [options]",
 ["-A no adapter headers", "-j JSON output", "-u raw units"],
 ["sensors", "watch -n2 sensors"],
 "from the lm-sensors package; run sensors-detect once to configure"),
("nproc", "System", "print the number of processing units available", "nproc [options]",
 ["--all total installed", "--ignore=N subtract N"],
 ["nproc", "make -j$(nproc)"],
 "the portable way to write -j$(nproc) in build scripts"),
("acpi", "System", "show battery and thermal information", "acpi [options]",
 ["-b battery", "-t thermal", "-a adapter", "-V voltages"],
 ["acpi -b", "acpi -t"],
 "quick battery check without opening a settings app"),
("ip", "Network", "show and manage network interfaces, routes and neighbors", "ip [object] command",
 ["a / addr addresses", "r / route routes", "l / link interfaces", "n / neigh ARP table", "-br -color brief pretty output"],
 ["ip -br a", "ip route", "ip neigh", "sudo ip link set eth0 up"],
 "the modern replacement for ifconfig/route/arp"),
("ss", "Network", "inspect sockets and listening ports", "ss [options]",
 ["-t TCP, -u UDP, -l listening, -n numeric, -p process, -a all", "state filters like 'state established'"],
 ["ss -tlnp", "ss -tunap | head -30", "ss -tp state established"],
 "ss -tlnp is the daily driver: what is listening, on which port, by which process"),
("netstat", "Network", "older socket and route statistics tool", "netstat [options]",
 ["-tlnp same meaning as with ss", "-r routing table", "-i interface stats", "-s summary counters"],
 ["netstat -tlnp", "netstat -rn"],
 "often not installed anymore; ss is the replacement"),
("ping", "Network", "test reachability with ICMP echo", "ping [options] host",
 ["-c N stop after N packets", "-i N interval", "-W N timeout per reply", "-s N payload size", "-4/-6 force family"],
 ["ping -c4 1.1.1.1", "ping -c4 google.com", "ping -s 1400 -M do host"],
 "if ping fails but the site loads, ICMP may just be filtered"),
("traceroute", "Network", "show the path packets take to a host", "traceroute [options] host",
 ["-n no DNS lookups", "-T TCP probes", "-I ICMP probes", "-m N max hops"],
 ["traceroute -n 1.1.1.1", "sudo traceroute -T -p 443 example.com"],
 "where the path stops is usually where the problem lives"),
("mtr", "Network", "combine ping and traceroute into a live view", "mtr [options] host",
 ["-r report mode", "-c N report after N cycles", "-n numeric", "-T TCP", "--report-wide"],
 ["mtr -rwc100 1.1.1.1", "mtr -n example.com"],
 "the best single tool for 'the network is slow sometimes'"),
("dig", "Network", "query DNS servers directly", "dig [options] name [type] [@server]",
 ["+short answers only", "ANY/A/AAAA/MX/TXT record types", "@1.1.1.1 ask a specific server", "+trace delegation path"],
 ["dig +short example.com", "dig MX gmail.com @8.8.8.8", "dig +trace example.com"],
 "dig +short is the scriptable form; the full output has the TTL and section flags"),
("nslookup", "Network", "older DNS query tool", "nslookup [options] name [server]",
 ["interactive mode when run bare", "set type=mx inside the shell"],
 ["nslookup example.com", "nslookup -type=mx gmail.com 1.1.1.1"],
 "dig gives more detail; nslookup is fine for a quick check"),
("host", "Network", "simple DNS lookup", "host [options] name [server]",
 ["-t TYPE record type", "-a all records"],
 ["host example.com", "host -t mx example.com"],
 "the shortest possible DNS answer"),
("whois", "Network", "look up domain registration information", "whois [options] domain",
 ["-h server query a specific whois server"],
 ["whois example.com | head -40"],
 "registrar, dates and nameservers live here"),
("curl", "Network", "transfer data to and from URLs", "curl [options] URL",
 ["-s silent", "-S show errors in silent mode", "-o FILE save to file", "-O save with remote name", "-L follow redirects", "-I headers only", "-X METHOD", "-d data (POST)", "-H header", "-k insecure (skip TLS check)", "--max-time N timeout"],
 ["curl -sS https://api.github.com/repos/rm-universe-os/universe-ai | jq .", "curl -LO https://example.com/file.zip", "curl -X POST -H 'Content-Type: application/json' -d '{\"a\":1}' https://api.example.com"],
 "add -f to fail on HTTP errors in scripts (curl -fsSL)"),
("wget", "Network", "download files from the web", "wget [options] URL",
 ["-c resume a partial download", "-O FILE output name", "-q quiet", "-r recursive mirror", "--limit-rate=500k", "--spider check existence"],
 ["wget -c https://example.com/big.iso", "wget -q --spider https://example.com"],
 "the classic choice for large downloads because of -c resume"),
("ssh", "Network", "connect to a remote machine securely", "ssh [options] [user@]host [command]",
 ["-p PORT non-standard port", "-i KEY identity file", "-L local port forward", "-R remote forward", "-J jump host", "-N no command (tunnel only)", "-v verbose debugging"],
 ["ssh alice@server.example.com", "ssh -i ~/.ssh/id_ed25519 -p 2222 host", "ssh -L 8080:localhost:80 user@host", "ssh -J jump host"],
 "ssh -v prints the whole handshake when a connection is refused for no obvious reason"),
("scp", "Network", "copy files over ssh", "scp [options] source destination",
 ["-r recursive", "-P PORT (capital!)", "-i identity file", "-C compression"],
 ["scp file.txt user@host:/tmp/", "scp -r user@host:~/logs ./logs"],
 "for anything bigger than a few files prefer rsync over ssh"),
("sftp", "Network", "interactive file transfer over ssh", "sftp [options] [user@]host",
 ["interactive commands: ls, cd, get, put, mkdir, bye"],
 ["sftp user@host", "echo 'get /var/log/syslog' | sftp user@host"],
 "handy when you need to browse interactively"),
("rsync", "Network", "fast, resumable file synchronization", "rsync [options] source destination",
 ["-a archive mode (-rlptgoD)", "-v verbose", "-h human sizes", "-z compress over the wire", "-P progress + partial resume", "--delete remove extraneous files on the target", "--exclude=pattern", "-n dry run (do this first!)"],
 ["rsync -avhP src/ user@host:/srv/app/", "rsync -avhn --delete src/ dst/", "rsync -a --exclude node_modules project/ backup/"],
 "trailing slash on the source is meaningful: src/ copies contents, src copies the directory"),
("nc", "Network", "netcat: read and write raw network connections", "nc [options] host port",
 ["-l listen mode", "-v verbose", "-z scan mode (no data)", "-u UDP", "-w N timeout"],
 ["nc -vz host 22 80 443", "nc -l 9000", "tar cf - dir | nc host 9000"],
 "the simplest port check and ad-hoc data pipe"),
("telnet", "Network", "old remote terminal and raw TCP client", "telnet host [port]",
 ["still useful for manually testing text protocols like SMTP or HTTP"],
 ["telnet host 25", "telnet 127.0.0.1 8080"],
 "never for real remote shells - ssh replaced it decades ago"),
("iptables", "Network", "legacy Linux firewall rules", "iptables [options] chain rule",
 ["-L list rules", "-S list as commands", "-A append", "-I insert", "-D delete", "-P default policy", "-F flush all"],
 ["sudo iptables -L -n -v", "sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT"],
 "rules are not persistent across reboots by themselves; nftables/ufw manage that"),
("nft", "Network", "nftables firewall front-end", "nft [command]",
 ["list ruleset", "add rule", "delete rule", "-a show handles"],
 ["sudo nft list ruleset", "sudo nft list tables"],
 "the modern successor to iptables on new kernels"),
("ufw", "Network", "simple front-end for firewall management", "ufw [command]",
 ["enable / disable", "allow PORT", "deny PORT", "status verbose", "delete RULE"],
 ["sudo ufw status verbose", "sudo ufw allow 22/tcp", "sudo ufw enable"],
 "Universe OS ships with UFW enabled (deny incoming by default)"),
("nmcli", "Network", "NetworkManager command line control", "nmcli [object] command",
 ["device status", "connection show", "dev wifi list", "dev wifi connect SSID password PASS", "-t -f for scriptable output"],
 ["nmcli device status", "nmcli dev wifi list", "nmcli con show --active"],
 "the scripting-friendly face of the desktop network applet"),
("nmtui", "Network", "text user interface for NetworkManager", "nmtui [edit|connect|hostname]",
 ["arrow-key driven menus"],
 ["nmtui", "nmtui connect"],
 "the friendly fallback when the desktop is not running"),
("tcpdump", "Network", "capture and inspect network packets", "tcpdump [options] [expression]",
 ["-i IFACE interface (any for all)", "-n no DNS", "-nn no DNS and no port names", "-c N packet count", "-w FILE write pcap", "-r FILE read pcap", "port N / host H / net N filters"],
 ["sudo tcpdump -i any -nn port 53", "sudo tcpdump -i eth0 -c 100 -w cap.pcap", "sudo tcpdump -r cap.pcap -nn"],
 "start narrow (one port, one host); -w then read in wireshark for deep analysis"),
("ethtool", "Network", "inspect and tune network interface hardware", "ethtool [options] interface",
 ["bare command shows link speed and duplex", "-S statistics", "-i driver info", "-s set speed/duplex"],
 ["ethtool eth0", "ethtool -S eth0 | head -30", "ethtool -i eth0"],
 "link speed 100Mb on a gigabit port is a cable problem more often than a config one"),
("arp", "Network", "show and manage the ARP cache", "arp [options]",
 ["-n numeric", "-a all entries", "-d delete an entry"],
 ["arp -an", "ip neigh show"],
 "ip neigh is the modern equivalent"),
("route", "Network", "show and edit the routing table (legacy)", "route [options]",
 ["-n numeric", "add/del routes"],
 ["route -n", "ip route show"],
 "ip route replaced it"),
("apt", "Packages", "Debian/Ubuntu package manager", "apt [command]",
 ["update refresh package lists", "upgrade upgrade installed packages", "install NAME...", "remove NAME...", "purge NAME... (also config)", "search TERM", "show NAME details", "autoremove unused dependencies", "list --installed", "-y assume yes"],
 ["sudo apt update && sudo apt upgrade -y", "apt search ripgrep", "apt show nginx", "sudo apt autoremove"],
 "update only refreshes lists - it never installs anything by itself"),
("apt-get", "Packages", "the script-stable apt variant", "apt-get [command]",
 ["same commands as apt", "-f fix broken dependencies", "dist-upgrade full upgrade"],
 ["sudo apt-get update && sudo apt-get install -y htop"],
 "scripts historically prefer apt-get because its interface never changes"),
("dpkg", "Packages", "low-level Debian package tool", "dpkg [options]",
 ["-i FILE install a .deb", "-l list installed (with pattern)", "-L PKG files a package owns", "-S FILE which package owns a file", "-r PKG remove", "--configure -a finish interrupted setups"],
 ["dpkg -l | grep nginx", "dpkg -S /usr/bin/ls", "sudo dpkg -i local.deb && sudo apt-get -f install"],
 "when dpkg gets stuck half-configured: sudo dpkg --configure -a"),
("snap", "Packages", "Snap package manager", "snap [command]",
 ["list", "install NAME", "remove NAME", "refresh update all", "info NAME"],
 ["snap list", "sudo snap install code --classic"],
 "snaps auto-update; check channels with snap info"),
("flatpak", "Packages", "Flatpak application manager", "flatpak [command]",
 ["install flathub ID", "run ID", "list", "update", "uninstall", "remote-add"],
 ["flatpak list --app", "flatpak install flathub com.spotify.Client", "flatpak update -y"],
 "permissions live in flatpak permissions (Flatseal-style hardening)"),
("pip", "Packages", "Python package installer", "pip [command]",
 ["install NAME", "uninstall NAME", "--user install for the current user", "-r requirements.txt", "list --outdated"],
 ["pip install --user requests", "pip install -r requirements.txt", "pip list --outdated"],
 "inside a venv, never sudo pip on modern distros"),
("pipx", "Packages", "install Python CLI apps in isolated environments", "pipx [command]",
 ["install NAME", "upgrade NAME", "list", "run NAME"],
 ["pipx install httpie", "pipx list"],
 "the right way to install python CLI tools globally"),
("npm", "Packages", "Node.js package manager", "npm [command]",
 ["install NAME [--save-dev]", "ci clean install from lockfile", "run SCRIPT", "outdated", "audit"],
 ["npm ci", "npm run build", "npm outdated"],
 "npm ci in CI and deployments; npm install while developing"),
("cargo", "Packages", "Rust package manager and build tool", "cargo [command]",
 ["build [--release]", "run", "test", "add DEP", "clippy lints", "fmt"],
 ["cargo build --release", "cargo test", "cargo add serde --features derive"],
 "cargo clippy before cargo commit, as the saying goes"),
("bash", "Shell", "the Bourne-Again SHell", "bash [options] [script]",
 ["-c run a command string", "-x trace execution (debugging)", "-e exit on error", "-u error on unset variables", "-o pipefail fail a pipeline on any failure", "-n syntax check without running"],
 ["bash -n script.sh", "bash -x script.sh", "bash -euo pipefail script.sh"],
 "the debugging trio: -n to check syntax, -x to watch what runs"),
("zsh", "Shell", "the Z shell with interactive superpowers", "zsh [options]",
 ["-c command string", "plugin ecosystems like oh-my-zsh"],
 ["zsh -c 'echo $ZSH_VERSION'"],
 "bash compatibility is close but not identical - scripts should declare their shell"),
("sh", "Shell", "the POSIX shell", "sh [options] [script]",
 ["-c command string", "-n syntax check", "-x trace"],
 ["sh -n install.sh", "sh -c 'echo portable'"],
 "use sh for maximum portability; avoid bash-only syntax there"),
("env", "Shell", "run a command with a modified environment", "env [options] [name=value]... [command]",
 ["bare command prints all variables", "-i start from an empty environment", "-u NAME unset a variable"],
 ["env | sort | less", "env -i PATH=/usr/bin bash --norc", "env VAR=value ./app"],
 "env -i is the clean-room way to reproduce environment bugs"),
("export", "Shell", "mark variables for child processes", "export NAME[=value]",
 ["bare export lists exported variables", "-n remove the export flag", "-p print in reusable form"],
 ["export EDITOR=vim", "export PATH=\"$HOME/.local/bin:$PATH\""],
 "only exported variables cross into child processes"),
("alias", "Shell", "create shortcuts for commands", "alias name='command'",
 ["bare alias lists them", "put them in ~/.bashrc or ~/.zshrc to persist"],
 ["alias ll='ls -lah'", "alias gs='git status -sb'"],
 "aliases do not expand inside scripts by default - that is a feature"),
("source", "Shell", "run a script in the current shell", "source FILE  (or: . FILE)",
 ["changes made by the script (cd, variables) persist"],
 ["source ~/.bashrc", ". ./env.sh"],
 "the difference from ./script.sh is the same-process execution"),
("history", "Shell", "show or manage the command history", "history [options]",
 ["-c clear the list", "-d N delete an entry", "!N re-run entry N", "!! re-run the last command", "Ctrl+R search interactively"],
 ["history | tail -30", "history -c", "Ctrl+R nginx"],
 "Ctrl+R is the fastest way to find that long command from yesterday"),
("echo", "Shell", "print text", "echo [options] [string...]",
 ["-n no trailing newline", "-e enable \\n \\t escapes (bash)", "quote variables: \"$var\""],
 ["echo \"hello $USER\"", "echo -e 'a\\tb'"],
 "printf is the portable choice when formatting matters"),
("printf", "Shell", "formatted printing", "printf FORMAT [args...]",
 ["%s string, %d integer, %f float, %x hex", "\\n newline", "unlike echo, behavior is identical everywhere"],
 ["printf '%s\\n' \"$PATH\"", "printf '%05d\\n' 42"],
 "the right tool for aligned output in scripts"),
("read", "Shell", "read a line from standard input into variables", "read [options] [name...]",
 ["-p PROMPT prompt text", "-r raw: do not interpret backslashes", "-s silent (passwords)", "-t N timeout", "-a ARRAY read into an array"],
 ["read -rp 'Name: ' name", "while read -r line; do echo \"$line\"; done < file", "read -rs -p 'Password: ' pw"],
 "always use -r in loops unless you want backslash processing"),
("test", "Shell", "evaluate conditional expressions", "test EXPR  (or: [ EXPR ])",
 ["-f file exists and is a file", "-d directory exists", "-z string is empty", "-n non-empty", "-eq/-ne numeric compare", "= / != string compare", "&& and || combine"],
 ["[ -f config.ini ] && echo found", "if [ \"$x\" -gt 10 ]; then echo big; fi"],
 "quote variables inside [ ] - unquoted empties are the classic syntax error"),
("expr", "Shell", "evaluate expressions (older arithmetic and string ops)", "expr EXPRESSION",
 ["integer arithmetic: expr 2 + 3", "string ops: length, substr, index"],
 ["expr 2 + 3", "expr length \"hello\""],
 "modern scripts use $(( )) for arithmetic and ${#var} for length"),
("seq", "Shell", "print a sequence of numbers", "seq [first] [step] last",
 ["-w equal width (zero padded)", "-s STRING custom separator", "-f FORMAT printf-style"],
 ["seq 1 10", "seq -w 1 100", "for i in $(seq 2 2 20); do echo $i; done"],
 "brace expansion {1..10} is the bash-native alternative"),
("yes", "Shell", "print a string repeatedly", "yes [string]",
 ["default string is 'y'; Ctrl+C stops it"],
 ["yes | sudo apt-get install -y pkg", "yes n | rm -i *.tmp"],
 "a blunt instrument for interactive prompts - read what you are auto-answering"),
("sleep", "Shell", "pause for a given time", "sleep DURATION",
 ["s/m/h/d suffixes: 0.5, 10s, 2m", "fractional seconds supported"],
 ["sleep 5", "sleep 0.2 && curl -s localhost:8080/health"],
 "the standard retry-loop companion"),
("date", "Shell", "print or set the date and time", "date [options] [+FORMAT]",
 ["+%Y-%m-%d formats", "-d 'yesterday' relative dates", "-u UTC", "-s set time (root)", "+%s epoch seconds"],
 ["date +'%Y-%m-%d %H:%M:%S'", "date -d '2 days ago' +%F", "date +%s"],
 "use date -d for date maths instead of hand-rolling calendar logic"),
("cal", "Shell", "display a calendar", "cal [options] [month] [year]",
 ["-3 show previous, current and next month", "-y whole year"],
 ["cal", "cal -3"],
 "tiny, harmless, occasionally exactly what you need"),
("bc", "Shell", "arbitrary-precision calculator language", "bc [options]",
 ["-l load the math library (floats, functions)", "scale=N decimal places", "echo 'expr' | bc for one-liners"],
 ["echo 'scale=2; 10/3' | bc -l", "echo '2^64' | bc"],
 "the shell's integer-only arithmetic stops at $(( )) - bc does not"),
("which", "Shell", "locate the executable a command name resolves to", "which [options] name...",
 ["-a all matches in PATH", "-p skip aliases and functions"],
 ["which python3", "which -a python3"],
 "shell functions and aliases need type instead"),
("type", "Shell", "explain how a name would be interpreted", "type [options] name...",
 ["-a all interpretations", "-t one-word type", "-p path only if it is a file"],
 ["type ll", "type -a python3"],
 "the truth-teller when 'which' disagrees with what actually runs"),
("whereis", "Shell", "locate binary, source and man page for a name", "whereis [options] name",
 ["-b binaries only", "-m man pages only"],
 ["whereis nginx", "whereis -b python3"],
 "finds more than which because it searches standard locations, not only PATH"),
("man", "Shell", "read the manual page for a command", "man [section] name",
 ["sections: 1 commands, 5 files/formats, 8 admin", "-k search descriptions (like apropos)", "-f one-line summaries"],
 ["man 5 fstab", "man -k 'disk usage'", "man tar | less"],
 "inside man: / to search, n for next match, q to quit"),
("apropos", "Shell", "search manual page descriptions", "apropos keyword",
 ["same as man -k", "a keyword index, not full-text"],
 ["apropos 'copy files'", "apropos network | head -20"],
 "the 'I forgot the command name' tool"),
("git", "Development", "distributed version control", "git [command]",
 ["status working tree state", "add / commit -m staging and recording", "log --oneline history", "diff changes", "branch / checkout / switch branches", "pull / push sync with remotes", "clone copy a repository", "stash shelve work", "rebase replay commits"],
 ["git status -sb", "git log --oneline --graph -20", "git diff --stat", "git stash && git switch main && git stash pop"],
 "commit small and often; git diff before git add saves embarrassment"),
("make", "Development", "build automation from Makefiles", "make [options] [target]",
 ["-j N parallel jobs", "-n dry run: print commands only", "-B force rebuild", "-C DIR run in a directory"],
 ["make -j$(nproc)", "make -n install", "make -C build/"],
 "make -n shows exactly what would run - the safe way to inspect a strange Makefile"),
("gcc", "Development", "the GNU C compiler (and driver for other languages)", "gcc [options] file...",
 ["-o OUT output name", "-Wall -Wextra warnings", "-g debug info", "-O2 optimisation", "-c compile without linking"],
 ["gcc -Wall -g -o app main.c", "gcc -c module.c"],
 "read warnings top-down; the first one often causes the rest"),
("vim", "Development", "the ubiquitous modal text editor", "vim [options] [file]",
 ["i insert, Esc normal mode", ":w save, :q quit, :wq both", "/ search", "dd delete line, yy copy line, p paste", ":%s/a/b/g replace everywhere"],
 ["vim /etc/hosts", "vim +42 file.txt"],
 "vimtutor is the 30-minute course everybody should do once"),
("nano", "Development", "simple terminal text editor", "nano [options] [file]",
 ["Ctrl+O save, Ctrl+X exit", "Ctrl+W search", "Ctrl+K cut line, Ctrl+U paste"],
 ["nano /etc/fstab", "sudo nano /etc/apt/sources.list"],
 "the editor that tells you its own shortcuts on screen"),
("jq", "Development", "command-line JSON processor", "jq [options] filter [file]",
 ["'.' pretty-print", "'.key' extract", "'.items[]' iterate", "-r raw strings", "-e exit code from value"],
 ["curl -s api | jq .", "jq -r '.name' package.json", "jq '.[] | select(.id==3)' data.json"],
 "the universal tool for API responses and config files"),
("openssl", "Development", "cryptography toolkit", "openssl command [options]",
 ["s_client -connect host:443 inspect TLS", "x509 -in cert.pem -text read a certificate", "req -new -x509 generate a self-signed cert", "dgst -sha256 hash", "rand -hex N random"],
 ["openssl s_client -connect example.com:443 -servername example.com </dev/null", "openssl x509 -in cert.pem -noout -dates"],
 "the certificate debugging sequence: s_client, then x509 -text, then check dates"),
("ssh-keygen", "Development", "create and manage SSH keys", "ssh-keygen [options]",
 ["-t ed25519 key type (modern default)", "-t rsa -b 4096 legacy compatibility", "-C comment", "-f output file", "-y print the public key"],
 ["ssh-keygen -t ed25519 -C me@host", "ssh-keygen -y -f ~/.ssh/id_ed25519"],
 "the private key never leaves the machine; ssh-copy-id installs the public one"),
("gpg", "Development", "GNU Privacy Guard: signing and encryption", "gpg [options]",
 ["--gen-key generate a keypair", "--list-keys", "-a armor output", "-d decrypt", "-e encrypt to a recipient", "--verify / --detach-sign"],
 ["gpg --list-keys", "gpg -a --detach-sign file.tar", "gpg --verify file.tar.asc"],
 "the trust model question ('who actually owns this key') is the hard part, not the commands"),
("base64", "Development", "encode or decode base64", "base64 [options] [file]",
 ["-d decode", "-w 0 no line wrapping"],
 ["echo -n hello | base64", "base64 -d blob.txt > file.bin", "openssl rand 32 | base64 -w0"],
 "base64 is encoding, not encryption - never for secrets"),
("md5sum", "Development", "compute or check MD5 checksums", "md5sum [options] [file...]",
 ["-c verify against a checksum file", "--tag BSD-style output"],
 ["md5sum image.iso", "md5sum -c md5sum.txt"],
 "fine for accidental corruption, broken for security; sha256 for that"),
("sha256sum", "Development", "compute or check SHA-256 checksums", "sha256sum [options] [file...]",
 ["-c verify against a checksum file", "--quiet only failures when checking"],
 ["sha256sum model.tar.zst", "sha256sum -c model.tar.zst.sha256"],
 "the standard integrity check for downloads and releases"),
("xxd", "Development", "hex dump (and reverse) a file", "xxd [options] [file]",
 ["-l N limit bytes", "-s OFFSET start offset", "-r reverse: hex back to binary", "-p plain hex"],
 ["xxd firmware.bin | head", "xxd -l 64 -s 0x100 disk.img", "xxd -r -p hex.txt > out.bin"],
 "the bridge between text tools and binary data"),
("hexdump", "Development", "display file contents in hex", "hexdump [options] [file]",
 ["-C canonical hex+ASCII display", "-n N bytes", "-s OFFSET"],
 ["hexdump -C header.bin | head -5"],
 "xxd -l or hexdump -C, either is fine; -C is the readable one"),
("od", "Development", "octal/hex dump of binary data", "od [options] [file]",
 ["-A x hex offsets", "-t x1z hex bytes plus ASCII", "-j skip, -N count"],
 ["od -A x -t x1z firmware.bin | head"],
 "the POSIX standard tool when hexdump is not installed"),
("objdump", "Development", "inspect object files and executables", "objdump [options] file",
 ["-d disassemble", "-h section headers", "-t symbols", "-s dump sections", "-x all headers"],
 ["objdump -h /usr/bin/ls", "objdump -d ./app | less"],
 "the first look at any compiled binary's structure"),
("nm", "Development", "list symbols in object files", "nm [options] file",
 ["-C demangle C++ names", "-D dynamic symbols", "-u undefined only"],
 ["nm -C libfoo.a | head", "nm -D /usr/bin/python3 | grep Py_"],
 "undefined symbols tell you which library is missing at link time"),
("readelf", "Development", "inspect ELF executables in detail", "readelf [options] file",
 ["-h header", "-d dynamic section", "-s symbols", "-n notes"],
 ["readelf -h /usr/bin/ls", "readelf -d ./app | grep NEEDED"],
 "NEEDED entries answer 'which libraries does this binary want'"),
("gdb", "Development", "the GNU debugger", "gdb [options] [program [core|pid]]",
 ["run [args]", "bt backtrace", "break FUNC / line", "next / step", "print EXPR", "info locals", "-p PID attach"],
 ["gdb ./crashyapp", "gdb -p 1234", "gdb ./app core"],
 "bt first, always - the backtrace tells you where to look"),
("valgrind", "Development", "memory error and leak detector", "valgrind [options] program",
 ["--leak-check=full", "--track-origins=yes", "-s summary", "--tool=helgrind thread races"],
 ["valgrind --leak-check=full ./app", "valgrind --tool=helgrind ./threaded-app"],
 "slow but merciless - run it on the smallest failing case"),
("perf", "Development", "Linux profiling toolkit", "perf [command]",
 ["top live CPU hotspots", "record / report sampling profiles", "stat hardware counters", "trace syscalls"],
 ["sudo perf top", "sudo perf stat ./benchmark", "sudo perf record -g ./app && sudo perf report"],
 "when 'why is this slow' needs real data instead of guesses"),
("docker", "Development", "container management", "docker [command]",
 ["ps containers", "images", "run -it IMAGE", "exec -it ID sh", "logs -f ID", "build -t NAME .", "compose up -d"],
 ["docker ps -a", "docker logs -f web", "docker exec -it db psql -U postgres"],
 "docker exec is the 'get a shell inside' move; docker logs the 'why did it die' move"),
("podman", "Development", "daemonless container engine (docker-compatible CLI)", "podman [command]",
 ["same commands as docker", "rootless by default", "generate systemd units"],
 ["podman ps", "podman run --rm -it alpine sh"],
 "rootless containers are the point; sudo docker is a smell on desktop Linux"),
]
