LINUX = [
("What does ls do?", "`ls` lists directory contents. Flags: -l long, -a hidden, -h human sizes, -t by time, -R recursive. Example: ls -lah /var/log"),
("How do I copy files?", "cp source dest. -r recursive, -i interactive, -p preserve attrs, -u newer only. Example: cp -r ~/project /tmp/backup"),
("How do I move or rename files?", "mv old new. -i ask before overwrite, -n never, -t DIR target dir. Example: mv file.txt ~/docs/report.txt"),
("What is rm and how to use it safely?", "rm deletes. -r recursive, -f force. Dangerous with root — check path twice. Universe AI always asks approval before rm."),
("How does grep work?", "grep PATTERN file. -i ignore case, -r recursive, -n line numbers, -v invert, -E extended regex. Example: grep -rn error /var/log/ | head"),
("How do I find files?", "find PATH -name pattern -type f. Tests: -mtime -7, -size +100M. Actions: -delete, .-exec cmd {} ;. Example: find /tmp -name *.tmp -mtime +7 -delete"),
("What does chmod do?", "chmod changes permissions: r=4 w=2 x=1 for user/group/other. chmod 755 script.sh = rwxr-xr-x. Symbolic: chmod +x file."),
("What is chown?", "chown user:group file — changes ownership, needs root for others' files. Example: sudo chown -R www-data:www-data /var/www"),
("How do I see processes?", "ps aux snapshot, top/htop live, pgrep -f name. Universe OS ships universe-monitor GUI."),
("How do I kill a process?", "kill PID (TERM), kill -9 PID (KILL, last resort), pkill -f pattern, killall name."),
("How does systemctl work?", "systemctl status/start/stop/restart/enable/disable UNIT. list-units --type=service. Example: sudo systemctl enable --now ufw"),
("How do I read logs?", "journalctl -u UNIT, -f follow, -b this boot, -p err. tail -f /var/log/syslog for files."),
("How do I check disk usage?", "df -h filesystems, du -sh DIR directory size, du -h --max-depth=1 | sort -h biggest dirs. GUI: universe-cleaner."),
("How do I check memory?", "free -h, top/htop per process, vmstat 1 live."),
("Network commands?", "ip a addresses, ip r routes, ss -tlnp ports, ping, dig, traceroute, nmcli wifi. GUI: universe-settings Network."),
("How do I archive files?", "tar -czf out.tar.gz dir (gzip), tar --zstd -cf out.tar.zst dir, extract -xf, list -tf. Universe OS ISO = zstd SquashFS."),
("How do permissions work?", "owner/group/other x rwx. ls -l shows. Root bypasses — Universe OS gates sudo via GUI."),
("What is sudo?", "run command as root. In Universe OS sudo = universe-privilege GUI gate with timed grants."),
("Pipes and redirection?", "| pipe, > overwrite, >> append, 2> errors, &> both, < input. Example: cat log | grep err | wc -l"),
("What is xargs?", "build commands from stdin: find . -name *.tmp | xargs rm. -I{} placeholder, -P 4 parallel."),
("How do I create a user?", "sudo useradd -m -s /bin/bash name && sudo passwd name. Add to sudo: usermod -aG sudo name."),
("How does apt work?", "apt update, install, remove, purge, upgrade, search, list --installed. Universe OS is Ubuntu-based."),
("What is a systemd unit?", "/etc/systemd/system/*.service: [Unit], [Service] ExecStart, [Install]. daemon-reload after edit."),
("Environment variables?", "export VAR=v, echo $VAR, printenv. Permanent in ~/.bashrc. PATH = command search path."),
("What is cron?", "crontab -e. m h dom mon dow cmd. 0 3 * * * = daily 3am. @reboot = at boot."),
("How do I use ssh?", "ssh user@host -p port -i key. scp file host:path. rsync -avz. Keys: ssh-keygen -t ed25519."),
("What is rsync?", "rsync -avz src/ dst/ syncs deltas. --delete mirror, -n dry-run first!"),
("How to check open ports?", "ss -tlnp (sudo for names). nmap for full scan (hacker mode has it)."),
("Symlink vs hard link?", "ln -s target name = symbolic. Hard link = same inode. Universe AI refuses symlink writes for safety."),
("Bash scripting basics?", "#!/bin/bash, X=5 no spaces, if [ $X -gt 3 ]; then fi, for f in *.txt; do done, chmod +x."),
("head/tail?", "head -n 20, tail -n 20, tail -f follow live, tail -n +5 from line 5."),
("What is awk for?", "columns: awk '{print $1}', -F: separator, $3 > 100 filters. Heavy jobs → python."),
("What is sed?", "sed s/old/new/g replace, -i in-place, -n 5p line 5. Universe AI asks approval for sed."),
("tar compressions?", "gzip -z, zstd --zstd, xz -J. Extract -xf. Universe OS ISO = zstd SquashFS."),
]
