SCENARIOS = [
("A systemd service will not start",
 "The service fails, restarts in a loop, or shows 'failed' after start.",
 ["the unit file has an error", "the service user or file permissions are wrong", "a dependency is missing or failed", "the port is already in use", "an environment variable the service expects is not set"],
 [("Check the service state and the exact error line", "systemctl status myapp.service"),
  ("Read the service's own log, newest first", "journalctl -u myapp.service -n 100 --no-pager"),
  ("See which other units failed around the same time", "systemctl --failed"),
  ("Validate the unit file for syntax mistakes", "systemd-analyze verify /etc/systemd/system/myapp.service"),
  ("After editing the unit file, reload and retry", "sudo systemctl daemon-reload && sudo systemctl restart myapp.service"),
  ("If the port is the problem, find who owns it", "ss -tlnp | grep :8080")],
 "Fix the root cause named in the log (permissions, config, port), then daemon-reload and restart. If a dependency keeps it down, check that unit too."),
("Disk is full but nothing obvious is large",
 "df shows 100% usage, yet du does not find the space.",
 ["deleted files still held open by a process", "a mount is shadowing files (files under a mount point)", "filesystem reserved blocks for root", "inode exhaustion (df -i), not block exhaustion"],
 [("Confirm which filesystem is actually full", "df -hT"),
  ("Check inode usage too - full inodes break things with free space", "df -i"),
  ("Find deleted-but-open files; the (deleted) marker is the giveaway", "sudo lsof -nP | grep '(deleted)'"),
  ("Restart the process holding the big deleted file, or truncate it", "sudo systemctl restart the-service"),
  ("Compare df with du on the same mount to spot shadowed files", "du -xsh /var/* | sort -h | tail")],
 "Restarting (or truncating) the process that holds deleted files returns the space. If df and du disagree on the same mount, look for files hidden under a mount point."),
("High CPU usage with no obvious culprit",
 "Fans spin up, the system feels slow, load average climbs.",
 ["a runaway process", "a stuck kernel thread or IO wait", "thermal throttling", "cron or backup jobs overlapping", "a crypto miner or other unwanted process"],
 [("Get the top CPU consumers, worst first", "ps aux --sort=-%cpu | head -15"),
  ("Check whether the load is CPU or IO wait", "vmstat 1 5"),
  ("Look at per-core usage to spot a single-threaded hog", "mpstat -P ALL 1 3"),
  ("Check temperatures - throttling looks like slowness", "sensors"),
  ("If IO-bound, find the busiest disk", "iostat -xz 1 5"),
  ("Identify the exact threads of a process if needed", "top -H -p PID")],
 "Handle the specific process: renice it, fix its bug, or kill it. If it is IO wait, the problem is the disk, not the CPU."),
("No internet connection",
 "Websites do not load; ping may or may not work.",
 ["cable or Wi-Fi association problem", "no IP address from DHCP", "bad DNS", "wrong default route", "firewall blocking", "the upstream router is down"],
 [("Check the interface state and addresses", "ip -br a"),
  ("If the interface is down, bring it up", "sudo ip link set eth0 up"),
  ("Check the default route exists", "ip route"),
  ("Ping the gateway, then a public IP (1.1.1.1) - this separates routing from DNS", "ping -c3 $(ip route | awk '/default/{print $3; exit}') && ping -c3 1.1.1.1"),
  ("If IPs work but names do not, it is DNS", "resolvectl status && dig +short example.com"),
  ("For Wi-Fi specifically, rescan and reconnect", "nmcli dev wifi list && nmcli dev wifi connect SSID password PASS"),
  ("Check the firewall is not eating the traffic", "sudo ufw status verbose")],
 "Fix at the layer that failed: association, DHCP, route, DNS or firewall. ping by IP working while names fail always means DNS."),
("'Permission denied' when accessing a file",
 "Reading, writing or executing a file or directory fails with Permission denied.",
 ["missing execute bit on a parent directory", "wrong owner or group", "an ACL is restricting access", "SELinux/AppArmor denial", "the file is immutable", "noexec mount option"],
 [("Look at the permissions of the file and every parent directory", "namei -l /path/to/file"),
  ("Check your identity and groups - maybe the group changed", "id"),
  ("Check for ACLs (the + sign in ls -l)", "getfacl /path/to/file"),
  ("Check for immutable or append-only attributes", "lsattr /path/to/file"),
  ("If it looks correct but still fails, check the audit log", "sudo journalctl -xe | tail -40"),
  ("Fix the owner or mode as needed", "sudo chown user:group /path && chmod 644 /path/file")],
 "Grant the access that is actually missing: chmod on the file or chmod +x on the parent directories, chown to the right owner, or remove the ACL/attribute that blocks you."),
("Application crashes at startup",
 "The app exits immediately, shows a flash, or dies without a window.",
 ["a missing shared library", "bad configuration file", "wrong permissions", "a stale lock file", "an incompatible driver or display backend"],
 [("Run it from a terminal to see the real error text", "./app"),
  ("Ask the loader which libraries are missing", "ldd ./app | grep 'not found'"),
  ("Trace which file it fails to open", "strace -f -e trace=openat ./app 2>&1 | grep -E 'ENOENT|EACCES' | tail -20"),
  ("Check its own logs and the journal", "journalctl --user -n 50 --no-pager"),
  ("If it is a GUI app, check the session type and backend", "echo $XDG_SESSION_TYPE $WAYLAND_DISPLAY $DISPLAY"),
  ("Try the other display backend", "GDK_BACKEND=x11 ./app")],
 "Install the missing library, fix the config or permission the trace named, or switch the display backend. The first ENOENT or EACCES in the trace is almost always the answer."),
("Boot hangs or drops to a black screen",
 "The machine powers on but never reaches the login screen.",
 ["a failing systemd unit in the boot chain", "a broken graphics driver", "a corrupted filesystem", "bad kernel parameters", "disk failure"],
 [("At the GRUB menu, boot with 'quiet splash' removed to see messages", "edit the boot entry: remove quiet splash, add nomodeset (Intel/AMD) or blacklist vendor drivers"),
  ("From a TTY or recovery shell, list failed units", "systemctl --failed"),
  ("Read the previous boot's log", "journalctl -b -1 -p err --no-pager"),
  ("Analyze what actually slowed or broke the boot", "systemd-analyze critical-chain"),
  ("Check the filesystem if errors are suspected", "sudo fsck -f /dev/nvme0n1p2"),
  ("Check disk health", "sudo smartctl -a /dev/nvme0n1")],
 "Fix the unit that failed, the driver that panicked, or the filesystem that is corrupt. Safe Mode (vendor driver blacklist) is the standard escape hatch for GPU-related black screens."),
("Slow boot",
 "The system takes minutes to reach the desktop.",
 ["a blocking service waiting on network or a timeout", "a slow mount (network share, bad fstab entry)", "a huge initramfs rebuild", "disk at 100% during boot", "too many autostart applications"],
 [("See the total boot time and the slowest units", "systemd-analyze blame | head -20"),
  ("See the critical chain - what actually gated the boot", "systemd-analyze critical-chain"),
  ("Check for mount timeouts in the journal", "journalctl -b | grep -iE 'timed out|timeout|dependency failed'"),
  ("List autostart programs", "ls ~/.config/autostart /etc/xdg/autostart"),
  ("Check fstab for entries that may hang (network mounts)", "cat /etc/fstab")],
 "Mask or fix the slow unit, add noauto/x-systemd.device-timeout to network mounts, and trim autostart apps. critical-chain shows the chain that actually matters."),
("Wi-Fi keeps dropping",
 "The connection works, then disappears or degrades.",
 ["power saving on the Wi-Fi card", "weak signal or channel congestion", "driver problems", "NetworkManager retry loops", "wrong regulatory domain"],
 [("Check the signal quality and current link", "nmcli dev wifi list --rescan yes"),
  ("Look at recent disconnect reasons in the log", "journalctl -u NetworkManager -n 80 --no-pager"),
  ("Check whether power saving is on (common cause of drops)", "iw dev wlan0 get power_save"),
  ("Turn it off and test", "sudo iw dev wlan0 set power_save off"),
  ("Check the driver in use", "lspci -k | grep -A3 -i network")],
 "Disable power saving persistently (NetworkManager wifi.powersave=2), pick a less crowded channel, or update the driver. Persistent drops with power_save on are a classic."),
("Audio stopped working",
 "No sound, wrong device, or crackling audio.",
 ["the wrong default sink is selected", "PipeWire/PulseAudio service is down", "the device is muted at ALSA level", "an app holds the device exclusively", "missing firmware or codec"],
 [("List outputs and check which is default", "pactl list short sinks && pactl info | grep 'Default Sink'"),
  ("Check and unmute ALSA master controls", "alsamixer -c0"),
  ("Check the audio services", "systemctl --user status pipewire pipewire-pulse wireplumber --no-pager"),
  ("Restart the user audio stack", "systemctl --user restart pipewire pipewire-pulse wireplumber"),
  ("See if an app holds the device", "fuser -v /dev/snd/* 2>/dev/null"),
  ("Check firmware/kernel messages for the card", "dmesg | grep -iE 'snd|audio|firmware' | tail -20")],
 "Select the right sink, unmute at both ALSA and PipeWire level, or restart the user audio services. If the card is missing entirely, it is a firmware/driver problem."),
("Out of memory: the OOM killer strikes",
 "Apps get killed randomly, especially under load.",
 ["a memory leak", "too many browser tabs or VMs", "no or too small swap", "cgroup limits hit", "a runaway process"],
 [("Check current memory and swap", "free -h"),
  ("Confirm who got killed and why", "dmesg -T | grep -i 'killed process' | tail"),
  ("Find the biggest memory consumers", "ps aux --sort=-%mem | head -15"),
  ("Watch memory live to catch the growth", "watch -n2 'free -h'"),
  ("Check for a process slowly leaking", "ps -o pid,rss,etime,cmd -C firefox")],
 "Kill or fix the leaking process, add swap as a buffer, and set a systemd MemoryMax= limit on the offender so it dies instead of the whole desktop."),
("Cannot delete a file",
 "rm says Permission denied or Operation not permitted even as root.",
 ["immutable or append-only attribute set", "the directory (not the file) lacks write permission", "the file is a mount point", "an open handle from a container or process", "filesystem is read-only (errors detected)"],
 [("Check attributes", "lsattr /path/to/file"),
  ("Remove the immutable flag if present", "sudo chattr -i /path/to/file"),
  ("Check the directory permissions", "ls -ld $(dirname /path/to/file)"),
  ("Check whether the filesystem went read-only after errors", "mount | grep ' / '"),
  ("Check for open handles", "sudo lsof /path/to/file")],
 "Clear the attribute, fix the directory mode, or remount rw after fixing the underlying disk problem. A filesystem that remounts itself read-only means errors - check dmesg."),
("SSH connection refused or times out",
 "ssh exits with 'Connection refused' or hangs.",
 ["sshd is not running or not listening on that port", "firewall blocks the port", "wrong port or host", "host key changed (man-in-the-middle warning)", "DNS resolves to the wrong host"],
 [("Check the service on the server", "systemctl status ssh"),
  ("Check what it listens on", "ss -tlnp | grep ssh"),
  ("From the client, test the port reachability", "nc -vz host 22"),
  ("Check the client's verbose handshake", "ssh -vvv user@host 2>&1 | tail -30"),
  ("Check the server firewall", "sudo ufw status verbose"),
  ("If the host key changed after a rebuild, update known_hosts", "ssh-keygen -R host")],
 "'Connection refused' = nothing listening (start sshd / fix port). Timeout = firewall or routing. Host key warnings after a reinstall are expected - remove the old key."),
("Cron job does not run",
 "The scheduled job never fires, or fires with errors.",
 ["cron service is not running", "wrong crontab syntax or time fields", "the command needs a PATH or environment cron does not have", "output errors are silently mailed", "the script lacks the execute bit"],
 [("Check cron itself", "systemctl status cron"),
  ("List the user's jobs", "crontab -l"),
  ("Check the system log for cron executions", "journalctl -u cron -n 50 --no-pager"),
  ("Test the exact command as the same user", "run the command manually with env -i"),
  ("Use absolute paths for everything inside the job", "which python3 && crontab -l")],
 "Fix the schedule, use absolute paths, redirect output to a log file so you can see errors, and remember cron has a minimal environment."),
("Website returns 502 Bad Gateway (nginx + app server)",
 "Nginx serves static files but proxied routes fail.",
 ["the backend app is down or crashed", "wrong upstream port or socket", "backend is too slow and nginx times out", "permissions on a unix socket", "backend listening on the wrong interface"],
 [("Check the nginx error log for the exact upstream error", "tail -50 /var/log/nginx/error.log"),
  ("Check the backend service", "systemctl status myapp"),
  ("Check the backend is really listening", "ss -tlnp | grep -E '8080|9000'"),
  ("Test the backend directly, bypassing nginx", "curl -sv http://127.0.0.1:8080/health"),
  ("Check nginx config for the proxy target", "nginx -T | grep -A5 proxy_pass"),
  ("Reload nginx after config fixes", "sudo nginx -t && sudo systemctl reload nginx")],
 "Bring the backend up, point the proxy at the right port, or raise proxy timeouts. The nginx error log names the failing upstream and the reason."),
("The clock is wrong",
 "Times in logs are off; HTTPS or apt fails with certificate errors.",
 ["wrong timezone", "NTP not running or blocked", "hardware clock wrong", "dual-boot Windows setting the RTC to local time"],
 [("Check the current time settings", "timedatectl"),
  ("Enable NTP sync", "sudo timedatectl set-ntp true"),
  ("Force a one-shot sync", "sudo chronyc makestep (or: sudo systemctl restart systemd-timesyncd)"),
  ("Set the right timezone if needed", "sudo timedatectl set-timezone REGION/CITY"),
  ("Check the hardware clock mode if dual-booting", "timedatectl | grep RTC")],
 "Turn on NTP and pick the correct timezone. Certificate errors that appear suddenly are usually a clock that drifted by minutes or more."),
("USB drive is not detected",
 "Plugging in a USB stick or disk does nothing.",
 ["the port or cable is bad", "kernel refused the device", "filesystem unsupported (exFAT/NTFS without packages)", "the device needs a different mode (USB modeswitch)", "power draw too high for the port"],
 [("Watch the kernel as you plug it in", "dmesg -w  (plug the device, watch the lines)"),
  ("List USB devices to confirm it enumerated", "lsusb"),
  ("List block devices to see if a disk appeared", "lsblk -f"),
  ("Check for filesystem support messages", "dmesg -T | grep -iE 'exfat|ntfs|sdb' | tail"),
  ("Try another port and cable", "physical swap - no command for this one")],
 "If lsusb shows it but lsblk does not, it is a storage/mode problem. If it appears in lsblk, mount it (or install exfatprogs/ntfs-3g for the filesystem)."),
("Filesystem errors after a power loss",
 "The system boots read-only, or shows I/O errors and fsck messages.",
 ["unsynced writes at power loss", "failing disk", "loose cable on a desktop drive", "BTRFS needs a scrub after errors"],
 [("Check the kernel log for the exact errors", "dmesg -T | grep -iE 'error|I/O|ext4|btrfs' | tail -30"),
  ("Check the filesystem state", "sudo tune2fs -l /dev/sda2 | grep -i state"),
  ("Run a check from a live environment or unmounted system", "sudo fsck -f /dev/sda2"),
  ("For BTRFS, check the device stats and scrub", "sudo btrfs device stats / && sudo btrfs scrub start /"),
  ("Check the disk's SMART health", "sudo smartctl -H /dev/sda")],
 "Repair the filesystem once, then look for the real cause: SMART errors mean replace the disk; repeated corruption on a healthy disk means cables or power."),
("Pacman says the package is already installed but the binary is missing",
 "apt/dpkg reports a package as installed, yet the file is absent.",
 ["files were deleted manually", "a partial upgrade left the package half-configured", "the file is in a different package", "dpkg database and filesystem disagree"],
 [("Ask dpkg which package owns the path", "dpkg -S /usr/bin/missing-tool"),
  ("Reinstall the owning package", "sudo apt install --reinstall PACKAGE"),
  ("Fix any half-configured packages", "sudo dpkg --configure -a && sudo apt-get -f install"),
  ("Verify the package's file list", "dpkg -L PACKAGE | head -30")],
 "Reinstall the package; if apt refuses, fix the dpkg state first with --configure -a and -f install."),
("Keyboard or language layout is wrong",
 "Typed characters do not match the keys, or the layout resets.",
 ["wrong X11/Wayland layout", "console keymap differs from desktop layout", "two layouts installed and the switch key was hit", "locale not generated"],
 [("Check current layout settings", "localectl status"),
  ("List configured layouts", "gsettings get org.gnome.desktop.input-sources sources"),
  ("Set the console keymap", "sudo localectl set-keymap us"),
  ("Set the desktop layout", "gsettings set org.gnome.desktop.input-sources sources \"[('xkb', 'us')]\""),
  ("Check locale generation", "locale -a | head")],
 "Set the layout at both levels (console and desktop), and generate the locale if programs complain about LC_ALL/LANG."),
("Program is extremely slow, disk is fine",
 "An application takes seconds to respond; no obvious load.",
 ["it is swapping", "waiting on a network resource with a timeout", "blocking DNS lookups", "lock contention", "profiling needed"],
 [("Check for swap activity", "vmstat 1 5"),
  ("Watch the process state - D state means IO wait", "ps -o pid,stat,wchan,cmd -p PID"),
  ("Check what it is doing with the kernel", "sudo strace -p PID -c"),
  ("Check its file descriptors and sockets", "sudo lsof -p PID | tail -20"),
  ("Profile where the time goes", "sudo perf top -p PID")],
 "Swapping: add memory or reduce the workload. D-state on network: fix the remote or timeout. The strace -c summary usually names the blocking syscall."),
("The desktop session crashes back to the login screen",
 "GNOME logs out spontaneously or on certain actions.",
 ["a GPU driver crash", "an out-of-memory kill", "a broken extension", "a full home partition", "session files corrupted"],
 [("Check the previous session's crash in the journal", "journalctl -b -1 -p err --no-pager | tail -50"),
  ("Check for OOM kills around the logout time", "journalctl -b | grep -iE 'oom|killed' | tail"),
  ("Check disk space in home", "df -h ~"),
  ("Disable extensions and test", "gnome-extensions list --enabled"),
  ("Check GPU driver errors", "journalctl -b | grep -iE 'gpu|drm|nvidia|amdgpu' | tail -30")],
 "Fix the named cause: free space, disable the crashing extension, update/rollback the GPU driver, or add memory. The journal almost always contains the exact reason at the logout moment."),
("apt upgrade fails with unmet dependencies",
 "Install/upgrade stops with 'held broken packages'.",
 ["mixed repositories or wrong release codename", "a package pinned by apt preferences", "third-party repo out of sync", "interrupted previous dpkg run"],
 [("Fix any interrupted dpkg state first", "sudo dpkg --configure -a"),
  ("Try to repair dependencies", "sudo apt-get -f install"),
  ("See why the package cannot move (held/pinned)", "apt-cache policy PACKAGE"),
  ("Check for pins and preferences files", "ls /etc/apt/preferences.d/ && cat /etc/apt/sources.list"),
  ("Refresh lists and retry with details", "sudo apt update && sudo apt full-upgrade")],
 "Repair dpkg state, remove the offending pin or repo, and retry. Never force with --force-* unless you fully understand the consequence."),
("Battery drains very fast",
 "Laptop battery life far below expectation.",
 ["a runaway process", "GPU stuck on discrete mode", "screen brightness and radio usage", "background indexing or backup", "a kernel/driver regression"],
 [("Find processes waking the CPU most", "sudo powertop (or: top -b -n1 | head)"),
  ("Check what is using power right now", "sudo powertop --time=30"),
  ("Check GPU state and whether the dGPU is idle", "nvidia-smi  (or: cat /sys/class/drm/card*/device/power_state)"),
  ("Check for blocked suspend states", "systemd-analyze --no-pager 2>/dev/null; cat /sys/power/state"),
  ("Check disk activity", "iostat -x 5 3")],
 "Kill or fix the busy process, force the dGPU to sleep (prime-select/ envycontrol), and re-test. powertop's tunables list is the fastest inventory of waste."),
("Zombie processes accumulate",
 "ps shows many defunct processes.",
 ["a parent process is not reaping children", "a bug in a long-running daemon", "an init mismatch in containers"],
 [("List zombies and their parents", "ps -eo pid,ppid,stat,cmd | awk '$3 ~ /Z/'"),
  ("Identify the parent that must reap them", "ps -o pid,cmd -p PPID"),
  ("If the parent is a service, restart it", "sudo systemctl restart the-parent"),
  ("If the parent is gone, the zombies are reparented and will clear", "ps -eo pid,ppid,stat,cmd | awk '$3 ~ /Z/'")],
 "Zombies themselves cost almost nothing; the bug is in the parent that does not reap. Restart the parent, and file the bug there."),
("Wi-Fi adapter not found after kernel update",
 "No wireless interface appears after upgrading the kernel.",
 ["out-of-tree driver (dkms) not rebuilt for the new kernel", "firmware missing", "secure boot blocking unsigned module", "module blacklisted"],
 [("Check the kernel you are running", "uname -r"),
  ("Check the adapter is visible on the bus", "lspci -k | grep -A3 -i network"),
  ("Check DKMS status for the driver", "dkms status"),
  ("Check for secure boot blocking modules", "mokutil --sb-state && dmesg | grep -i 'key was rejected'"),
  ("Try loading the module explicitly", "sudo modprobe -v DRIVER")],
 "Rebuild the DKMS module for the running kernel, sign it (or disable secure boot), or boot the previous kernel until the fix lands."),
("DNS resolution is slow (seconds per lookup)",
 "Everything works but each new domain takes seconds.",
 ["a dead first nameserver in resolv.conf", "broken IPv6 route with no fallback", "systemd-resolved cache disabled", "upstream server slow"],
 [("Check which DNS servers are configured and their state", "resolvectl status"),
  ("Time the resolution directly against each server", "dig example.com @SERVER +stats | grep 'Query time'"),
  ("Flush the cache and re-test", "sudo resolvectl flush-caches"),
  ("Check for IPv6 reachability issues", "ping -6 -c2 2606:4700:4700::1111"),
  ("Test with a public resolver as a comparison", "dig @1.1.1.1 example.com +stats")],
 "Remove or replace the dead nameserver, disable broken IPv6 on that link if needed, and keep a cache (systemd-resolved) running."),
("A cron/script works in terminal but fails in systemd",
 "The exact command works by hand, the unit fails.",
 ["different environment (PATH, HOME, LANG)", "different user and permissions", "no TTY", "working directory not set", "quoting differences"],
 [("Compare environments", "systemd-run --user --wait --pipe env | sort  (vs your shell's env)"),
  ("Set explicit paths in the unit", "Environment=PATH=/usr/local/bin:/usr/bin:/bin"),
  ("Set the working directory explicitly", "WorkingDirectory=/srv/app"),
  ("Check the unit's own log", "journalctl -u myunit -n 50 --no-pager"),
  ("Run it once through systemd with full output", "sudo systemd-run --unit=test1 --wait --pipe /path/script.sh")],
 "Make the unit self-contained: absolute paths, explicit Environment=, WorkingDirectory=, and the right User=. Environment differences are the number-one cause."),
("Mounted drive shows wrong permissions for all users",
 "An NTFS/exFAT drive is root-only or ignores chmod.",
 ["filesystem does not support POSIX permissions", "mount options omit uid/gid/umask", "mounted by root without user options"],
 [("Check how it is mounted and with which options", "mount | grep /dev/sdb1"),
  ("Remount with explicit ownership options", "sudo umount /mnt/data && sudo mount -o uid=$(id -u),gid=$(id -g),umask=022 /dev/sdb1 /mnt/data"),
  ("Make it persistent in fstab", "echo 'UUID=XXXX /mnt/data exfat uid=1000,gid=1000,umask=022 0 0' | sudo tee -a /etc/fstab"),
  ("Verify after remount", "ls -l /mnt/data | head")],
 "Foreign filesystems need mount-time identity options (uid, gid, umask) - chmod cannot store POSIX permissions there."),
("Login loop: correct password, straight back to login",
 "The desktop flashes and returns to the login screen.",
 ["full home partition or quota", "broken ~/.Xauthority or session files", "GPU driver crash at session start", "a broken shell profile"],
 [("Log in on a TTY and check disk space", "df -h ~"),
  ("Check the session's crash log", "journalctl -b -p err --no-pager | tail -40"),
  ("Move aside session state and retry", "mv ~/.config/gnome-session ~/.config/gnome-session.bak"),
  ("Check the X/Wayland auth files", "ls -la ~/.Xauthority"),
  ("Try a different session from the login screen", "select 'GNOME on Xorg' or a plain session in the gear menu")],
 "Free the disk, remove the corrupted session state, or fix the driver. The journal at the moment of logout names the failing component."),
("Sound device missing after update",
 "The sound card vanished from settings.",
 ["kernel module not loaded", "firmware regression", "PipeWire wireplumber crashed", "the device is soft-blocked"],
 [("Check whether the card exists at kernel level", "aplay -l"),
  ("Check the module", "lsmod | grep snd"),
  ("Restart the user audio stack", "systemctl --user restart wireplumber pipewire pipewire-pulse"),
  ("Check firmware errors", "dmesg | grep -i firmware | tail"),
  ("Check for soft blocks", "rfkill list 2>/dev/null")],
 "Reload the module or restart the audio stack; if the kernel no longer sees the card, it is firmware/driver - boot the previous kernel to confirm."),
("rm says 'Argument list too long'",
 "Deleting many files with a wildcard fails.",
 ["the shell expands the glob into more arguments than execve allows", "ext4 directory with millions of entries"],
 [("Delete in batches through find and xargs", "find /path -maxdepth 1 -name '*.tmp' -print0 | xargs -0 rm -f"),
  ("Or let find do the deletion", "find /path -maxdepth 1 -name '*.tmp' -delete"),
  ("For millions of entries in one directory, delete in waves", "find /path -maxdepth 1 -type f | head -10000 | xargs rm -f")],
 "Never let the shell expand the glob; let find stream the names into rm. Repeat until empty for truly huge directories."),
("Screen resolution or refresh rate wrong",
 "Only a low resolution is offered, or the screen flickers.",
 ["missing GPU driver (falls back to llvmpipe)", "wrong mode not exposed by the monitor EDID", "Wayland vs X11 differences", "bad cable or adapter"],
 [("Check which driver and renderer are in use", "glxinfo | grep -E 'OpenGL renderer|direct rendering'"),
  ("Check the kernel driver", "lspci -k | grep -A3 -i vga"),
  ("List available modes", "xrandr  (on X11)"),
  ("Check for EDID read failures", "dmesg | grep -iE 'edid|drm' | tail"),
  ("On Wayland, check the compositor's mode list", "gnome-randr  (or the Settings app)")],
 "Install/enable the proper GPU driver first - software rendering cannot offer real modes. If the mode is genuinely absent, add it manually with xrandr (X11) or via a custom EDID."),
("System runs out of disk in /tmp",
 "Builds or apps fail when /tmp fills up.",
 ["a tool writing huge temp files", "no cleanup of old temp files", "tmpfs sized too small", "a crash left multi-GB dumps"],
 [("See what is in /tmp, largest first", "du -sh /tmp/* 2>/dev/null | sort -h | tail"),
  ("Check whether /tmp is tmpfs and its size", "df -h /tmp && mount | grep /tmp"),
  ("Clear old temp files owned by you", "find /tmp -maxdepth 1 -user $(id -u) -mtime +1 -exec rm -rf {} +"),
  ("Check for core dumps", "coredumpctl list")],
 "Delete the stale files, point the tool's temp dir elsewhere (TMPDIR=/var/tmp), and for tmpfs sizing adjust fstab. coredumpctl can reclaim huge dumps."),
("Chromium/Electron app shows a blank window",
 "The window opens but stays empty.",
 ["GPU compositing problem", "missing --no-sandbox in a restricted environment", "a crashed renderer", "wrong Wayland backend", "profile corruption"],
 [("Run it with GPU disabled to test", "app --disable-gpu"),
  ("Check the renderer crash in the log", "journalctl --user -n 50 --no-pager | grep -i renderer"),
  ("Try the other ozone platform", "app --ozone-platform=x11"),
  ("Start with a clean profile", "app --user-data-dir=/tmp/test-profile"),
  ("Check for missing libraries", "ldd /path/to/app | grep 'not found'")],
 "Usually --disable-gpu or --ozone-platform=x11 isolates it to the graphics stack; otherwise a clean profile or the missing library fixes it."),
("Can't write to a mounted Samba/NFS share",
 "Mount works but writes fail with permissions.",
 ["uid/gid mapping differs between server and client", "root_squash on NFS", "SMB credentials lack write rights", "mount options missing rw"],
 [("Check the mount options actually in use", "mount | grep -E 'nfs|cifs'"),
  ("Check server-side permissions", "ls -ln /mnt/share | head"),
  ("For NFS, check for root_squash", "cat /etc/exports  (on the server)"),
  ("Remount SMB with the right credentials and uid", "sudo mount -t cifs //server/share /mnt/s -o username=u,uid=$(id -u),gid=$(id -g)"),
  ("Test with a simple write", "touch /mnt/share/probe && rm /mnt/share/probe")],
 "Make the client and server agree on identity: uid/gid options for SMB, no_root_squash (or proper user mapping) for NFS."),
("Package manager database is locked",
 "apt fails with 'Could not get lock /var/lib/dpkg/lock'.",
 ["another apt/dpkg process is running", "an unattended-upgrade is in progress", "a crashed apt left stale locks", "a package manager GUI is open"],
 [("Check for running package processes first", "ps aux | grep -E 'apt|dpkg' | grep -v grep"),
  ("Wait for it or let it finish - do not kill dpkg mid-transaction", "systemctl status unattended-upgrades"),
  ("If truly stale (no process), remove the locks", "sudo rm /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/apt/archives/lock"),
  ("Then repair any interrupted state", "sudo dpkg --configure -a")],
 "Almost always: wait. Killing a package manager mid-write is how databases break; only remove locks when no process holds them."),
("Wayland app refuses to start, X11 version works",
 "App errors about display or crashes under Wayland.",
 ["no Wayland backend in the toolkit", "missing XWayland", "portal service not running", "screen capture APIs blocked by Wayland security"],
 [("Check the session type", "echo $XDG_SESSION_TYPE"),
  ("Force the X11 backend for that app", "GDK_BACKEND=x11 app  /  QT_QPA_PLATFORM=xcb app"),
  ("Check XWayland is available", "which Xwayland"),
  ("Check the portals", "systemctl --user status xdg-desktop-portal --no-pager")],
 "Force the app's X11 backend as a workaround; the real fix is a toolkit/portal update. Screen capture and global hotkeys need portals on Wayland by design."),
("The system does not shut down or reboot",
 "The machine hangs on shutdown with a spinning screen.",
 ["a unit refusing to stop", "a stuck NFS/network mount", "a process ignoring SIGTERM", "a kernel/driver hang"],
 [("Watch the shutdown messages (Esc on the splash)", "press Esc during shutdown to see units stopping"),
  ("From the journal after a forced power-off, check the last boot", "journalctl -b -1 -n 80 --no-pager"),
  ("Look for units that took long to stop", "journalctl -b -1 | grep -iE 'stopped|timed out' | tail -40"),
  ("Check for network mounts", "mount | grep -E 'nfs|cifs'"),
  ("Identify processes ignoring TERM next time", "ps -eo pid,stat,cmd | awk '$2 ~ /D/'")],
 "Fix or mask the unit that blocks shutdown; add noauto/x-systemd options to network mounts; a D-state process usually means an IO problem underneath."),
("New user cannot log in graphically",
 "Password accepted in TTY but the GUI refuses.",
 ["home directory missing or wrong ownership", "shell set to nologin", "account locked", "GDM/PAM misconfiguration"],
 [("Check the account state", "sudo passwd -S USER && sudo usermod -s /bin/bash USER"),
  ("Check home ownership", "ls -ld /home/USER"),
  ("Fix ownership if needed", "sudo chown -R USER:USER /home/USER"),
  ("Check the auth log for the refusal reason", "journalctl -u gdm -n 50 --no-pager"),
  ("Check the shell is valid", "getent passwd USER")],
 "Recreate or fix the home directory, set a valid shell, unlock the account. The auth log states the exact PAM stage that refused."),
("An executable refuses to run: 'Permission denied' though +x is set",
 "chmod +x done, still Permission denied.",
 ["the filesystem is mounted noexec", "the shebang interpreter is missing", "wrong architecture", "the binary was truncated during copy", "apparmor/selinux denial"],
 [("Check mount options for noexec", "mount | grep ' /home'"),
  ("Check the interpreter the script wants", "head -1 ./script.sh && ls -l $(head -1 ./script.sh | cut -c3-)"),
  ("Check the binary format", "file ./binary"),
  ("Run through the loader for a clearer error", "/lib64/ld-linux-x86-64.so.2 ./binary"),
  ("Check for security module denials", "sudo dmesg | grep -iE 'apparmor|denied' | tail")],
 "Remount without noexec, install the missing interpreter, or use the right architecture build. AppArmor denials are visible in dmesg with the profile name."),
("Text file has wrong encoding, shows strange characters",
 "Files from Windows show or store mangled characters.",
 ["CRLF line endings", "wrong charset (latin-1 vs utf-8)", "BOM markers", "locale mismatch"],
 [("Detect the encoding", "file -bi thefile.txt"),
  ("Inspect invisible characters", "cat -A thefile.txt | head"),
  ("Convert CRLF to LF", "sed -i 's/\\r$//' thefile.txt  (or: dos2unix thefile.txt)"),
  ("Convert charset", "iconv -f ISO-8859-1 -t UTF-8 in.txt > out.txt"),
  ("Check your locale", "locale")],
 "Convert line endings and charset explicitly, and set a UTF-8 locale. For archives, fix before extracting so filenames decode correctly."),
("Package holds old kernel and /boot fills up",
 "Updates fail: '/boot is full'.",
 ["many installed kernels", "large initramfs images", "small /boot partition"],
 [("Check usage", "df -h /boot"),
  ("List installed kernels", "dpkg -l 'linux-image-*' | grep ^ii"),
  ("Remove the oldest kernels (never the running one)", "sudo apt autoremove --purge"),
  ("Check what is consuming /boot", "du -sh /boot/* | sort -h | tail"),
  ("Verify the running kernel before cleanup", "uname -r")],
 "Let autoremove purge old kernels, or remove specific old linux-image packages, keeping the running one and one fallback."),
("Process uses 100% of one core and cannot be killed",
 "kill -9 seems to do nothing.",
 ["uninterruptible sleep (D state) on IO", "kernel thread", "a stuck NFS mount", "firmware/driver hang"],
 [("Check the process state", "ps -o pid,stat,wchan,cmd -p PID"),
  ("D state means IO wait - check the disk", "iostat -xz 1 3"),
  ("Check kernel messages", "dmesg -T | tail -30"),
  ("If it is an NFS hang, check the mount", "mount | grep nfs && nfsstat -m"),
  ("Reboot may be the only way out of a driver hang", "sudo reboot (after saving work)")],
 "SIGKILL cannot kill D-state processes; fix the underlying IO (disk, network mount). A hung driver often needs a reboot - note it for a bug report."),
("Newly installed program is not found in PATH",
 "command not found right after installing.",
 ["the binary is in a non-standard directory", "PATH was not updated", "hash cache in the shell is stale", "it is a shell function or alias", "the package installed a different name"],
 [("Find where it actually is", "dpkg -L PACKAGE | grep bin/  (or: find / -name 'program' -type f 2>/dev/null)"),
  ("Check your PATH", "echo $PATH"),
  ("Refresh the shell's command hash", "hash -r"),
  ("Check what the name resolves to", "type -a program"),
  ("Run it by full path to confirm it works", "/usr/local/bin/program --version")],
 "Add the directory to PATH in your shell rc, run hash -r, and double-check the real binary name - some packages install versioned names."),
("Memory shows high usage but system is healthy",
 "free shows almost no free memory; is this a problem?",
 ["Linux uses free RAM as cache", "buff/cache is reclaimable", "available is the number that matters"],
 [("Read the numbers correctly", "free -h"),
  ("Watch the available column under load", "watch -n2 free -h"),
  ("Check swap activity - that is the real pressure signal", "vmstat 1 5"),
  ("Identify real consumers", "ps aux --sort=-%mem | head")],
 "This is normal. Compare 'available', not 'free'. Only worry when available is small and swap in/out (si/so) is active."),
("Firmware update is offered but the tool fails",
 "fwupd reports errors.",
 ["device not supported by fwupd", "LVFS metadata stale", "permissions/daemon issue", "firmware write blocked by power settings"],
 [("Check the device is recognized", "fwupdmgr get-devices"),
  ("Refresh metadata", "fwupdmgr refresh"),
  ("See pending updates", "fwupdmgr get-updates"),
  ("Check the daemon", "systemctl status fwupd --no-pager"),
  ("Apply updates (AC power!)", "fwupdmgr update")],
 "Refresh and retry; if the device is unsupported, use the vendor's own updater. Never update firmware on low battery."),
("CRON job runs but script fails on relative paths",
 "The job fires; log shows 'No such file or directory'.",
 ["cron's working directory is the user's home", "relative paths in the script", "PATH does not include /usr/local/bin", "locale or TZ differences"],
 [("Make every path absolute in the script", "grep -nE '[^/]\\w+/' script.sh"),
  ("Set an explicit working directory", "cd /srv/app || exit 1  at the top of the script"),
  ("Export a sane environment at the top", "PATH=/usr/local/bin:/usr/bin:/bin"),
  ("Log everything while debugging", "*/5 * * * * /path/script.sh >> /var/log/script.log 2>&1")],
 "Scripts for cron must be self-contained: absolute paths, explicit cd, explicit PATH, and output redirected to a log you actually read."),
("BTRFS filesystem reports errors",
 "btrfs commands show read/write errors or a failed scrub.",
 ["failing disk", "bit rot (checksum mismatch)", "memory errors", "loose SATA cable"],
 [("Check device error counters", "sudo btrfs device stats /"),
  ("Start a scrub and watch it", "sudo btrfs scrub start -B /"),
  ("Check SMART immediately", "sudo smartctl -a /dev/nvme0n1"),
  ("Look for the failing file in the log", "sudo journalctl -k | grep -i btrfs | tail -30"),
  ("If a disk is failing, replace it with btrfs replace", "sudo btrfs replace start /dev/old /dev/new /")],
 "Fix the hardware first (cable/disk). BTRFS checksum errors with healthy hardware usually mean RAM - run a memtest before trusting the pool."),
("Terminal shows garbage after binary output",
 "The terminal is full of strange characters.",
 ["a binary file was catted to the terminal", "wrong TERM value", "UTF-8 output to a non-UTF-8 locale", "an escape sequence set an odd charset"],
 [("Reset the terminal state", "reset  (or: tput reset)"),
  ("Check the TERM variable", "echo $TERM"),
  ("Check locale", "locale | head -3"),
  ("Next time, pipe binary output through cat -v or less", "cat -v binary.bin | head")],
 "reset fixes almost every mangled terminal. Avoid cat-ing binaries; use xxd or strings."),
("A GUI app scales wrongly on HiDPI",
 "Tiny or huge UI on a high-resolution screen.",
 ["fractional scaling settings", "toolkit-specific scale factors", "X11 app under Wayland scaling", "monitor DPI misreported"],
 [("Check the desktop's scaling setting", "gsettings get org.gnome.desktop.interface text-scaling-factor"),
  ("Check GDK scaling", "gsettings get org.gnome.desktop.interface scaling-factor"),
  ("For GTK apps, try an explicit scale", "GDK_SCALE=2 app"),
  ("For Qt apps", "QT_SCALE_FACTOR=1.5 app"),
  ("Check the monitor's reported size", "xrandr --verbose | grep -A2 ' connected'")],
 "Set the desktop scale first; for stubborn toolkits, override per-app with GDK_SCALE / QT_SCALE_FACTOR."),
("Shared library version conflict breaks an app",
 "App fails after installing something else: symbol lookup error.",
 ["LD_LIBRARY_PATH override", "duplicate libraries in /usr/local/lib", "ldconfig cache stale", "a package downgraded a shared lib"],
 [("See which libraries it resolves", "ldd ./app | head -20"),
  ("Check the loader search path", "ldconfig -p | grep LIBNAME"),
  ("Check for LD_LIBRARY_PATH interference", "echo $LD_LIBRARY_PATH"),
  ("Refresh the loader cache", "sudo ldconfig"),
  ("Trace the actual resolution failure", "LD_DEBUG=libs ./app 2>&1 | grep -i 'searching\\|trying' | head -30")],
 "Remove the rogue library or LD_LIBRARY_PATH entry, run ldconfig, and prefer packaged libraries over hand-copied ones in /usr/local/lib."),
("Random freezes under load",
 "The whole system stutters or locks briefly.",
 ["memory pressure and reclaim", "IO saturation", "GPU driver stalls", "thermal throttling", "kernel bug"],
 [("Check memory pressure and swap", "vmstat 1 10"),
  ("Check IO saturation", "iostat -xz 1 10"),
  ("Check temperatures", "sensors"),
  ("Check kernel messages for stalls", "dmesg -T | grep -iE 'stall|hung|reset' | tail -30"),
  ("Check for firmware/BIOS updates if reproducible", "sudo fwupdmgr get-updates")],
 "Attack the specific resource that saturates. Reproducible freezes with clean logs point at firmware/driver - update, or boot an older kernel to bisect."),
("Journal takes gigabytes of disk",
 "journalctl --disk-usage shows a huge number.",
 ["no size limit configured", "verbose units spamming the log", "debug logging left on"],
 [("See the usage and the noisiest units", "journalctl --disk-usage && journalctl --no-pager | wc -l"),
  ("Vacuum to a sane size", "sudo journalctl --vacuum-size=200M"),
  ("Cap it permanently", "set SystemMaxUse=200M in /etc/systemd/journald.conf then restart systemd-journald"),
  ("Find the noisy service", "journalctl -b --no-pager | awk '{print $5}' | sort | uniq -c | sort -rn | head")],
 "Vacuum now, cap the size in journald.conf, and fix the unit that logs in a loop."),
("Dual boot: Windows entry missing from GRUB",
 "After installing/updating Windows the menu does not show it.",
 ["os-prober disabled", "Windows bootloader on another ESP", "GRUB config not regenerated", "fast startup left the NTFS dirty"],
 [("Check os-prober is enabled and run it", "sudo os-prober"),
  ("Regenerate the GRUB config", "sudo update-grub"),
  ("Check for the Windows EFI files", "ls /boot/efi/EFI/Microsoft/Boot/bootmgfw.efi"),
  ("If missing, check the other disk's ESP", "sudo fdisk -l | grep -i efi"),
  ("Disable Windows Fast Startup if NTFS is dirty", "powercfg /h off  (in Windows)")],
 "Enable os-prober, regenerate grub.cfg, and make sure the ESP with the Windows loader is mounted and scanned. Fast Startup must be off for clean dual-boot."),
("Application writes logs but you see nothing in journalctl",
 "The app logs to a file, not the journal.",
 ["the app writes its own file", "stdout goes to a socket or /dev/null", "unit type is simple with no capture", "log level too high"],
 [("Check where the unit sends output", "systemctl cat myapp"),
  ("Look at the app's own log location", "find /var/log -name '*myapp*'"),
  ("Watch the unit's stdout if it is journald", "journalctl -u myapp -f"),
  ("Increase verbosity temporarily", "sudo systemctl edit myapp  (add Environment=LOG_LEVEL=debug)")],
 "Look where the app actually writes: its own file, syslog, or stdout captured by journald. systemctl cat shows the configured streams."),
("New device works only as root",
 "The device node or interface is root-only.",
 ["udev rule missing", "device permissions 0600", "group membership missing", "logind session not active"],
 [("Check the device node and its group", "ls -l /dev/DEVICE"),
  ("Check your groups", "id"),
  ("Add yourself to the owning group", "sudo usermod -aG GROUP $USER"),
  ("Re-login for group changes to apply", "loginctl terminate-user $USER  (or just log out)"),
  ("Check udev sees the device", "udevadm info -q all -n /dev/DEVICE | head -30")],
 "Join the right group and re-login - group membership only applies to new sessions."),
("The system cannot find a command that exists in /usr/local/bin",
 "Installed a tool manually; command not found.",
 ["/usr/local/bin not in PATH", "binary not executable", "installed to a versioned name", "shell hash cache stale"],
 [("Confirm the file exists and is executable", "ls -l /usr/local/bin/TOOL"),
  ("Run it by absolute path", "/usr/local/bin/TOOL --version"),
  ("Check PATH ordering", "echo $PATH | tr ':' '\\n'"),
  ("Fix PATH persistently", "echo 'export PATH=/usr/local/bin:$PATH' >> ~/.profile"),
  ("Refresh the hash table", "hash -r")],
 "Add the directory to PATH in your shell profile, ensure the execute bit, and run hash -r in the current shell."),
("Firewall blocks a local service after enabling ufw",
 "A dev server worked; after ufw enable, it is unreachable.",
 ["ufw default deny incoming", "the port is not allowed", "the app binds only to localhost", "ufw rule order"],
 [("Check ufw status and rules", "sudo ufw status verbose"),
  ("Allow the specific port", "sudo ufw allow 8080/tcp"),
  ("Check what the app binds to", "ss -tlnp | grep 8080"),
  ("If it binds to 127.0.0.1 only, that is why remote clients cannot reach it", "bind to 0.0.0.0 in the app config if intended"),
  ("Re-test from the client side", "nc -vz server 8080")],
 "Allow the port in ufw and make sure the app listens on the interface you think it does. Binding to localhost is invisible from the network by design."),
("Updates fail with TLS/certificate errors",
 "apt or git refuses with certificate problems.",
 ["system clock wrong", "expired CA bundle", "corporate proxy interception", "TLS interception by antivirus"],
 [("Check the clock first - it causes most of these", "timedatectl && date"),
  ("Update the CA certificates", "sudo apt install --reinstall ca-certificates"),
  ("Check proxy environment variables", "env | grep -i proxy"),
  ("Test the endpoint directly", "curl -v https://deb.debian.org 2>&1 | tail -20")],
 "Fix the clock, refresh ca-certificates, and remove or trust the intercepting proxy. Never disable TLS verification globally to 'fix' this."),
("Random reboots or kernel panics",
 "The machine restarts without warning.",
 ["hardware fault (RAM, PSU, thermals)", "overclock instability", "kernel driver bug", "failing disk"],
 [("Check the previous boot for panic traces", "journalctl -k -b -1 | tail -60"),
  ("Check temperatures right before the crash", "sensors  (and check logs for thermal events)"),
  ("Run a memory test", "memtester 2G 1  (or boot memtest86+)"),
  ("Check the disk's SMART health", "sudo smartctl -H /dev/nvme0n1"),
  ("Check for firmware updates", "sudo fwupdmgr get-updates")],
 "Look for the pattern: thermal (clean the fans), RAM (memtest), PSU (heavy-load reboots), driver (previous kernel bisect). Hardware first, software second."),
("The 'device is busy' on umount",
 "umount fails: target is busy.",
 ["a shell cd'd into the mount", "an editor or process has a file open there", "a container bind-mount", "NFS clients"],
 [("Find the processes using it", "lsof +f -- /mnt/usb  (or: fuser -vm /mnt/usb)"),
  ("Check for shells sitting inside", "ls -l /proc/*/cwd 2>/dev/null | grep /mnt/usb"),
  ("Close them, or kill the offending process", "kill PID"),
  ("Lazy unmount as a last resort", "sudo umount -l /mnt/usb")],
 "Find and close what holds the mount. lazy unmount detaches now and cleans up later - data may still be flushing, so prefer the real fix."),
("Flatpak app has no access to files",
 "A sandboxed app cannot see the home directory.",
 ["Flatpak sandbox permissions", "portal not running", "filesystem permissions not granted"],
 [("See the app's current permissions", "flatpak info --show-permissions APP_ID"),
  ("Grant access interactively with Flatseal or", "flatpak override --user --filesystem=home APP_ID"),
  ("Check portals are running", "systemctl --user status xdg-desktop-portal --no-pager"),
  ("Re-launch the app fully", "flatpak run APP_ID")],
 "Grant the narrowest filesystem permission the app actually needs; portals handle file pickers without full home access."),
("Bash script has a syntax error that makes no sense",
 "bash reports an error at a line that looks fine.",
 ["an unclosed quote or bracket above the reported line", "CRLF line endings from Windows", "an unescaped special character in a heredoc", "a missing fi/done/esac"],
 [("Check the whole file without running it", "bash -n script.sh"),
  ("Show line endings", "cat -A script.sh | head -20"),
  ("Fix CRLF endings", "sed -i 's/\\r$//' script.sh"),
  ("Trace execution to see where it derails", "bash -x script.sh 2>&1 | tail -30")],
 "The reported line is usually a symptom; the cause is earlier. bash -n and cat -A find 90% of these."),
("The mouse or keyboard stops responding",
 "Input freezes, sometimes with the system otherwise alive.",
 ["USB autosuspend", "kworker/USB controller issue", "driver crash", "hardware failure"],
 [("Check kernel messages around the freeze", "dmesg -T | tail -50"),
  ("Check for USB resets", "dmesg -T | grep -iE 'usb.*reset|disconnect' | tail"),
  ("Disable USB autosuspend for the device as a test", "echo -1 | sudo tee /sys/bus/usb/devices/usb*/power/autosuspend"),
  ("Check input devices are still enumerated", "lsusb && libinput list-devices 2>/dev/null | head")],
 "A USB reset storm usually means power or cable; autosuspend quirks are fixable with a udev rule. If it is a PS/2-free laptop, test with an external device."),
("Writes to an SSD are extremely slow",
 "The disk became slow after being fast.",
 ["almost full SSD (no free blocks for wear leveling)", "TRIM not running", "SATA link at low speed", "thermal throttling of the SSD", "failing drive"],
 [("Check free space and TRIM support", "df -h / && sudo hdparm -I /dev/sda | grep -i trim"),
  ("Run fstrim manually", "sudo fstrim -v /"),
  ("Check the link speed", "sudo hdparm -I /dev/sda | grep -i speed"),
  ("Check the drive temperature and health", "sudo smartctl -A /dev/sda | grep -iE 'temp|wear|percent'")],
 "Keep 10-20% free on SSDs, enable the fstrim timer, and check SMART wear values - a worn drive is slow because it is dying."),
("An app window is missing from the taskbar/dock",
 "The window exists but has no dock entry.",
 ["the app sets skip-taskbar", "the .desktop file does not match the WM class", "a shell extension glitch"],
 [("Check the window's WM class", "xprop WM_CLASS  (click the window)"),
  ("Check the .desktop file's StartupWMClass", "grep -i startupwmclass ~/.local/share/applications/*.desktop"),
  ("Align the two", "set StartupWMClass in the desktop file to the real WM_CLASS"),
  ("Restart the shell as a last resort", "press Alt+F2, r, Enter  (X11)  /  log out-in (Wayland)")],
 "The dock matches windows to apps by WM class; make the .desktop file agree with what the app actually sets."),
("Wi-Fi keeps dropping or will not connect",
 "The network disappears, reconnects in a loop, or asks for the password again and again.",
 ["driver power management is turning the radio off", "the access point rejects the saved profile", "regulatory domain blocks the channel", "weak signal at the edge of coverage", "NetworkManager has a stale duplicate profile"],
 [("Check the radio is not blocked in software or hardware", "rfkill list"),
  ("Look at the current link and signal strength", "iw dev wlan0 link"),
  ("Check NetworkManager's view and the last failure reason", "nmcli device status && journalctl -u NetworkManager -n 80 --no-pager"),
  ("Scan for the AP and compare its channel and signal", "nmcli device wifi list"),
  ("Disable Wi-Fi power saving as a test", "iw dev wlan0 set power_save off"),
  ("If duplicates exist, delete the stale profile", "nmcli connection delete 'MyWifi'")],
 "Power saving and stale profiles cause most drops. Turn power save off, remove duplicate profiles, and reconnect; if signal is under -70 dBm the fix is physical."),
("Bluetooth device pairs but produces no sound",
 "Headphones connect successfully, yet audio keeps playing on the speakers.",
 ["the sink is not selected as the default output", "the codec handshake failed", "the device is connected to the wrong profile (HSP instead of A2DP)", "PipeWire or WirePlumber is confused"],
 [("Check which profile the card is using", "pactl list cards | grep -A 20 'bluez'"),
  ("List sinks and find the default", "pactl list short sinks && pactl info | grep 'Default Sink'"),
  ("Set the correct profile and default sink", "pactl set-card-profile bluez_card.XX a2dp-sink && pactl set-default-sink bluez_output.XX.a2dp-sink"),
  ("Restart the audio stack if state is stuck", "systemctl --user restart pipewire wireplumber"),
  ("Check the logs for codec errors", "journalctl --user -u wireplumber -n 50 --no-pager")],
 "Force the A2DP profile and set the sink as default. If it still fails, restarting PipeWire and WirePlumber clears stale device state."),
("No audio at all after a fresh install",
 "The system boots, but nothing produces sound and no devices are listed.",
 ["the correct audio server is not running", "the sound card is muted at the hardware level", "firmware or the wrong codec module is missing", "the user is not in the audio group (rare on modern setups)"],
 [("Check whether PipeWire or PulseAudio is actually running", "systemctl --user status pipewire pipewire-pulse wireplumber"),
  ("List cards and sinks from the server's point of view", "pactl list short cards && pactl list short sinks"),
  ("Check ALSA sees the hardware", "aplay -l"),
  ("Unmute everything at the ALSA level and raise levels", "alsamixer"),
  ("Look for firmware load failures in the kernel log", "sudo dmesg | grep -i -E 'firmware|sof|hda'")],
 "If ALSA sees the card but the server does not, the session audio stack is the problem - restart the user services. If ALSA sees nothing, it is a kernel or firmware issue."),
("Printer prints nothing or jobs vanish",
 "Documents stay in the queue forever, or jobs disappear without output.",
 ["the printer is unreachable over the network", "the wrong driver or PPD is selected", "CUPS is stopped", "a stuck job is blocking the queue"],
 [("Check the queue and job states", "lpstat -t"),
  ("Check CUPS itself", "systemctl status cups --no-pager"),
  ("Cancel the stuck job", "cancel -a"),
  ("Verify the printer answers on the network", "ping -c 2 printer.local && lpinfo -v | grep -i network"),
  ("Watch CUPS error messages while resending", "journalctl -u cups -f")],
 "Cancel the blocked job, confirm CUPS is running and the printer is reachable, then re-add the queue with the correct driver if jobs keep failing."),
("System will not resume from suspend",
 "The screen stays black after opening the lid, or the machine reboots instead of resuming.",
 ["the GPU driver fails to reinitialize", "a USB or PCI device does not come back", "the swap file is too small for hibernation", "kernel regression in the resume path"],
 [("Read the resume attempt from the previous boot", "journalctl -b -1 | grep -i -E 'resume|suspend|pci|gpu' | tail -40"),
  ("Check the sleep states the firmware offers", "cat /sys/power/state && cat /sys/power/mem_sleep"),
  ("For hibernation, verify the resume device matches", "cat /proc/cmdline | grep -o 'resume=[^ ]*' && swapon --show"),
  ("Test suspending from the terminal to see live errors", "sudo systemctl suspend"),
  ("Try the other suspend mode if offered", "echo deep | sudo tee /sys/power/mem_sleep")],
 "Most resume failures are driver bugs - capture the previous boot log, test s2idle versus deep, and for hibernation make sure the swap is at least as large as RAM."),
("Boot is extremely slow",
 "The system takes minutes to reach the login screen, with no single obvious hang.",
 ["a service waits on a network timeout", "a filesystem check runs on every boot", "an external device is being waited for", "the initramfs is bloated or misconfigured"],
 [("See exactly which units took the longest", "systemd-analyze blame | head -25"),
  ("See the critical chain of the boot", "systemd-analyze critical-chain"),
  ("Check for failed or waiting units", "systemctl --failed && systemctl list-jobs"),
  ("Look for timeouts in the kernel log", "journalctl -b | grep -i -E 'timeout|timed out' | head -30"),
  ("Check whether fsck runs every boot", "journalctl -b | grep -i fsck")],
 "Usually one unit waiting on the network or a device dominates. Mask or fix that unit; for repeated fsck, check the filesystem's max-mount-count with tune2fs."),
("Emergency mode after editing fstab",
 "The boot drops to an emergency shell after a change to /etc/fstab.",
 ["a UUID or device path is wrong", "a mount option is unsupported", "the mount point directory does not exist", "the filesystem needs repair"],
 [("Read the exact fstab error", "journalctl -xb | grep -i -B2 -A5 fstab"),
  ("Inspect the file and compare UUIDs with reality", "cat /etc/fstab && blkid"),
  ("Test each entry without rebooting", "sudo findmnt --verify --verbose"),
  ("Comment out the broken line to boot normally", "sudo sed -i 's|^UUID=bad|#UUID=bad|' /etc/fstab"),
  ("Reload systemd after fixing", "sudo systemctl daemon-reload")],
 "Fix or comment the bad line, verify with findmnt --verify, and only then reboot. The nofail option prevents this class of failure for non-critical mounts."),
("Black screen after a graphics driver update",
 "The system boots (disk activity, maybe sound) but the display never lights up.",
 ["the new driver fails to load", "the display manager crashed", "the wrong kernel module is blacklisted", "Wayland session fails and no X11 fallback exists"],
 [("Switch to a TTY with Ctrl+Alt+F3 and log in", "sudo journalctl -b | grep -i -E 'drm|nvidia|amdgpu|i915' | tail -40"),
  ("Check the display manager state", "systemctl status gdm --no-pager"),
  ("Check which GPU drivers actually loaded", "lsmod | grep -E 'nvidia|amdgpu|i915|nouveau'"),
  ("Boot the previous kernel from the GRUB menu as a fallback", "hold Shift or Esc during boot"),
  ("Reinstall or roll back the driver from the TTY", "sudo apt install --reinstall nvidia-driver-XXX")],
 "The kernel log from the current boot names the failing module. Rolling back to the previous kernel or driver usually restores the display immediately."),
("Keyboard layout or language input is wrong",
 "Typed characters do not match the physical keys, or a layout cannot be switched.",
 ["the layout is configured in two places and they disagree", "the input method is not running", "only the console layout was set, not the graphical one", "per-window layout settings are disabled"],
 [("Check the active layouts and groups", "localectl status && setxkbmap -query"),
  ("List what the session thinks is available", "gsettings get org.gnome.desktop.input-sources sources"),
  ("Set the console and graphical layout consistently", "sudo localectl set-x11-keymap us,de pc105 '' grp:alt_shift_toggle"),
  ("For complex scripts, check the input method", "pgrep -a ibus; pgrep -a fcitx5"),
  ("Apply a layout immediately for testing", "setxkbmap us -variant altgr-intl")],
 "Set the layout once with localectl (it writes both console and X11 config), and make sure only one input-method framework is running."),
("Locale or timezone is wrong in applications",
 "Dates, currency or character encoding appear wrong; some apps print warnings about locale.",
 ["the locale was never generated", "LC_ALL overrides everything and is set incorrectly", "the timezone is UTC when local time was expected", "SSH forwards a broken locale from the client"],
 [("Check the effective locale and timezone", "locale && timedatectl"),
  ("List generated locales", "locale -a | head -20"),
  ("Generate the missing locale", "sudo locale-gen en_US.UTF-8"),
  ("Set timezone and time sync in one move", "sudo timedatectl set-timezone Europe/Berlin && sudo timedatectl set-ntp true"),
  ("Check for overrides in shell profiles", "grep -rn 'LC_\\|LANG' ~/.profile ~/.bashrc /etc/environment 2>/dev/null")],
 "Generate the locale, set the timezone via timedatectl, and hunt down stale LC_ALL exports - one bad export in a profile can shadow everything."),
("Clock drifts or jumps around",
 "Timestamps in logs do not match reality, or the clock jumps by hours.",
 ["NTP synchronization is disabled or blocked", "the RTC is set to local time instead of UTC", "a VM's clock is being corrected by the hypervisor", "a failing CMOS battery"],
 [("Check sync status and the last correction", "timedatectl && journalctl -u systemd-timesyncd -n 30 --no-pager"),
  ("See which time sources are reachable", "chronyc sources -v  (if chrony is installed)"),
  ("Check whether the hardware clock is UTC", "timedatectl | grep -i rtc"),
  ("Force a sync now", "sudo systemctl restart systemd-timesyncd"),
  ("For VMs, check for host time sync tools", "systemctl status systemd-timesyncd qemu-guest-agent --no-pager")],
 "Re-enable NTP, set the RTC to UTC, and in VMs let the guest agent handle time instead of fighting the host."),
("DNS resolution fails intermittently",
 "Some sites resolve, others do not; ping by IP works while names fail.",
 ["the resolver list contains a dead server", "systemd-resolved cache is stale", "VPN split-DNS is leaking the wrong server", "the interface's DNS is not being applied"],
 [("Check the effective resolver configuration", "resolvectl status"),
  ("Query a name directly against a known server", "dig @1.1.1.1 example.com +short"),
  ("Compare with the system resolver path", "resolvectl query example.com"),
  ("Flush caches and restart the resolver", "sudo resolvectl flush-caches && sudo systemctl restart systemd-resolved"),
  ("Check what the DHCP client handed over", "nmcli dev show | grep -i dns")],
 "If dig against a public resolver works but the system path fails, the local resolver or its upstream list is at fault - flush and restart it."),
("Package manager lock or broken dpkg state",
 "apt refuses to run: another process holds the lock, or dpkg was interrupted.",
 ["another package operation is genuinely running", "a previous operation crashed mid-way", "unattended-upgrades started at the same moment", "dpkg needs a manual configure pass"],
 [("Find what holds the lock", "sudo fuser -v /var/lib/dpkg/lock-frontend"),
  ("Check for running package processes", "pgrep -a 'apt|dpkg|unattended'"),
  ("Fix an interrupted dpkg safely", "sudo dpkg --configure -a"),
  ("Repair dependencies if the state is inconsistent", "sudo apt --fix-broken install"),
  ("Only as a last resort, remove stale lock files", "sudo rm /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock && sudo dpkg --configure -a")],
 "Prefer waiting for the real process. If nothing is running, dpkg --configure -a plus apt --fix-broken install repairs almost every interrupted state."),
("Package installation fails with held or broken packages",
 "apt reports held packages, unmet dependencies, or refuses to upgrade.",
 ["a package is on hold (apt-mark)", "a third-party repository is unreachable or mis-signed", "a partial upgrade left inconsistent versions", "a PPA conflicts with the base distribution"],
 [("List held packages", "apt-mark showhold"),
  ("See the exact dependency conflict", "sudo apt install -f"),
  ("Check repository reachability and signatures", "sudo apt update 2>&1 | grep -i -E 'err|fail|no_pubkey'"),
  ("Inspect pinned or problematic sources", "apt-cache policy problematic-package"),
  ("Unhold or remove the blocking package", "sudo apt-mark unhold package-name")],
 "Unhold what blocks the transaction and fix the offending repository. A mis-signed repo is fixed by re-importing its key, not by forcing the install."),
("Flatpak application fails to launch",
 "A Flatpak app does nothing when clicked, or complains about permissions.",
 ["a runtime is missing or outdated", "the app lacks a portal or permission it needs", "the sandbox blocks the requested path", "the app's files are corrupted"],
 [("Run the app from a terminal to see the real error", "flatpak run org.example.App"),
  ("Check for missing runtimes", "flatpak list --runtime && flatpak repair --user"),
  ("Inspect and adjust permissions", "flatpak info --show-permissions org.example.App && flatpak override --user --filesystem=~/Projects org.example.App"),
  ("Update everything", "flatpak update -y"),
  ("Reinstall if files are damaged", "flatpak uninstall --delete-data org.example.App && flatpak install flathub org.example.App")],
 "Missing runtimes and sandbox permissions explain most failures. flatpak run in a terminal prints the real reason every time."),
("Snap application cannot access files or devices",
 "A Snap works but cannot see files outside its home, or needs a device it cannot open.",
 ["the snap lacks a plug connection", "strict confinement blocks the path", "the mount namespace is stale after an update", "interface not available on the system"],
 [("See the snap's connections", "snap connections app-name"),
  ("Connect the missing interface", "sudo snap connect app-name:removable-media"),
  ("Check for errors in the snap's logs", "snap logs app-name -n 50"),
  ("Restart the app after connection changes", "snap restart app-name"),
  ("If the namespace is stale, refresh it", "sudo snap refresh app-name")],
 "Snaps are confined by design - connect the right interface instead of trying to escape the sandbox."),
("Application menu entry is missing or has the wrong icon",
 "The app runs from the terminal but does not appear in the launcher, or shows a generic icon.",
 ["the .desktop file is in the wrong directory", "the desktop database cache is stale", "the Exec or Icon path is wrong", "the file lacks the executable bit or has a syntax error"],
 [("Validate the desktop file", "desktop-file-validate ~/.local/share/applications/app.desktop"),
  ("Check where the file lives", "ls ~/.local/share/applications /usr/share/applications | grep -i app"),
  ("Refresh the database cache", "update-desktop-database ~/.local/share/applications"),
  ("Confirm the Exec binary and Icon name resolve", "grep -E 'Exec|Icon' ~/.local/share/applications/app.desktop"),
  ("Check the icon theme actually contains it", "find /usr/share/icons -name 'app-icon*' 2>/dev/null | head")],
 "Fix the file, make it executable if needed, then update the desktop database - launchers read the cache, not the directory."),
("USB device is not detected",
 "A flash drive, serial adapter or camera does not appear at all.",
 ["the port or cable is dead or charge-only", "the kernel module for the chipset is missing", "the device needs a quirk or more power", "the filesystem on it is corrupt"],
 [("Watch the kernel as you plug it in", "sudo dmesg -w"),
  ("List USB devices and see whether it enumerates", "lsusb && lsusb -t"),
  ("Check the block layer for a new disk", "lsblk -o NAME,SIZE,TYPE,TRAN"),
  ("Look for power or reset errors in the log", "sudo dmesg | grep -i -E 'usb|reset|over-current' | tail -30"),
  ("For a corrupt filesystem, run a check", "sudo fsck /dev/sdb1")],
 "If lsusb shows nothing the problem is physical or firmware; if it shows the device but no block device appears, it is a driver or media issue."),
("Disk shows I/O errors or the filesystem went read-only",
 "The system logs I/O errors and suddenly mounts a filesystem read-only.",
 ["the drive is failing (SMART will show it)", "a cable or power supply is unstable", "the filesystem hit an inconsistency and remounted read-only for safety", "controller or firmware bug under load"],
 [("Read the drive's health", "sudo smartctl -H /dev/sda && sudo smartctl -A /dev/sda | grep -i -E 'realloc|pending|uncorrect'"),
  ("Find the exact kernel errors", "sudo dmesg | grep -i -E 'I/O error|ata|nvme|failed command' | tail -40"),
  ("Check the mount state", "findmnt -no OPTIONS /data"),
  ("Check the filesystem", "sudo umount /data && sudo fsck -f /dev/sdb1"),
  ("Capture SMART before deciding", "sudo smartctl -a /dev/sda > ~/smart-report.txt")],
 "Rising reallocated or pending sectors mean the disk is dying - back up first. A single event with clean SMART often means a cable or power problem."),
("SSD or NVMe is slow or gets hot",
 "Transfers are far below the drive's rating, or the drive throttles and the system stutters.",
 ["the drive is thermally throttling", "TRIM is not running", "the filesystem is nearly full", "PCIe link is running at reduced width or speed"],
 [("Check the link speed and width", "sudo lspci -vv | grep -A3 -i nvme | grep -i -E 'lnksta|lnkcap'"),
  ("Check temperature and wear", "sudo nvme smart-log /dev/nvme0 | grep -i -E 'temperature|used|throttle'"),
  ("Verify periodic TRIM is enabled", "systemctl status fstrim.timer --no-pager"),
  ("Run a manual trim", "sudo fstrim -av"),
  ("Check free space and fragmentation pressure", "df -h / && sudo btrfs filesystem usage / 2>/dev/null")],
 "Overheating and a missing fstrim.timer explain most slowness. A PCIe link at half width points at the slot or the drive's seating."),
("Out of memory kills applications",
 "Apps vanish without warning; the kernel log mentions oom-killer.",
 ["a process leaked memory over time", "the workload genuinely exceeds RAM", "swap is disabled or too small", "a single command allocated everything at once"],
 [("Confirm the kill in the log", "journalctl -k | grep -i -E 'oom|killed process' | tail -20"),
  ("See current memory and swap pressure", "free -h && vmstat 1 5"),
  ("Find the biggest memory consumers", "ps aux --sort=-%rss | head -10"),
  ("Check whether swap exists", "swapon --show"),
  ("Watch for a growing process over time", "watch -n5 'ps aux --sort=-%rss | head -5'")],
 "Fix the leaking process first; add swap or zram as a safety net. Early OOM kills with plenty of swap often indicate a memory-hungry workload, not a leak."),
("Processes in D state will not die",
 "kill -9 does nothing and the process shows state D (uninterruptible sleep).",
 ["the process is blocked on I/O from a failing device", "an NFS or network mount is unreachable", "a kernel driver is stuck", "a FUSE filesystem is hung"],
 [("Check the process state and its stack", "ps -o pid,stat,wchan,cmd -p PID && sudo cat /proc/PID/stack"),
  ("See what it is waiting on", "sudo cat /proc/PID/wchan; ls -l /proc/PID/fd | head"),
  ("Check for hung mounts", "mount | grep -E 'nfs|cifs|fuse'"),
  ("Try a forced unmount of the hung filesystem", "sudo umount -f /mnt/hung || sudo umount -l /mnt/hung"),
  ("If a device is dead, only a reboot clears it", "sudo reboot")],
 "D state cannot be interrupted by signals - the process is waiting inside the kernel. Fix or unmount the underlying I/O, or reboot as the last resort."),
("Zombie processes accumulate",
 "The process list shows many defunct entries.",
 ["a parent process is not reaping its children", "a buggy daemon leaks children", "a container's init is missing (PID 1 in containers must reap)"],
 [("Count and list the zombies", "ps aux | awk '$8 ~ /Z/ {print}' | head -20"),
  ("Find the parent that should reap them", "ps -o ppid= -p ZOMBIE_PID"),
  ("Check whether the parent is alive and healthy", "ps -p PARENT_PID -o pid,stat,cmd"),
  ("Restart the parent process to clear the backlog", "sudo systemctl restart the-service"),
  ("In containers, ensure an init reaps children", "docker run --init ...")],
 "Zombies themselves cost almost nothing; the problem is the parent that stopped reaping. Restart it, or give the container an init process."),
("Too many open files or inotify watchers",
 "Applications fail with 'too many open files' or file watchers stop working (editors, sync tools).",
 ["the per-user file descriptor limit is too low", "inotify watch limits are exhausted", "a process is leaking descriptors", "systemd service has its own limit"],
 [("Check current limits", "ulimit -n && cat /proc/sys/fs/inotify/max_user_watches"),
  ("Find who holds the most descriptors", "sudo lsof | awk '{print $1}' | sort | uniq -c | sort -rn | head"),
  ("Raise inotify limits persistently", "echo 'fs.inotify.max_user_watches=524288' | sudo tee /etc/sysctl.d/90-inotify.conf && sudo sysctl --system"),
  ("Raise the user limit in limits.conf", "echo \"$USER soft nofile 65536\" | sudo tee -a /etc/security/limits.d/90-nofile.conf"),
  ("For a service, set LimitNOFILE in the unit", "systemctl edit myservice")],
 "Raise inotify watchers for editors and sync tools; raise nofile for services. Then log out and back in - limits apply at session start."),
("Systemd timer does not fire",
 "A scheduled job never runs, though the timer unit exists.",
 ["the timer is not enabled, only started", "the service it triggers fails instantly", "the schedule expression is wrong", "the timer is waiting on another unit"],
 [("Check the timer's next elapse time", "systemctl list-timers --all | grep -i myjob"),
  ("Check the timer unit itself", "systemctl status myjob.timer --no-pager"),
  ("Check what happens when the service runs", "systemctl status myjob.service --no-pager && journalctl -u myjob.service -n 50"),
  ("Validate the schedule", "systemd-analyze calendar 'Mon *-*-* 03:00:00'"),
  ("Enable it so it survives reboots", "sudo systemctl enable --now myjob.timer")],
 "list-timers shows the next fire time; if it is empty, the timer is not active. Test the service by hand first - a failing service makes a timer look dead."),
("Cron job runs by hand but not from cron",
 "The script works in a terminal yet silently fails when scheduled.",
 ["cron uses a minimal PATH", "the job depends on a shell profile that is not loaded", "output is discarded and errors are invisible", "the user crontab versus system crontab confusion"],
 [("Log the job's real environment", "*/5 * * * * /usr/bin/env > /tmp/cron-env.txt 2>&1"),
  ("Redirect output to a file to see errors", "*/5 * * * * /path/script.sh >> /var/log/script.log 2>&1"),
  ("Use absolute paths for every binary", "grep -E '^[^#]' /etc/crontab ~/cron-check.txt 2>/dev/null"),
  ("Check cron's own log", "journalctl -u cron -n 50 --no-pager  (or grep CRON /var/log/syslog)"),
  ("Test with a minimal environment", "env -i /bin/sh -c '/path/script.sh'")],
 "Cron does not read your shell profile. Use absolute paths, set PATH explicitly at the top of the script, and always redirect output."),
("journald grows without bound",
 "The journal directory keeps growing and the disk fills up.",
 ["persistent journal has no size cap", "a service is logging in a tight loop", "the journal was never vacuumed", "Storage=auto plus a chatty daemon"],
 [("Check the journal's disk usage", "journalctl --disk-usage"),
  ("Find the noisiest unit", "journalctl --since '1 hour ago' -o short | awk '{print $5}' | sort | uniq -c | sort -rn | head"),
  ("Cap the journal size", "sudo mkdir -p /etc/systemd/journald.conf.d && printf '[Journal]\\nSystemMaxUse=500M\\n' | sudo tee /etc/systemd/journald.conf.d/90-size.conf"),
  ("Vacuum immediately", "sudo journalctl --vacuum-size=500M"),
  ("Restart journald to apply the cap", "sudo systemctl restart systemd-journald")],
 "Set SystemMaxUse once and forget it. If one unit is flooding the journal, fix that unit - the cap is a safety net, not a cure."),
("SSH login fails with permission denied",
 "The password or key is correct, yet the server refuses the login.",
 ["key file permissions are too open", "the wrong key is offered first", "server-side AllowUsers or DenyUsers blocks the account", "the account is locked or shell is nologin"],
 [("See which key the client actually offers", "ssh -v user@host 2>&1 | grep -E 'Offering|Authentications'"),
  ("Fix key permissions", "chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_* && chmod 644 ~/.ssh/*.pub"),
  ("Check the server's auth log for the reason", "sudo journalctl -u ssh -n 50 --no-pager"),
  ("Check account state on the server", "sudo passwd -S user && getent passwd user"),
  ("Check sshd's rules", "sudo sshd -T | grep -i -E 'allowusers|denyusers|permitrootlogin|passwordauth'")],
 "Client-side, it is almost always key permissions. Server-side, the sshd log names the exact rule that rejected you - read it, do not guess."),
("Firewall blocks a service that should be reachable",
 "A local service works on localhost but not from other machines.",
 ["the firewall does not allow the port", "the service binds to 127.0.0.1 only", "another rule drops the traffic earlier", "NAT or routing sits in the way"],
 [("Check the firewall state and rules", "sudo ufw status verbose  (or sudo nft list ruleset | head -40)"),
  ("Verify what address the service listens on", "ss -tlnp | grep :8080"),
  ("Test from the machine itself on the external address", "curl -m3 http://192.168.1.10:8080"),
  ("Allow the port explicitly", "sudo ufw allow 8080/tcp"),
  ("Confirm with an external probe", "nc -vz 192.168.1.10 8080")],
 "If the service listens on 127.0.0.1, no firewall change will help - fix the bind address first, then the firewall rule."),
("AppArmor or SELinux denies an application",
 "An app fails with permission errors even though file permissions look right.",
 ["a security profile is blocking a path", "the profile needs updating after an app change", "the denial is only visible in the audit log", "the app writes to an unusual location"],
 [("Check the audit log for denials", "sudo journalctl -k | grep -i -E 'apparmor|denied|avc' | tail -30"),
  ("See the profile status", "sudo aa-status"),
  ("Test with the profile in complain mode", "sudo aa-complain /etc/apparmor.d/usr.bin.app"),
  ("Fix the profile or move the file", "sudo aa-logprof"),
  ("Re-enforce once working", "sudo aa-enforce /etc/apparmor.d/usr.bin.app")],
 "The audit log names the exact path and operation. Adjust the profile rather than disabling security wholesale."),
("Boot fails: kernel module will not load",
 "A module fails to insert; dmesg shows errors like 'invalid module format' or 'unknown symbol'.",
 ["module built for a different kernel version", "Secure Boot rejects unsigned modules", "a dependency module is missing", "the module is blacklisted"],
 [("See the exact error", "sudo dmesg | grep -i -B2 -A5 'module' | tail -30"),
  ("Try loading it manually with verbose output", "sudo modprobe -v module-name"),
  ("Check blacklists", "grep -r module-name /etc/modprobe.d/ /lib/modprobe.d/ 2>/dev/null"),
  ("Check Secure Boot state", "mokutil --sb-state"),
  ("Rebuild out-of-tree modules against the current kernel", "sudo dkms status && sudo dkms autoinstall")],
 "DKMS modules must be rebuilt after every kernel upgrade; Secure Boot requires signing. modprobe -v plus dmesg names the true reason in one line."),
("Bluetooth adapter not found after suspend",
 "Bluetooth works after boot but disappears after a suspend cycle.",
 ["the USB Bluetooth controller is not reset on resume", "the bluetooth service crashed", "firmware reload failed", "kernel quirk needed for the chipset"],
 [("Check the adapter state", "bluetoothctl list && rfkill list"),
  ("Restart the service", "sudo systemctl restart bluetooth"),
  ("Reset the USB device", "echo '1-4' | sudo tee /sys/bus/usb/drivers/usb/unbind; echo '1-4' | sudo tee /sys/bus/usb/drivers/usb/bind"),
  ("Check resume-time firmware errors", "sudo dmesg | grep -i -E 'bluetooth|btusb' | tail -20"),
  ("Persist a workaround via systemd sleep hook if needed", "systemctl cat systemd-suspend.service | head -20")],
 "A service restart usually recovers it; if it recurs, a resume hook that rebinds the USB device is the stable fix."),
("Screen tearing or stuttering video",
 "Motion looks torn on the desktop, or video stutters while the system is idle.",
 ["compositor sync settings are wrong for the driver", "the wrong GPU is driving the display", "a background process spikes I/O or CPU", "the video decoder falls back to software"],
 [("Check which driver and renderer the session uses", "glxinfo | grep -E 'OpenGL renderer|direct rendering'"),
  ("Check the compositor's sync setting", "gsettings get org.gnome.mutter experimental-features"),
  ("Look for background load during playback", "top -b -n1 | head -15"),
  ("Check hardware video decode support", "vainfo | head -20"),
  ("For hybrid graphics, confirm the right GPU is active", "glxinfo | grep -i 'device'")],
 "Tearing is a sync/driver mismatch; stutter is usually background I/O or software decoding. Fix the cause, not the symptom with compositor hacks."),
("Fan runs constantly and the laptop is hot",
 "The fans never stop and the chassis is warm even at idle.",
 ["a runaway process", "thermal throttling from dust or dried paste", "the governor keeps the CPU at max frequency", "a discrete GPU stays powered on"],
 [("Find the top CPU consumers", "ps aux --sort=-%cpu | head -10"),
  ("Check temperatures and frequency", "sensors && grep MHz /proc/cpuinfo | head"),
  ("Check the CPU governor", "cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"),
  ("Check whether the dGPU is asleep", "cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status 2>/dev/null"),
  ("Look for IO wait keeping things busy", "vmstat 1 5")],
 "Software causes (a runaway process, a powered-on dGPU) are fixable in place; persistent heat at true idle is physical maintenance."),
("Battery drains fast and capacity shrank",
 "The laptop no longer reaches its rated runtime and capacity numbers look low.",
 ["background services never sleep", "the discrete GPU stays active", "Wi-Fi power saving is off", "the battery genuinely aged"],
 [("Check power draw and the top offenders", "powertop --time=60  (or upower -d | head -30)"),
  ("Check battery health", "upower -i $(upower -e | grep BAT) | grep -E 'capacity|energy-full|state'"),
  ("Check whether the dGPU sleeps", "cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status 2>/dev/null"),
  ("Enable Wi-Fi power saving", "iw dev wlan0 set power_save on"),
  ("Check suspend inhibitors", "systemd-inhibit --list")],
 "Measure with powertop before changing anything. Aged batteries show low energy-full versus design capacity - that part is hardware."),
("System becomes unresponsive under heavy I/O",
 "The desktop freezes for seconds while large copies run.",
 ["writeback flushes stall the storage device", "the scheduler uses the wrong I/O class for the job", "the storage device itself saturates", "too little RAM for the working set"],
 [("Watch I/O wait and queue depth", "vmstat 1 10 && iostat -x 1 5  (sysstat)"),
  ("Find the process causing it", "sudo iotop -oP"),
  ("Run heavy jobs at idle I/O priority", "ionice -c3 cp bigfile /backup/"),
  ("Check dirty page limits", "sysctl vm.dirty_ratio vm.dirty_background_ratio"),
  ("Consider a lower dirty ratio for desktop feel", "sudo sysctl vm.dirty_background_ratio=5")],
 "Stutter under I/O is a queueing problem: lower the dirty ratios and run bulk work with ionice -c3 so interactive apps stay responsive."),
("Time skew breaks TLS or authentication",
 "HTTPS fails with certificate errors, or Kerberos-style auth rejects you, even though networking is fine.",
 ["the system clock is off by more than a few minutes", "NTP is blocked by a firewall", "the RTC battery died", "a VM clock desyncs after snapshots"],
 [("Check the clock and sync state", "date -u && timedatectl"),
  ("Check reachability of NTP servers", "chronyc tracking  (or systemctl status systemd-timesyncd)"),
  ("Force a correction", "sudo systemctl restart systemd-timesyncd"),
  ("For VMs, re-sync after resume or snapshot restore", "sudo hwclock --hctosys"),
  ("Verify against an external source", "curl -sI https://example.com | grep -i date")],
 "TLS will not tolerate a wrong clock. Fix time sync first, and in VMs make the guest agent responsible for the clock."),
("Filesystem is read-only and remount fails",
 "A filesystem unexpectedly became read-only; remounting read-write refuses.",
 ["the kernel remounted it read-only after an error", "the device has failed", "the journal needs replay via fsck", "LVM or md layer is degraded"],
 [("See why the kernel remounted it", "sudo dmesg | grep -i -E 'remount|read-only|ext4|xfs' | tail -30"),
  ("Check the array or volume health", "cat /proc/mdstat; sudo lvs"),
  ("Check and repair offline", "sudo umount /data && sudo fsck -f /dev/mapper/vg-data"),
  ("After repair, remount and verify", "sudo mount -a && findmnt /data"),
  ("If the device is failing, migrate data first", "sudo ddrescue /dev/sdb1 /dev/sdc1 rescue.log")],
 "Read-only remount is the kernel protecting your data. Repair the filesystem before writing anything else to it."),
("Docker container exits immediately",
 "A container starts and dies in seconds with exit code 0 or 1.",
 ["the main process finished (a shell with no tty, a one-shot command)", "the entrypoint script errors out", "a required volume or env var is missing", "the container cannot write to its working directory"],
 [("See the exit code and logs", "docker ps -a | head && docker logs CONTAINER"),
  ("Run it interactively to watch the failure", "docker run --rm -it IMAGE sh"),
  ("Check the entrypoint and command", "docker inspect IMAGE --format '{{.Config.Entrypoint}} {{.Config.Cmd}}'"),
  ("Check mounts and permissions", "docker inspect CONTAINER --format '{{json .Mounts}}'"),
  ("Verify the image architecture matches", "docker inspect IMAGE --format '{{.Architecture}}'")],
 "Containers live only as long as their main process. If the entrypoint exits, the container exits - debug the process, not Docker."),
("Docker uses too much disk space",
 "The disk fills up with images, layers and volumes.",
 ["dangling images and build cache accumulate", "stopped containers keep their writable layers", "volumes from removed containers are orphaned", "logs grow without a cap"],
 [("See where the space goes", "docker system df -v | head -30"),
  ("Prune safely step by step", "docker container prune && docker image prune"),
  ("Remove build cache", "docker builder prune"),
  ("Find orphaned volumes before deleting", "docker volume ls -f dangling=true"),
  ("Cap container log sizes", "printf '{\"log-driver\":\"json-file\",\"log-opts\":{\"max-size\":\"10m\",\"max-file\":\"3\"}}' | sudo tee /etc/docker/daemon.json")],
 "Prune in order (containers, images, cache, volumes) and cap log growth - logs are the silent disk eater in long-running hosts."),
("Network interface has no IP address",
 "The interface is up but has no address, or DHCP never completes.",
 ["the DHCP client failed", "the interface is administratively down", "a duplicate address or profile conflict", "the driver loaded but the link never came up"],
 [("Check the interface state", "ip -br addr && ip -br link"),
  ("Bring it up and re-request DHCP", "sudo ip link set eth0 up && sudo dhclient -v eth0"),
  ("Check NetworkManager's view", "nmcli device status"),
  ("Watch the DHCP conversation", "sudo journalctl -u NetworkManager -f"),
  ("Check for duplicate profiles on the interface", "nmcli -f NAME,DEVICE connection show")],
 "ip -br link shows carrier state first; no carrier is a cable or switch problem, carrier with no IP is a DHCP or profile problem."),
("VPN connects but nothing routes",
 "The VPN tunnel is up, yet no traffic passes or DNS breaks.",
 ["the default route still points at the physical gateway", "DNS is not updated for the tunnel", "the firewall blocks the tunnel interface", "split-tunnel configuration is wrong"],
 [("Check the routing table", "ip route show"),
  ("Check DNS per interface", "resolvectl status | grep -A5 -i tun"),
  ("Check the tunnel interface state", "ip -br addr show tun0"),
  ("Verify traffic actually exits the tunnel", "curl --interface tun0 -sI https://ifconfig.me"),
  ("Check firewall rules for the tunnel", "sudo nft list ruleset | grep -i tun | head")],
 "Routing and DNS must both follow the tunnel. If the default route stayed behind, the VPN client's route management is misconfigured."),
("Sound crackles or stutters under load",
 "Audio pops when the CPU is busy or during heavy I/O.",
 ["the audio buffer is too small for the load", "CPU frequency scaling causes timing jitter", "a real-time priority is missing for the audio thread", "the USB audio device shares a saturated bus"],
 [("Check for xruns in the audio server", "journalctl --user -u pipewire -n 50 | grep -i xrun"),
  ("Check the quantum and sample rate settings", "pw-metadata -n settings"),
  ("Raise the quantum for stability", "pw-metadata -n settings 0 clock.force-quantum 1024"),
  ("Check whether the CPU is throttling", "grep MHz /proc/cpuinfo | head"),
  ("Check real-time priority limits for the user", "ulimit -r && cat /etc/security/limits.d/audio.conf 2>/dev/null")],
 "Crackling under load is a buffering problem: a larger quantum trades a little latency for stability. Then confirm the audio threads get real-time priority."),
("GRUB shows wrong entries or misses the new kernel",
 "The boot menu lists stale kernels, or a freshly installed kernel is absent.",
 ["os-prober found ghosts", "grub.cfg was not regenerated", "the ESP is not mounted when updating", "boot order points to the wrong loader"],
 [("Regenerate the configuration", "sudo update-grub"),
  ("Check the ESP mount and space", "findmnt /boot/efi && df -h /boot/efi"),
  ("List installed kernels", "dpkg -l 'linux-image-*' | grep ^ii"),
  ("Check the EFI boot order", "sudo efibootmgr -v"),
  ("Remove a stale kernel cleanly", "sudo apt purge linux-image-OLD-version")],
 "update-grub with the ESP mounted fixes most cases; keep at least two kernels installed so a bad update is always recoverable."),
("Lock screen or login loop after an update",
 "The password is correct but the session returns to the login screen instantly.",
 ["the session fails to start (bad extension, broken config)", "home directory is full or unwritable", "Wayland/X11 session type fails", "the GPU driver broke the compositor"],
 [("Check free space and home ownership", "df -h ~ && ls -ld ~ && ls -la ~ | head"),
  ("Read the session's errors", "journalctl -b -u gdm -n 80 --no-pager"),
  ("Try the other session type from the login screen", "gear icon: switch Wayland/X11"),
  ("Move suspicious user config aside", "mv ~/.config ~/.config.bak  (test login, then restore selectively)"),
  ("Check .Xauthority ownership", "ls -l ~/.Xauthority")],
 "A full home directory or a broken session config is the usual cause. Moving .config aside is the fastest isolation test."),
("Clock, keyboard or brightness keys stop working",
 "Function keys do nothing after an update.",
 ["the function-key driver module is missing", "the daemon handling keys crashed", "ACPI events changed with a firmware update", "the session lost the key mapping"],
 [("Check the key events reach the system", "sudo showkey -k  (or evtest)"),
  ("Check the hotkey daemon", "systemctl status power-profiles-daemon 2>/dev/null; pgrep -a -f 'hotkey|power|acpi'"),
  ("Read ACPI events as you press keys", "sudo acpi_listen"),
  ("Check the kernel's view", "sudo dmesg | grep -i -E 'acpi|wmi|hotkey' | tail -20"),
  ("Reinstall the vendor module if needed", "lsmod | grep -i wmi")],
 "If showkey sees the key, it is software mapping; if not, it is firmware or the module. That split decides where to look."),
("File transfer over the network is slow",
 "scp, rsync or SMB moves data far slower than the link should allow.",
 ["a duplex mismatch or bad cable", "encryption overhead with a slow CPU", "many small files instead of few large ones", "the remote disk is the bottleneck"],
 [("Measure the raw link first", "iperf3 -c server  (or curl -o /dev/null http://server/bigfile)"),
  ("Check the NIC's negotiated speed", "ethtool eth0 | grep -E 'Speed|Duplex'"),
  ("Use rsync with compression off on fast links", "rsync -a --info=progress2 src/ host:/dst/"),
  ("Archive many small files into one stream", "tar -cf - dir/ | ssh host 'tar -xf - -C /dst'"),
  ("Check the destination disk speed", "ssh host 'dd if=/dev/zero of=/tmp/test bs=1M count=500 oflag=direct'")],
 "Measure the link before blaming the tool; a 100Mb link or a busy remote disk caps everything regardless of software."),
("Log files explode and fill the disk",
 "A log directory grows to gigabytes within hours.",
 ["a service logs in a crash loop", "debug logging was left on", "no rotation is configured", "a script prints per-request lines"],
 [("Find the biggest and fastest-growing logs", "sudo du -ah /var/log | sort -h | tail -15"),
  ("Check what writes the most right now", "sudo lsof +D /var/log | head -20"),
  ("Read the tail of the offender", "sudo tail -50 /var/log/huge.log"),
  ("Set up rotation", "printf '/var/log/huge.log {\\n  daily\\n  rotate 7\\n  size 50M\\n  compress\\n}\\n' | sudo tee /etc/logrotate.d/huge"),
  ("Cap it immediately if the disk is critical", "sudo truncate -s 0 /var/log/huge.log")],
 "Truncate to survive tonight, then fix the cause: a crash-looping service or debug logging left enabled."),
("Text looks garbled in the terminal or files",
 "Accented characters show as boxes or question marks.",
 ["the locale is not UTF-8", "the terminal emulator uses a non-UTF-8 encoding", "a font lacks the needed glyphs", "SSH forwards a broken locale"],
 [("Check the locale and encoding", "locale && echo $TERM"),
  ("Check the file's actual encoding", "file -i suspicious.txt"),
  ("Convert legacy encodings", "iconv -f ISO-8859-1 -t UTF-8 legacy.txt -o fixed.txt"),
  ("Verify terminal encoding", "locale charmap"),
  ("Reconfigure locales if incomplete", "sudo dpkg-reconfigure locales")],
 "UTF-8 everywhere is the target. Convert legacy files with iconv rather than changing the whole system locale."),
("Kernel panic or sudden reboot under load",
 "The machine hard-reboots with no shutdown sequence when stressed.",
 ["unstable RAM or overclock", "power supply insufficient under GPU load", "CPU thermal shutdown", "a kernel bug triggered by a driver"],
 [("Check for thermal shutdown messages", "journalctl -k -b -1 | grep -i -E 'thermal|critical' | tail -20"),
  ("Check machine-check or hardware errors", "journalctl -k -b -1 | grep -i -E 'mce|hardware error' | tail -20"),
  ("Test memory", "sudo memtester 2G 1  (or memtest86+ from GRUB)"),
  ("Check power draw headroom under load", "sudo powertop --time=30"),
  ("Update firmware and microcode", "sudo fwupdmgr update 2>/dev/null; grep microcode /proc/cpuinfo | head -1")],
 "Sudden reboots under load point at power, thermals or RAM - not software. Check the previous boot's log for the last words before death."),
("Screen resolution or scaling is wrong",
 "Everything is tiny, huge, or the native resolution is not offered.",
 ["the display's EDID was not read", "fractional scaling is disabled", "the wrong output is primary", "Wayland/X11 scaling behaves differently"],
 [("List outputs and available modes", "wlr-randr  (Wayland)  /  xrandr  (X11)"),
  ("Set resolution manually as a test", "xrandr --output HDMI-1 --mode 2560x1440"),
  ("Enable fractional scaling on GNOME", "gsettings set org.gnome.mutter experimental-features \"['scale-monitor-framebuffer']\""),
  ("Set per-monitor scale", "gsettings set org.gnome.desktop.interface text-scaling-factor 1.25"),
  ("Check EDID reading when a mode is missing", "sudo dmesg | grep -i edid | tail")],
 "Missing modes are usually EDID problems; tiny or huge UI is a scaling setting. Fix scaling at the session level, not per app."),
("Microphone is silent or noisy",
 "Recording apps capture silence, or audio is full of hiss.",
 ["the input source is muted at the ALSA level", "the wrong input device is default", "gain is too high causing clipping", "privacy mute switch engaged"],
 [("List sources and check mute state", "pactl list short sources"),
  ("Check and unmute at the hardware level", "alsamixer -c 0"),
  ("Set the default source", "pactl set-default-source alsa_input.pci-0000_00_1f.3.analog-stereo"),
  ("Test with a raw recording", "arecord -f cd -d 5 /tmp/test.wav && aplay /tmp/test.wav"),
  ("Check for a hardware mute key state", "sudo dmesg | grep -i -E 'mic|mute' | tail")],
 "arecord bypasses the desktop stack - if it works, the problem is in PipeWire routing, not the hardware."),
("Second monitor is not detected",
 "An external display shows nothing when plugged in.",
 ["the cable or adapter is charge-only", "the output is disabled in software", "the dock's firmware mangles the EDID", "the GPU driver fails on hotplug"],
 [("Check the kernel sees a hotplug event", "sudo dmesg -w  (plug the cable, watch for output)"),
  ("List outputs and their states", "xrandr --query  /  wlr-randr"),
  ("Force-enable a disabled output", "xrandr --output HDMI-1 --auto"),
  ("Check the dock's USB identity", "lsusb | grep -i -E 'dock|displaylink'"),
  ("Check the GPU's connector state", "cat /sys/class/drm/card*/status")],
 "If the kernel never logs a hotplug, the problem is physical or the dock. If it does, the compositor or driver needs the output enabled."),
("Random freezes with no log entry",
 "The system locks up completely, leaving nothing in the logs.",
 ["memory errors that do not reach the log", "storage controller hangs", "GPU driver deadlock", "CPU errata or firmware bug"],
 [("Enable persistent logging for the next event", "sudo mkdir -p /var/log/journal && sudo systemd-journald"),
  ("Set up kdump or pstore for crash capture", "systemctl status kdump-tools 2>/dev/null; ls /sys/fs/pstore/ 2>/dev/null"),
  ("Test RAM thoroughly", "memtest86+ from the boot menu, at least one full pass"),
  ("Check firmware and microcode versions", "sudo fwupdmgr get-devices 2>/dev/null | head -20"),
  ("Watch temperatures and voltages under load", "sensors -f && watch -n2 sensors")],
 "Total freezes without logs are usually hardware or firmware. pstore plus a RAM test is the fastest way to narrow it."),
("Terminal command not found after installing",
 "A freshly installed tool cannot be found, though the package installed fine.",
 ["the binary is outside PATH", "the shell's command hash is stale", "the package installed to a versioned path", "the tool needs a login shell to pick up new PATH"],
 [("Find where the binary actually is", "which -a tool; find /usr /opt ~/.local -name tool -type f 2>/dev/null | head"),
  ("Check PATH and the shell hash", "echo $PATH; hash -r"),
  ("Check whether it is a login-shell profile issue", "bash -lc 'which tool'"),
  ("Add the right directory to PATH persistently", "echo 'export PATH=\"$HOME/.local/bin:$PATH\"' >> ~/.profile"),
  ("Verify the package's file list", "dpkg -L package-name | grep bin")],
 "hash -r fixes the current shell; a PATH line in ~/.profile fixes future ones. Never copy binaries into /usr/bin by hand."),
("System clock is wrong only in dual-boot",
 "Windows and Linux disagree about the time by hours.",
 ["Windows writes the RTC in local time, Linux expects UTC", "timezone settings differ between the systems"],
 [("Check how Linux treats the RTC", "timedatectl | grep -i rtc"),
  ("Tell Linux to store local time in the RTC", "timedatectl set-local-rtc 1 --adjust-system-clock"),
  ("Or fix it on the Windows side with a registry setting", "reg add \"HKLM\\System\\CurrentControlSet\\Control\\TimeZoneInformation\" /v RealTimeIsUniversal /t REG_DWORD /d 1"),
  ("Verify both systems agree after a reboot", "date && timedatectl")],
 "Best practice is UTC in the RTC everywhere; the Windows registry key achieves that without changing Linux."),
]
