SCENARIOS = [
("A systemd service will not start",
 "The service fails, restarts in a loop, or shows 'failed' after start.",
 ["the unit file has an error", "the service user or file permissions are wrong", "a dependency is missing or failed", "the port is already in use", "an environment variable the service expects is not set"],
 [("Check the service state and the exact error line", "systemctl status myapp.service"),
  ("Read the service's own log, newest first", "journalctl -u myapp.service -n 100 --no-pager"),
  ("See which other units failed around the same time", "systemctl --failed"),
  ("Validate the unit file for syntax mistakes", "systemd-analyze verify /etc/systemd/system/myapp.service"),
  ("After editing the unit file, reload and retry", "sudo systemctl daemon-reload && sudo systemctl restart myapp.service"),
  ("If the port is the problem, find who owns it", "ss -tlnp | grep :8080")],
 "Fix the root cause named in the log (permissions, config, port), then daemon-reload and restart. If a dependency keeps it down, check that unit too."),
("Disk is full but nothing obvious is large",
 "df shows 100% usage, yet du does not find the space.",
 ["deleted files still held open by a process", "a mount is shadowing files (files under a mount point)", "filesystem reserved blocks for root", "inode exhaustion (df -i), not block exhaustion"],
 [("Confirm which filesystem is actually full", "df -hT"),
  ("Check inode usage too - full inodes break things with free space", "df -i"),
  ("Find deleted-but-open files; the (deleted) marker is the giveaway", "sudo lsof -nP | grep '(deleted)'"),
  ("Restart the process holding the big deleted file, or truncate it", "sudo systemctl restart the-service"),
  ("Compare df with du on the same mount to spot shadowed files", "du -xsh /var/* | sort -h | tail")],
 "Restarting (or truncating) the process that holds deleted files returns the space. If df and du disagree on the same mount, look for files hidden under a mount point."),
("High CPU usage with no obvious culprit",
 "Fans spin up, the system feels slow, load average climbs.",
 ["a runaway process", "a stuck kernel thread or IO wait", "thermal throttling", "cron or backup jobs overlapping", "a crypto miner or other unwanted process"],
 [("Get the top CPU consumers, worst first", "ps aux --sort=-%cpu | head -15"),
  ("Check whether the load is CPU or IO wait", "vmstat 1 5"),
  ("Look at per-core usage to spot a single-threaded hog", "mpstat -P ALL 1 3"),
  ("Check temperatures - throttling looks like slowness", "sensors"),
  ("If IO-bound, find the busiest disk", "iostat -xz 1 5"),
  ("Identify the exact threads of a process if needed", "top -H -p PID")],
 "Handle the specific process: renice it, fix its bug, or kill it. If it is IO wait, the problem is the disk, not the CPU."),
("No internet connection",
 "Websites do not load; ping may or may not work.",
 ["cable or Wi-Fi association problem", "no IP address from DHCP", "bad DNS", "wrong default route", "firewall blocking", "the upstream router is down"],
 [("Check the interface state and addresses", "ip -br a"),
  ("If the interface is down, bring it up", "sudo ip link set eth0 up"),
  ("Check the default route exists", "ip route"),
  ("Ping the gateway, then a public IP (1.1.1.1) - this separates routing from DNS", "ping -c3 $(ip route | awk '/default/{print $3; exit}') && ping -c3 1.1.1.1"),
  ("If IPs work but names do not, it is DNS", "resolvectl status && dig +short example.com"),
  ("For Wi-Fi specifically, rescan and reconnect", "nmcli dev wifi list && nmcli dev wifi connect SSID password PASS"),
  ("Check the firewall is not eating the traffic", "sudo ufw status verbose")],
 "Fix at the layer that failed: association, DHCP, route, DNS or firewall. ping by IP working while names fail always means DNS."),
("'Permission denied' when accessing a file",
 "Reading, writing or executing a file or directory fails with Permission denied.",
 ["missing execute bit on a parent directory", "wrong owner or group", "an ACL is restricting access", "SELinux/AppArmor denial", "the file is immutable", "noexec mount option"],
 [("Look at the permissions of the file and every parent directory", "namei -l /path/to/file"),
  ("Check your identity and groups - maybe the group changed", "id"),
  ("Check for ACLs (the + sign in ls -l)", "getfacl /path/to/file"),
  ("Check for immutable or append-only attributes", "lsattr /path/to/file"),
  ("If it looks correct but still fails, check the audit log", "sudo journalctl -xe | tail -40"),
  ("Fix the owner or mode as needed", "sudo chown user:group /path && chmod 644 /path/file")],
 "Grant the access that is actually missing: chmod on the file or chmod +x on the parent directories, chown to the right owner, or remove the ACL/attribute that blocks you."),
("Application crashes at startup",
 "The app exits immediately, shows a flash, or dies without a window.",
 ["a missing shared library", "bad configuration file", "wrong permissions", "a stale lock file", "an incompatible driver or display backend"],
 [("Run it from a terminal to see the real error text", "./app"),
  ("Ask the loader which libraries are missing", "ldd ./app | grep 'not found'"),
  ("Trace which file it fails to open", "strace -f -e trace=openat ./app 2>&1 | grep -E 'ENOENT|EACCES' | tail -20"),
  ("Check its own logs and the journal", "journalctl --user -n 50 --no-pager"),
  ("If it is a GUI app, check the session type and backend", "echo $XDG_SESSION_TYPE $WAYLAND_DISPLAY $DISPLAY"),
  ("Try the other display backend", "GDK_BACKEND=x11 ./app")],
 "Install the missing library, fix the config or permission the trace named, or switch the display backend. The first ENOENT or EACCES in the trace is almost always the answer."),
("Boot hangs or drops to a black screen",
 "The machine powers on but never reaches the login screen.",
 ["a failing systemd unit in the boot chain", "a broken graphics driver", "a corrupted filesystem", "bad kernel parameters", "disk failure"],
 [("At the GRUB menu, boot with 'quiet splash' removed to see messages", "edit the boot entry: remove quiet splash, add nomodeset (Intel/AMD) or blacklist vendor drivers"),
  ("From a TTY or recovery shell, list failed units", "systemctl --failed"),
  ("Read the previous boot's log", "journalctl -b -1 -p err --no-pager"),
  ("Analyze what actually slowed or broke the boot", "systemd-analyze critical-chain"),
  ("Check the filesystem if errors are suspected", "sudo fsck -f /dev/nvme0n1p2"),
  ("Check disk health", "sudo smartctl -a /dev/nvme0n1")],
 "Fix the unit that failed, the driver that panicked, or the filesystem that is corrupt. Safe Mode (vendor driver blacklist) is the standard escape hatch for GPU-related black screens."),
("Slow boot",
 "The system takes minutes to reach the desktop.",
 ["a blocking service waiting on network or a timeout", "a slow mount (network share, bad fstab entry)", "a huge initramfs rebuild", "disk at 100% during boot", "too many autostart applications"],
 [("See the total boot time and the slowest units", "systemd-analyze blame | head -20"),
  ("See the critical chain - what actually gated the boot", "systemd-analyze critical-chain"),
  ("Check for mount timeouts in the journal", "journalctl -b | grep -iE 'timed out|timeout|dependency failed'"),
  ("List autostart programs", "ls ~/.config/autostart /etc/xdg/autostart"),
  ("Check fstab for entries that may hang (network mounts)", "cat /etc/fstab")],
 "Mask or fix the slow unit, add noauto/x-systemd.device-timeout to network mounts, and trim autostart apps. critical-chain shows the chain that actually matters."),
("Wi-Fi keeps dropping",
 "The connection works, then disappears or degrades.",
 ["power saving on the Wi-Fi card", "weak signal or channel congestion", "driver problems", "NetworkManager retry loops", "wrong regulatory domain"],
 [("Check the signal quality and current link", "nmcli dev wifi list --rescan yes"),
  ("Look at recent disconnect reasons in the log", "journalctl -u NetworkManager -n 80 --no-pager"),
  ("Check whether power saving is on (common cause of drops)", "iw dev wlan0 get power_save"),
  ("Turn it off and test", "sudo iw dev wlan0 set power_save off"),
  ("Check the driver in use", "lspci -k | grep -A3 -i network")],
 "Disable power saving persistently (NetworkManager wifi.powersave=2), pick a less crowded channel, or update the driver. Persistent drops with power_save on are a classic."),
("Audio stopped working",
 "No sound, wrong device, or crackling audio.",
 ["the wrong default sink is selected", "PipeWire/PulseAudio service is down", "the device is muted at ALSA level", "an app holds the device exclusively", "missing firmware or codec"],
 [("List outputs and check which is default", "pactl list short sinks && pactl info | grep 'Default Sink'"),
  ("Check and unmute ALSA master controls", "alsamixer -c0"),
  ("Check the audio services", "systemctl --user status pipewire pipewire-pulse wireplumber --no-pager"),
  ("Restart the user audio stack", "systemctl --user restart pipewire pipewire-pulse wireplumber"),
  ("See if an app holds the device", "fuser -v /dev/snd/* 2>/dev/null"),
  ("Check firmware/kernel messages for the card", "dmesg | grep -iE 'snd|audio|firmware' | tail -20")],
 "Select the right sink, unmute at both ALSA and PipeWire level, or restart the user audio services. If the card is missing entirely, it is a firmware/driver problem."),
("Out of memory: the OOM killer strikes",
 "Apps get killed randomly, especially under load.",
 ["a memory leak", "too many browser tabs or VMs", "no or too small swap", "cgroup limits hit", "a runaway process"],
 [("Check current memory and swap", "free -h"),
  ("Confirm who got killed and why", "dmesg -T | grep -i 'killed process' | tail"),
  ("Find the biggest memory consumers", "ps aux --sort=-%mem | head -15"),
  ("Watch memory live to catch the growth", "watch -n2 'free -h'"),
  ("Check for a process slowly leaking", "ps -o pid,rss,etime,cmd -C firefox")],
 "Kill or fix the leaking process, add swap as a buffer, and set a systemd MemoryMax= limit on the offender so it dies instead of the whole desktop."),
("Cannot delete a file",
 "rm says Permission denied or Operation not permitted even as root.",
 ["immutable or append-only attribute set", "the directory (not the file) lacks write permission", "the file is a mount point", "an open handle from a container or process", "filesystem is read-only (errors detected)"],
 [("Check attributes", "lsattr /path/to/file"),
  ("Remove the immutable flag if present", "sudo chattr -i /path/to/file"),
  ("Check the directory permissions", "ls -ld $(dirname /path/to/file)"),
  ("Check whether the filesystem went read-only after errors", "mount | grep ' / '"),
  ("Check for open handles", "sudo lsof /path/to/file")],
 "Clear the attribute, fix the directory mode, or remount rw after fixing the underlying disk problem. A filesystem that remounts itself read-only means errors - check dmesg."),
("SSH connection refused or times out",
 "ssh exits with 'Connection refused' or hangs.",
 ["sshd is not running or not listening on that port", "firewall blocks the port", "wrong port or host", "host key changed (man-in-the-middle warning)", "DNS resolves to the wrong host"],
 [("Check the service on the server", "systemctl status ssh"),
  ("Check what it listens on", "ss -tlnp | grep ssh"),
  ("From the client, test the port reachability", "nc -vz host 22"),
  ("Check the client's verbose handshake", "ssh -vvv user@host 2>&1 | tail -30"),
  ("Check the server firewall", "sudo ufw status verbose"),
  ("If the host key changed after a rebuild, update known_hosts", "ssh-keygen -R host")],
 "'Connection refused' = nothing listening (start sshd / fix port). Timeout = firewall or routing. Host key warnings after a reinstall are expected - remove the old key."),
("Cron job does not run",
 "The scheduled job never fires, or fires with errors.",
 ["cron service is not running", "wrong crontab syntax or time fields", "the command needs a PATH or environment cron does not have", "output errors are silently mailed", "the script lacks the execute bit"],
 [("Check cron itself", "systemctl status cron"),
  ("List the user's jobs", "crontab -l"),
  ("Check the system log for cron executions", "journalctl -u cron -n 50 --no-pager"),
  ("Test the exact command as the same user", "run the command manually with env -i"),
  ("Use absolute paths for everything inside the job", "which python3 && crontab -l")],
 "Fix the schedule, use absolute paths, redirect output to a log file so you can see errors, and remember cron has a minimal environment."),
("Website returns 502 Bad Gateway (nginx + app server)",
 "Nginx serves static files but proxied routes fail.",
 ["the backend app is down or crashed", "wrong upstream port or socket", "backend is too slow and nginx times out", "permissions on a unix socket", "backend listening on the wrong interface"],
 [("Check the nginx error log for the exact upstream error", "tail -50 /var/log/nginx/error.log"),
  ("Check the backend service", "systemctl status myapp"),
  ("Check the backend is really listening", "ss -tlnp | grep -E '8080|9000'"),
  ("Test the backend directly, bypassing nginx", "curl -sv http://127.0.0.1:8080/health"),
  ("Check nginx config for the proxy target", "nginx -T | grep -A5 proxy_pass"),
  ("Reload nginx after config fixes", "sudo nginx -t && sudo systemctl reload nginx")],
 "Bring the backend up, point the proxy at the right port, or raise proxy timeouts. The nginx error log names the failing upstream and the reason."),
("The clock is wrong",
 "Times in logs are off; HTTPS or apt fails with certificate errors.",
 ["wrong timezone", "NTP not running or blocked", "hardware clock wrong", "dual-boot Windows setting the RTC to local time"],
 [("Check the current time settings", "timedatectl"),
  ("Enable NTP sync", "sudo timedatectl set-ntp true"),
  ("Force a one-shot sync", "sudo chronyc makestep (or: sudo systemctl restart systemd-timesyncd)"),
  ("Set the right timezone if needed", "sudo timedatectl set-timezone REGION/CITY"),
  ("Check the hardware clock mode if dual-booting", "timedatectl | grep RTC")],
 "Turn on NTP and pick the correct timezone. Certificate errors that appear suddenly are usually a clock that drifted by minutes or more."),
("USB drive is not detected",
 "Plugging in a USB stick or disk does nothing.",
 ["the port or cable is bad", "kernel refused the device", "filesystem unsupported (exFAT/NTFS without packages)", "the device needs a different mode (USB modeswitch)", "power draw too high for the port"],
 [("Watch the kernel as you plug it in", "dmesg -w  (plug the device, watch the lines)"),
  ("List USB devices to confirm it enumerated", "lsusb"),
  ("List block devices to see if a disk appeared", "lsblk -f"),
  ("Check for filesystem support messages", "dmesg -T | grep -iE 'exfat|ntfs|sdb' | tail"),
  ("Try another port and cable", "physical swap - no command for this one")],
 "If lsusb shows it but lsblk does not, it is a storage/mode problem. If it appears in lsblk, mount it (or install exfatprogs/ntfs-3g for the filesystem)."),
("Filesystem errors after a power loss",
 "The system boots read-only, or shows I/O errors and fsck messages.",
 ["unsynced writes at power loss", "failing disk", "loose cable on a desktop drive", "BTRFS needs a scrub after errors"],
 [("Check the kernel log for the exact errors", "dmesg -T | grep -iE 'error|I/O|ext4|btrfs' | tail -30"),
  ("Check the filesystem state", "sudo tune2fs -l /dev/sda2 | grep -i state"),
  ("Run a check from a live environment or unmounted system", "sudo fsck -f /dev/sda2"),
  ("For BTRFS, check the device stats and scrub", "sudo btrfs device stats / && sudo btrfs scrub start /"),
  ("Check the disk's SMART health", "sudo smartctl -H /dev/sda")],
 "Repair the filesystem once, then look for the real cause: SMART errors mean replace the disk; repeated corruption on a healthy disk means cables or power."),
("Pacman says the package is already installed but the binary is missing",
 "apt/dpkg reports a package as installed, yet the file is absent.",
 ["files were deleted manually", "a partial upgrade left the package half-configured", "the file is in a different package", "dpkg database and filesystem disagree"],
 [("Ask dpkg which package owns the path", "dpkg -S /usr/bin/missing-tool"),
  ("Reinstall the owning package", "sudo apt install --reinstall PACKAGE"),
  ("Fix any half-configured packages", "sudo dpkg --configure -a && sudo apt-get -f install"),
  ("Verify the package's file list", "dpkg -L PACKAGE | head -30")],
 "Reinstall the package; if apt refuses, fix the dpkg state first with --configure -a and -f install."),
("Keyboard or language layout is wrong",
 "Typed characters do not match the keys, or the layout resets.",
 ["wrong X11/Wayland layout", "console keymap differs from desktop layout", "two layouts installed and the switch key was hit", "locale not generated"],
 [("Check current layout settings", "localectl status"),
  ("List configured layouts", "gsettings get org.gnome.desktop.input-sources sources"),
  ("Set the console keymap", "sudo localectl set-keymap us"),
  ("Set the desktop layout", "gsettings set org.gnome.desktop.input-sources sources \"[('xkb', 'us')]\""),
  ("Check locale generation", "locale -a | head")],
 "Set the layout at both levels (console and desktop), and generate the locale if programs complain about LC_ALL/LANG."),
("Program is extremely slow, disk is fine",
 "An application takes seconds to respond; no obvious load.",
 ["it is swapping", "waiting on a network resource with a timeout", "blocking DNS lookups", "lock contention", "profiling needed"],
 [("Check for swap activity", "vmstat 1 5"),
  ("Watch the process state - D state means IO wait", "ps -o pid,stat,wchan,cmd -p PID"),
  ("Check what it is doing with the kernel", "sudo strace -p PID -c"),
  ("Check its file descriptors and sockets", "sudo lsof -p PID | tail -20"),
  ("Profile where the time goes", "sudo perf top -p PID")],
 "Swapping: add memory or reduce the workload. D-state on network: fix the remote or timeout. The strace -c summary usually names the blocking syscall."),
("The desktop session crashes back to the login screen",
 "GNOME logs out spontaneously or on certain actions.",
 ["a GPU driver crash", "an out-of-memory kill", "a broken extension", "a full home partition", "session files corrupted"],
 [("Check the previous session's crash in the journal", "journalctl -b -1 -p err --no-pager | tail -50"),
  ("Check for OOM kills around the logout time", "journalctl -b | grep -iE 'oom|killed' | tail"),
  ("Check disk space in home", "df -h ~"),
  ("Disable extensions and test", "gnome-extensions list --enabled"),
  ("Check GPU driver errors", "journalctl -b | grep -iE 'gpu|drm|nvidia|amdgpu' | tail -30")],
 "Fix the named cause: free space, disable the crashing extension, update/rollback the GPU driver, or add memory. The journal almost always contains the exact reason at the logout moment."),
("apt upgrade fails with unmet dependencies",
 "Install/upgrade stops with 'held broken packages'.",
 ["mixed repositories or wrong release codename", "a package pinned by apt preferences", "third-party repo out of sync", "interrupted previous dpkg run"],
 [("Fix any interrupted dpkg state first", "sudo dpkg --configure -a"),
  ("Try to repair dependencies", "sudo apt-get -f install"),
  ("See why the package cannot move (held/pinned)", "apt-cache policy PACKAGE"),
  ("Check for pins and preferences files", "ls /etc/apt/preferences.d/ && cat /etc/apt/sources.list"),
  ("Refresh lists and retry with details", "sudo apt update && sudo apt full-upgrade")],
 "Repair dpkg state, remove the offending pin or repo, and retry. Never force with --force-* unless you fully understand the consequence."),
("Battery drains very fast",
 "Laptop battery life far below expectation.",
 ["a runaway process", "GPU stuck on discrete mode", "screen brightness and radio usage", "background indexing or backup", "a kernel/driver regression"],
 [("Find processes waking the CPU most", "sudo powertop (or: top -b -n1 | head)"),
  ("Check what is using power right now", "sudo powertop --time=30"),
  ("Check GPU state and whether the dGPU is idle", "nvidia-smi  (or: cat /sys/class/drm/card*/device/power_state)"),
  ("Check for blocked suspend states", "systemd-analyze --no-pager 2>/dev/null; cat /sys/power/state"),
  ("Check disk activity", "iostat -x 5 3")],
 "Kill or fix the busy process, force the dGPU to sleep (prime-select/ envycontrol), and re-test. powertop's tunables list is the fastest inventory of waste."),
("Zombie processes accumulate",
 "ps shows many defunct processes.",
 ["a parent process is not reaping children", "a bug in a long-running daemon", "an init mismatch in containers"],
 [("List zombies and their parents", "ps -eo pid,ppid,stat,cmd | awk '$3 ~ /Z/'"),
  ("Identify the parent that must reap them", "ps -o pid,cmd -p PPID"),
  ("If the parent is a service, restart it", "sudo systemctl restart the-parent"),
  ("If the parent is gone, the zombies are reparented and will clear", "ps -eo pid,ppid,stat,cmd | awk '$3 ~ /Z/'")],
 "Zombies themselves cost almost nothing; the bug is in the parent that does not reap. Restart the parent, and file the bug there."),
("Wi-Fi adapter not found after kernel update",
 "No wireless interface appears after upgrading the kernel.",
 ["out-of-tree driver (dkms) not rebuilt for the new kernel", "firmware missing", "secure boot blocking unsigned module", "module blacklisted"],
 [("Check the kernel you are running", "uname -r"),
  ("Check the adapter is visible on the bus", "lspci -k | grep -A3 -i network"),
  ("Check DKMS status for the driver", "dkms status"),
  ("Check for secure boot blocking modules", "mokutil --sb-state && dmesg | grep -i 'key was rejected'"),
  ("Try loading the module explicitly", "sudo modprobe -v DRIVER")],
 "Rebuild the DKMS module for the running kernel, sign it (or disable secure boot), or boot the previous kernel until the fix lands."),
("DNS resolution is slow (seconds per lookup)",
 "Everything works but each new domain takes seconds.",
 ["a dead first nameserver in resolv.conf", "broken IPv6 route with no fallback", "systemd-resolved cache disabled", "upstream server slow"],
 [("Check which DNS servers are configured and their state", "resolvectl status"),
  ("Time the resolution directly against each server", "dig example.com @SERVER +stats | grep 'Query time'"),
  ("Flush the cache and re-test", "sudo resolvectl flush-caches"),
  ("Check for IPv6 reachability issues", "ping -6 -c2 2606:4700:4700::1111"),
  ("Test with a public resolver as a comparison", "dig @1.1.1.1 example.com +stats")],
 "Remove or replace the dead nameserver, disable broken IPv6 on that link if needed, and keep a cache (systemd-resolved) running."),
("A cron/script works in terminal but fails in systemd",
 "The exact command works by hand, the unit fails.",
 ["different environment (PATH, HOME, LANG)", "different user and permissions", "no TTY", "working directory not set", "quoting differences"],
 [("Compare environments", "systemd-run --user --wait --pipe env | sort  (vs your shell's env)"),
  ("Set explicit paths in the unit", "Environment=PATH=/usr/local/bin:/usr/bin:/bin"),
  ("Set the working directory explicitly", "WorkingDirectory=/srv/app"),
  ("Check the unit's own log", "journalctl -u myunit -n 50 --no-pager"),
  ("Run it once through systemd with full output", "sudo systemd-run --unit=test1 --wait --pipe /path/script.sh")],
 "Make the unit self-contained: absolute paths, explicit Environment=, WorkingDirectory=, and the right User=. Environment differences are the number-one cause."),
("Mounted drive shows wrong permissions for all users",
 "An NTFS/exFAT drive is root-only or ignores chmod.",
 ["filesystem does not support POSIX permissions", "mount options omit uid/gid/umask", "mounted by root without user options"],
 [("Check how it is mounted and with which options", "mount | grep /dev/sdb1"),
  ("Remount with explicit ownership options", "sudo umount /mnt/data && sudo mount -o uid=$(id -u),gid=$(id -g),umask=022 /dev/sdb1 /mnt/data"),
  ("Make it persistent in fstab", "echo 'UUID=XXXX /mnt/data exfat uid=1000,gid=1000,umask=022 0 0' | sudo tee -a /etc/fstab"),
  ("Verify after remount", "ls -l /mnt/data | head")],
 "Foreign filesystems need mount-time identity options (uid, gid, umask) - chmod cannot store POSIX permissions there."),
("Login loop: correct password, straight back to login",
 "The desktop flashes and returns to the login screen.",
 ["full home partition or quota", "broken ~/.Xauthority or session files", "GPU driver crash at session start", "a broken shell profile"],
 [("Log in on a TTY and check disk space", "df -h ~"),
  ("Check the session's crash log", "journalctl -b -p err --no-pager | tail -40"),
  ("Move aside session state and retry", "mv ~/.config/gnome-session ~/.config/gnome-session.bak"),
  ("Check the X/Wayland auth files", "ls -la ~/.Xauthority"),
  ("Try a different session from the login screen", "select 'GNOME on Xorg' or a plain session in the gear menu")],
 "Free the disk, remove the corrupted session state, or fix the driver. The journal at the moment of logout names the failing component."),
("Sound device missing after update",
 "The sound card vanished from settings.",
 ["kernel module not loaded", "firmware regression", "PipeWire wireplumber crashed", "the device is soft-blocked"],
 [("Check whether the card exists at kernel level", "aplay -l"),
  ("Check the module", "lsmod | grep snd"),
  ("Restart the user audio stack", "systemctl --user restart wireplumber pipewire pipewire-pulse"),
  ("Check firmware errors", "dmesg | grep -i firmware | tail"),
  ("Check for soft blocks", "rfkill list 2>/dev/null")],
 "Reload the module or restart the audio stack; if the kernel no longer sees the card, it is firmware/driver - boot the previous kernel to confirm."),
("rm says 'Argument list too long'",
 "Deleting many files with a wildcard fails.",
 ["the shell expands the glob into more arguments than execve allows", "ext4 directory with millions of entries"],
 [("Delete in batches through find and xargs", "find /path -maxdepth 1 -name '*.tmp' -print0 | xargs -0 rm -f"),
  ("Or let find do the deletion", "find /path -maxdepth 1 -name '*.tmp' -delete"),
  ("For millions of entries in one directory, delete in waves", "find /path -maxdepth 1 -type f | head -10000 | xargs rm -f")],
 "Never let the shell expand the glob; let find stream the names into rm. Repeat until empty for truly huge directories."),
("Screen resolution or refresh rate wrong",
 "Only a low resolution is offered, or the screen flickers.",
 ["missing GPU driver (falls back to llvmpipe)", "wrong mode not exposed by the monitor EDID", "Wayland vs X11 differences", "bad cable or adapter"],
 [("Check which driver and renderer are in use", "glxinfo | grep -E 'OpenGL renderer|direct rendering'"),
  ("Check the kernel driver", "lspci -k | grep -A3 -i vga"),
  ("List available modes", "xrandr  (on X11)"),
  ("Check for EDID read failures", "dmesg | grep -iE 'edid|drm' | tail"),
  ("On Wayland, check the compositor's mode list", "gnome-randr  (or the Settings app)")],
 "Install/enable the proper GPU driver first - software rendering cannot offer real modes. If the mode is genuinely absent, add it manually with xrandr (X11) or via a custom EDID."),
("System runs out of disk in /tmp",
 "Builds or apps fail when /tmp fills up.",
 ["a tool writing huge temp files", "no cleanup of old temp files", "tmpfs sized too small", "a crash left multi-GB dumps"],
 [("See what is in /tmp, largest first", "du -sh /tmp/* 2>/dev/null | sort -h | tail"),
  ("Check whether /tmp is tmpfs and its size", "df -h /tmp && mount | grep /tmp"),
  ("Clear old temp files owned by you", "find /tmp -maxdepth 1 -user $(id -u) -mtime +1 -exec rm -rf {} +"),
  ("Check for core dumps", "coredumpctl list")],
 "Delete the stale files, point the tool's temp dir elsewhere (TMPDIR=/var/tmp), and for tmpfs sizing adjust fstab. coredumpctl can reclaim huge dumps."),
("Chromium/Electron app shows a blank window",
 "The window opens but stays empty.",
 ["GPU compositing problem", "missing --no-sandbox in a restricted environment", "a crashed renderer", "wrong Wayland backend", "profile corruption"],
 [("Run it with GPU disabled to test", "app --disable-gpu"),
  ("Check the renderer crash in the log", "journalctl --user -n 50 --no-pager | grep -i renderer"),
  ("Try the other ozone platform", "app --ozone-platform=x11"),
  ("Start with a clean profile", "app --user-data-dir=/tmp/test-profile"),
  ("Check for missing libraries", "ldd /path/to/app | grep 'not found'")],
 "Usually --disable-gpu or --ozone-platform=x11 isolates it to the graphics stack; otherwise a clean profile or the missing library fixes it."),
("Can't write to a mounted Samba/NFS share",
 "Mount works but writes fail with permissions.",
 ["uid/gid mapping differs between server and client", "root_squash on NFS", "SMB credentials lack write rights", "mount options missing rw"],
 [("Check the mount options actually in use", "mount | grep -E 'nfs|cifs'"),
  ("Check server-side permissions", "ls -ln /mnt/share | head"),
  ("For NFS, check for root_squash", "cat /etc/exports  (on the server)"),
  ("Remount SMB with the right credentials and uid", "sudo mount -t cifs //server/share /mnt/s -o username=u,uid=$(id -u),gid=$(id -g)"),
  ("Test with a simple write", "touch /mnt/share/probe && rm /mnt/share/probe")],
 "Make the client and server agree on identity: uid/gid options for SMB, no_root_squash (or proper user mapping) for NFS."),
("Package manager database is locked",
 "apt fails with 'Could not get lock /var/lib/dpkg/lock'.",
 ["another apt/dpkg process is running", "an unattended-upgrade is in progress", "a crashed apt left stale locks", "a package manager GUI is open"],
 [("Check for running package processes first", "ps aux | grep -E 'apt|dpkg' | grep -v grep"),
  ("Wait for it or let it finish - do not kill dpkg mid-transaction", "systemctl status unattended-upgrades"),
  ("If truly stale (no process), remove the locks", "sudo rm /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/apt/archives/lock"),
  ("Then repair any interrupted state", "sudo dpkg --configure -a")],
 "Almost always: wait. Killing a package manager mid-write is how databases break; only remove locks when no process holds them."),
("Wayland app refuses to start, X11 version works",
 "App errors about display or crashes under Wayland.",
 ["no Wayland backend in the toolkit", "missing XWayland", "portal service not running", "screen capture APIs blocked by Wayland security"],
 [("Check the session type", "echo $XDG_SESSION_TYPE"),
  ("Force the X11 backend for that app", "GDK_BACKEND=x11 app  /  QT_QPA_PLATFORM=xcb app"),
  ("Check XWayland is available", "which Xwayland"),
  ("Check the portals", "systemctl --user status xdg-desktop-portal --no-pager")],
 "Force the app's X11 backend as a workaround; the real fix is a toolkit/portal update. Screen capture and global hotkeys need portals on Wayland by design."),
("The system does not shut down or reboot",
 "The machine hangs on shutdown with a spinning screen.",
 ["a unit refusing to stop", "a stuck NFS/network mount", "a process ignoring SIGTERM", "a kernel/driver hang"],
 [("Watch the shutdown messages (Esc on the splash)", "press Esc during shutdown to see units stopping"),
  ("From the journal after a forced power-off, check the last boot", "journalctl -b -1 -n 80 --no-pager"),
  ("Look for units that took long to stop", "journalctl -b -1 | grep -iE 'stopped|timed out' | tail -40"),
  ("Check for network mounts", "mount | grep -E 'nfs|cifs'"),
  ("Identify processes ignoring TERM next time", "ps -eo pid,stat,cmd | awk '$2 ~ /D/'")],
 "Fix or mask the unit that blocks shutdown; add noauto/x-systemd options to network mounts; a D-state process usually means an IO problem underneath."),
("New user cannot log in graphically",
 "Password accepted in TTY but the GUI refuses.",
 ["home directory missing or wrong ownership", "shell set to nologin", "account locked", "GDM/PAM misconfiguration"],
 [("Check the account state", "sudo passwd -S USER && sudo usermod -s /bin/bash USER"),
  ("Check home ownership", "ls -ld /home/USER"),
  ("Fix ownership if needed", "sudo chown -R USER:USER /home/USER"),
  ("Check the auth log for the refusal reason", "journalctl -u gdm -n 50 --no-pager"),
  ("Check the shell is valid", "getent passwd USER")],
 "Recreate or fix the home directory, set a valid shell, unlock the account. The auth log states the exact PAM stage that refused."),
("An executable refuses to run: 'Permission denied' though +x is set",
 "chmod +x done, still Permission denied.",
 ["the filesystem is mounted noexec", "the shebang interpreter is missing", "wrong architecture", "the binary was truncated during copy", "apparmor/selinux denial"],
 [("Check mount options for noexec", "mount | grep ' /home'"),
  ("Check the interpreter the script wants", "head -1 ./script.sh && ls -l $(head -1 ./script.sh | cut -c3-)"),
  ("Check the binary format", "file ./binary"),
  ("Run through the loader for a clearer error", "/lib64/ld-linux-x86-64.so.2 ./binary"),
  ("Check for security module denials", "sudo dmesg | grep -iE 'apparmor|denied' | tail")],
 "Remount without noexec, install the missing interpreter, or use the right architecture build. AppArmor denials are visible in dmesg with the profile name."),
("Text file has wrong encoding, shows strange characters",
 "Files from Windows show or store mangled characters.",
 ["CRLF line endings", "wrong charset (latin-1 vs utf-8)", "BOM markers", "locale mismatch"],
 [("Detect the encoding", "file -bi thefile.txt"),
  ("Inspect invisible characters", "cat -A thefile.txt | head"),
  ("Convert CRLF to LF", "sed -i 's/\\r$//' thefile.txt  (or: dos2unix thefile.txt)"),
  ("Convert charset", "iconv -f ISO-8859-1 -t UTF-8 in.txt > out.txt"),
  ("Check your locale", "locale")],
 "Convert line endings and charset explicitly, and set a UTF-8 locale. For archives, fix before extracting so filenames decode correctly."),
("Package holds old kernel and /boot fills up",
 "Updates fail: '/boot is full'.",
 ["many installed kernels", "large initramfs images", "small /boot partition"],
 [("Check usage", "df -h /boot"),
  ("List installed kernels", "dpkg -l 'linux-image-*' | grep ^ii"),
  ("Remove the oldest kernels (never the running one)", "sudo apt autoremove --purge"),
  ("Check what is consuming /boot", "du -sh /boot/* | sort -h | tail"),
  ("Verify the running kernel before cleanup", "uname -r")],
 "Let autoremove purge old kernels, or remove specific old linux-image packages, keeping the running one and one fallback."),
("Process uses 100% of one core and cannot be killed",
 "kill -9 seems to do nothing.",
 ["uninterruptible sleep (D state) on IO", "kernel thread", "a stuck NFS mount", "firmware/driver hang"],
 [("Check the process state", "ps -o pid,stat,wchan,cmd -p PID"),
  ("D state means IO wait - check the disk", "iostat -xz 1 3"),
  ("Check kernel messages", "dmesg -T | tail -30"),
  ("If it is an NFS hang, check the mount", "mount | grep nfs && nfsstat -m"),
  ("Reboot may be the only way out of a driver hang", "sudo reboot (after saving work)")],
 "SIGKILL cannot kill D-state processes; fix the underlying IO (disk, network mount). A hung driver often needs a reboot - note it for a bug report."),
("Newly installed program is not found in PATH",
 "command not found right after installing.",
 ["the binary is in a non-standard directory", "PATH was not updated", "hash cache in the shell is stale", "it is a shell function or alias", "the package installed a different name"],
 [("Find where it actually is", "dpkg -L PACKAGE | grep bin/  (or: find / -name 'program' -type f 2>/dev/null)"),
  ("Check your PATH", "echo $PATH"),
  ("Refresh the shell's command hash", "hash -r"),
  ("Check what the name resolves to", "type -a program"),
  ("Run it by full path to confirm it works", "/usr/local/bin/program --version")],
 "Add the directory to PATH in your shell rc, run hash -r, and double-check the real binary name - some packages install versioned names."),
("Memory shows high usage but system is healthy",
 "free shows almost no free memory; is this a problem?",
 ["Linux uses free RAM as cache", "buff/cache is reclaimable", "available is the number that matters"],
 [("Read the numbers correctly", "free -h"),
  ("Watch the available column under load", "watch -n2 free -h"),
  ("Check swap activity - that is the real pressure signal", "vmstat 1 5"),
  ("Identify real consumers", "ps aux --sort=-%mem | head")],
 "This is normal. Compare 'available', not 'free'. Only worry when available is small and swap in/out (si/so) is active."),
("Firmware update is offered but the tool fails",
 "fwupd reports errors.",
 ["device not supported by fwupd", "LVFS metadata stale", "permissions/daemon issue", "firmware write blocked by power settings"],
 [("Check the device is recognized", "fwupdmgr get-devices"),
  ("Refresh metadata", "fwupdmgr refresh"),
  ("See pending updates", "fwupdmgr get-updates"),
  ("Check the daemon", "systemctl status fwupd --no-pager"),
  ("Apply updates (AC power!)", "fwupdmgr update")],
 "Refresh and retry; if the device is unsupported, use the vendor's own updater. Never update firmware on low battery."),
("CRON job runs but script fails on relative paths",
 "The job fires; log shows 'No such file or directory'.",
 ["cron's working directory is the user's home", "relative paths in the script", "PATH does not include /usr/local/bin", "locale or TZ differences"],
 [("Make every path absolute in the script", "grep -nE '[^/]\\w+/' script.sh"),
  ("Set an explicit working directory", "cd /srv/app || exit 1  at the top of the script"),
  ("Export a sane environment at the top", "PATH=/usr/local/bin:/usr/bin:/bin"),
  ("Log everything while debugging", "*/5 * * * * /path/script.sh >> /var/log/script.log 2>&1")],
 "Scripts for cron must be self-contained: absolute paths, explicit cd, explicit PATH, and output redirected to a log you actually read."),
("BTRFS filesystem reports errors",
 "btrfs commands show read/write errors or a failed scrub.",
 ["failing disk", "bit rot (checksum mismatch)", "memory errors", "loose SATA cable"],
 [("Check device error counters", "sudo btrfs device stats /"),
  ("Start a scrub and watch it", "sudo btrfs scrub start -B /"),
  ("Check SMART immediately", "sudo smartctl -a /dev/nvme0n1"),
  ("Look for the failing file in the log", "sudo journalctl -k | grep -i btrfs | tail -30"),
  ("If a disk is failing, replace it with btrfs replace", "sudo btrfs replace start /dev/old /dev/new /")],
 "Fix the hardware first (cable/disk). BTRFS checksum errors with healthy hardware usually mean RAM - run a memtest before trusting the pool."),
("Terminal shows garbage after binary output",
 "The terminal is full of strange characters.",
 ["a binary file was catted to the terminal", "wrong TERM value", "UTF-8 output to a non-UTF-8 locale", "an escape sequence set an odd charset"],
 [("Reset the terminal state", "reset  (or: tput reset)"),
  ("Check the TERM variable", "echo $TERM"),
  ("Check locale", "locale | head -3"),
  ("Next time, pipe binary output through cat -v or less", "cat -v binary.bin | head")],
 "reset fixes almost every mangled terminal. Avoid cat-ing binaries; use xxd or strings."),
("A GUI app scales wrongly on HiDPI",
 "Tiny or huge UI on a high-resolution screen.",
 ["fractional scaling settings", "toolkit-specific scale factors", "X11 app under Wayland scaling", "monitor DPI misreported"],
 [("Check the desktop's scaling setting", "gsettings get org.gnome.desktop.interface text-scaling-factor"),
  ("Check GDK scaling", "gsettings get org.gnome.desktop.interface scaling-factor"),
  ("For GTK apps, try an explicit scale", "GDK_SCALE=2 app"),
  ("For Qt apps", "QT_SCALE_FACTOR=1.5 app"),
  ("Check the monitor's reported size", "xrandr --verbose | grep -A2 ' connected'")],
 "Set the desktop scale first; for stubborn toolkits, override per-app with GDK_SCALE / QT_SCALE_FACTOR."),
("Shared library version conflict breaks an app",
 "App fails after installing something else: symbol lookup error.",
 ["LD_LIBRARY_PATH override", "duplicate libraries in /usr/local/lib", "ldconfig cache stale", "a package downgraded a shared lib"],
 [("See which libraries it resolves", "ldd ./app | head -20"),
  ("Check the loader search path", "ldconfig -p | grep LIBNAME"),
  ("Check for LD_LIBRARY_PATH interference", "echo $LD_LIBRARY_PATH"),
  ("Refresh the loader cache", "sudo ldconfig"),
  ("Trace the actual resolution failure", "LD_DEBUG=libs ./app 2>&1 | grep -i 'searching\\|trying' | head -30")],
 "Remove the rogue library or LD_LIBRARY_PATH entry, run ldconfig, and prefer packaged libraries over hand-copied ones in /usr/local/lib."),
("Random freezes under load",
 "The whole system stutters or locks briefly.",
 ["memory pressure and reclaim", "IO saturation", "GPU driver stalls", "thermal throttling", "kernel bug"],
 [("Check memory pressure and swap", "vmstat 1 10"),
  ("Check IO saturation", "iostat -xz 1 10"),
  ("Check temperatures", "sensors"),
  ("Check kernel messages for stalls", "dmesg -T | grep -iE 'stall|hung|reset' | tail -30"),
  ("Check for firmware/BIOS updates if reproducible", "sudo fwupdmgr get-updates")],
 "Attack the specific resource that saturates. Reproducible freezes with clean logs point at firmware/driver - update, or boot an older kernel to bisect."),
("Journal takes gigabytes of disk",
 "journalctl --disk-usage shows a huge number.",
 ["no size limit configured", "verbose units spamming the log", "debug logging left on"],
 [("See the usage and the noisiest units", "journalctl --disk-usage && journalctl --no-pager | wc -l"),
  ("Vacuum to a sane size", "sudo journalctl --vacuum-size=200M"),
  ("Cap it permanently", "set SystemMaxUse=200M in /etc/systemd/journald.conf then restart systemd-journald"),
  ("Find the noisy service", "journalctl -b --no-pager | awk '{print $5}' | sort | uniq -c | sort -rn | head")],
 "Vacuum now, cap the size in journald.conf, and fix the unit that logs in a loop."),
("Dual boot: Windows entry missing from GRUB",
 "After installing/updating Windows the menu does not show it.",
 ["os-prober disabled", "Windows bootloader on another ESP", "GRUB config not regenerated", "fast startup left the NTFS dirty"],
 [("Check os-prober is enabled and run it", "sudo os-prober"),
  ("Regenerate the GRUB config", "sudo update-grub"),
  ("Check for the Windows EFI files", "ls /boot/efi/EFI/Microsoft/Boot/bootmgfw.efi"),
  ("If missing, check the other disk's ESP", "sudo fdisk -l | grep -i efi"),
  ("Disable Windows Fast Startup if NTFS is dirty", "powercfg /h off  (in Windows)")],
 "Enable os-prober, regenerate grub.cfg, and make sure the ESP with the Windows loader is mounted and scanned. Fast Startup must be off for clean dual-boot."),
("Application writes logs but you see nothing in journalctl",
 "The app logs to a file, not the journal.",
 ["the app writes its own file", "stdout goes to a socket or /dev/null", "unit type is simple with no capture", "log level too high"],
 [("Check where the unit sends output", "systemctl cat myapp"),
  ("Look at the app's own log location", "find /var/log -name '*myapp*'"),
  ("Watch the unit's stdout if it is journald", "journalctl -u myapp -f"),
  ("Increase verbosity temporarily", "sudo systemctl edit myapp  (add Environment=LOG_LEVEL=debug)")],
 "Look where the app actually writes: its own file, syslog, or stdout captured by journald. systemctl cat shows the configured streams."),
("New device works only as root",
 "The device node or interface is root-only.",
 ["udev rule missing", "device permissions 0600", "group membership missing", "logind session not active"],
 [("Check the device node and its group", "ls -l /dev/DEVICE"),
  ("Check your groups", "id"),
  ("Add yourself to the owning group", "sudo usermod -aG GROUP $USER"),
  ("Re-login for group changes to apply", "loginctl terminate-user $USER  (or just log out)"),
  ("Check udev sees the device", "udevadm info -q all -n /dev/DEVICE | head -30")],
 "Join the right group and re-login - group membership only applies to new sessions."),
("The system cannot find a command that exists in /usr/local/bin",
 "Installed a tool manually; command not found.",
 ["/usr/local/bin not in PATH", "binary not executable", "installed to a versioned name", "shell hash cache stale"],
 [("Confirm the file exists and is executable", "ls -l /usr/local/bin/TOOL"),
  ("Run it by absolute path", "/usr/local/bin/TOOL --version"),
  ("Check PATH ordering", "echo $PATH | tr ':' '\\n'"),
  ("Fix PATH persistently", "echo 'export PATH=/usr/local/bin:$PATH' >> ~/.profile"),
  ("Refresh the hash table", "hash -r")],
 "Add the directory to PATH in your shell profile, ensure the execute bit, and run hash -r in the current shell."),
("Firewall blocks a local service after enabling ufw",
 "A dev server worked; after ufw enable, it is unreachable.",
 ["ufw default deny incoming", "the port is not allowed", "the app binds only to localhost", "ufw rule order"],
 [("Check ufw status and rules", "sudo ufw status verbose"),
  ("Allow the specific port", "sudo ufw allow 8080/tcp"),
  ("Check what the app binds to", "ss -tlnp | grep 8080"),
  ("If it binds to 127.0.0.1 only, that is why remote clients cannot reach it", "bind to 0.0.0.0 in the app config if intended"),
  ("Re-test from the client side", "nc -vz server 8080")],
 "Allow the port in ufw and make sure the app listens on the interface you think it does. Binding to localhost is invisible from the network by design."),
("Updates fail with TLS/certificate errors",
 "apt or git refuses with certificate problems.",
 ["system clock wrong", "expired CA bundle", "corporate proxy interception", "TLS interception by antivirus"],
 [("Check the clock first - it causes most of these", "timedatectl && date"),
  ("Update the CA certificates", "sudo apt install --reinstall ca-certificates"),
  ("Check proxy environment variables", "env | grep -i proxy"),
  ("Test the endpoint directly", "curl -v https://deb.debian.org 2>&1 | tail -20")],
 "Fix the clock, refresh ca-certificates, and remove or trust the intercepting proxy. Never disable TLS verification globally to 'fix' this."),
("Random reboots or kernel panics",
 "The machine restarts without warning.",
 ["hardware fault (RAM, PSU, thermals)", "overclock instability", "kernel driver bug", "failing disk"],
 [("Check the previous boot for panic traces", "journalctl -k -b -1 | tail -60"),
  ("Check temperatures right before the crash", "sensors  (and check logs for thermal events)"),
  ("Run a memory test", "memtester 2G 1  (or boot memtest86+)"),
  ("Check the disk's SMART health", "sudo smartctl -H /dev/nvme0n1"),
  ("Check for firmware updates", "sudo fwupdmgr get-updates")],
 "Look for the pattern: thermal (clean the fans), RAM (memtest), PSU (heavy-load reboots), driver (previous kernel bisect). Hardware first, software second."),
("The 'device is busy' on umount",
 "umount fails: target is busy.",
 ["a shell cd'd into the mount", "an editor or process has a file open there", "a container bind-mount", "NFS clients"],
 [("Find the processes using it", "lsof +f -- /mnt/usb  (or: fuser -vm /mnt/usb)"),
  ("Check for shells sitting inside", "ls -l /proc/*/cwd 2>/dev/null | grep /mnt/usb"),
  ("Close them, or kill the offending process", "kill PID"),
  ("Lazy unmount as a last resort", "sudo umount -l /mnt/usb")],
 "Find and close what holds the mount. lazy unmount detaches now and cleans up later - data may still be flushing, so prefer the real fix."),
("Flatpak app has no access to files",
 "A sandboxed app cannot see the home directory.",
 ["Flatpak sandbox permissions", "portal not running", "filesystem permissions not granted"],
 [("See the app's current permissions", "flatpak info --show-permissions APP_ID"),
  ("Grant access interactively with Flatseal or", "flatpak override --user --filesystem=home APP_ID"),
  ("Check portals are running", "systemctl --user status xdg-desktop-portal --no-pager"),
  ("Re-launch the app fully", "flatpak run APP_ID")],
 "Grant the narrowest filesystem permission the app actually needs; portals handle file pickers without full home access."),
("Bash script has a syntax error that makes no sense",
 "bash reports an error at a line that looks fine.",
 ["an unclosed quote or bracket above the reported line", "CRLF line endings from Windows", "an unescaped special character in a heredoc", "a missing fi/done/esac"],
 [("Check the whole file without running it", "bash -n script.sh"),
  ("Show line endings", "cat -A script.sh | head -20"),
  ("Fix CRLF endings", "sed -i 's/\\r$//' script.sh"),
  ("Trace execution to see where it derails", "bash -x script.sh 2>&1 | tail -30")],
 "The reported line is usually a symptom; the cause is earlier. bash -n and cat -A find 90% of these."),
("The mouse or keyboard stops responding",
 "Input freezes, sometimes with the system otherwise alive.",
 ["USB autosuspend", "kworker/USB controller issue", "driver crash", "hardware failure"],
 [("Check kernel messages around the freeze", "dmesg -T | tail -50"),
  ("Check for USB resets", "dmesg -T | grep -iE 'usb.*reset|disconnect' | tail"),
  ("Disable USB autosuspend for the device as a test", "echo -1 | sudo tee /sys/bus/usb/devices/usb*/power/autosuspend"),
  ("Check input devices are still enumerated", "lsusb && libinput list-devices 2>/dev/null | head")],
 "A USB reset storm usually means power or cable; autosuspend quirks are fixable with a udev rule. If it is a PS/2-free laptop, test with an external device."),
("Writes to an SSD are extremely slow",
 "The disk became slow after being fast.",
 ["almost full SSD (no free blocks for wear leveling)", "TRIM not running", "SATA link at low speed", "thermal throttling of the SSD", "failing drive"],
 [("Check free space and TRIM support", "df -h / && sudo hdparm -I /dev/sda | grep -i trim"),
  ("Run fstrim manually", "sudo fstrim -v /"),
  ("Check the link speed", "sudo hdparm -I /dev/sda | grep -i speed"),
  ("Check the drive temperature and health", "sudo smartctl -A /dev/sda | grep -iE 'temp|wear|percent'")],
 "Keep 10-20% free on SSDs, enable the fstrim timer, and check SMART wear values - a worn drive is slow because it is dying."),
("An app window is missing from the taskbar/dock",
 "The window exists but has no dock entry.",
 ["the app sets skip-taskbar", "the .desktop file does not match the WM class", "a shell extension glitch"],
 [("Check the window's WM class", "xprop WM_CLASS  (click the window)"),
  ("Check the .desktop file's StartupWMClass", "grep -i startupwmclass ~/.local/share/applications/*.desktop"),
  ("Align the two", "set StartupWMClass in the desktop file to the real WM_CLASS"),
  ("Restart the shell as a last resort", "press Alt+F2, r, Enter  (X11)  /  log out-in (Wayland)")],
 "The dock matches windows to apps by WM class; make the .desktop file agree with what the app actually sets."),
]
